- installer/Dockerfile-dev
> perf: 精简构建

- config_example.yml
> perf: 优化注释

- apps/application/serializers/chat_serializers.py
- apps/application/urls.py
- apps/application/views/chat_views.py
- pyproject.toml
- ui/src/api/log.ts
- ui/src/styles/app.scss
- ui/src/views/log/index.vue
> feat: 支持应用对话日志导出

- apps/application/chat_pipeline/pipeline_manage.py
- apps/application/chat_pipeline/step/chat_step/i_chat_step.py
- apps/application/chat_pipeline/step/chat_step/impl/base_chat_step.py
- apps/application/chat_pipeline/step/generate_human_message_step/i_generate_human_message_step.py
- apps/application/chat_pipeline/step/reset_problem_step/i_reset_problem_step.py
- apps/application/chat_pipeline/step/search_dataset_step/i_search_dataset_step.py
fixed typo.
PiplineManage -> PipelineManage
> refactor: fix typo

- ui/src/views/user-manage/component/UserDialog.vue
- ui/src/views/user-manage/component/UserPwdDialog.vue
- ui/src/views/user-manage/index.vue
> refactor: remove unused element

- apps/common/constants/permission_constants.py
> docs: 修改注释的错别字

- ui/src/utils/message.ts
> fix: typos

- ui/src/views/dataset/CreateDataset.vue
> fix(dataset): 删除注释

- apps/common/field/common.py
> fix: 统一为中文简体

- main.py
> docs: 修改注释中的错别字

- ui/src/views/problem/component/RelateProblemDialog.vue
> fix: 修复文档为空的情况#92

- ui/tsconfig.node.json
> chore(TS): skipLibCheck

- README.md
> docs: 修改单词拼写

- ui/tsconfig.app.json
> Update tsconfig.app.json config

- apps/common/util/file_util.py
- apps/smartdoc/conf.py
> perf: 优化代码和错误提示

- ui/tsconfig.vitest.json
> Update tsconfig.vitest.json config

- .github/workflows/typos_check.yml
> chore: 增加拼写检测Action

- ui/src/router/routes.ts
- ui/src/views/404/index.vue
> perf: 优化提示和待办描述

- ui/src/views/template/component/CreateModelDialog.vue
- ui/src/views/template/component/EditModel.vue
> style: 简化样式代码

- ui/src/views/problem/component/RelateProblemDialog.vue
> fix: 【知识库】当文档为空时，关联分段错误修复

- apps/common/util/split_model.py
> fix: PDF上传知识库开始导入接口报错 #122

- ui/src/styles/element-plus.scss
- ui/src/views/paragraph/component/ProblemComponent.vue
> fix:【问题管理】添加关联问题时，问题过长下拉组件样式优化(#80)

- ui/index.html
> fix: 去除应用内嵌

- apps/setting/models_provider/impl/openai_model_provider/openai_model_provider.py
> fix: 支持 OpenAI 兼容模型 #142

- ui/src/views/dataset/component/UploadComponent.vue
> feat: 【知识库】上传文档时，支持选择文件夹(#36)

- ui/src/components/ai-chat/index.vue
> fix: 知识库问答问题限制字符数量(#148)

- ui/src/api/type/application.ts
> perf: 优化AI回答 #132

- apps/setting/models_provider/impl/openai_model_provider/model/openai_chat_model.py
- apps/setting/models_provider/impl/openai_model_provider/openai_model_provider.py
> fix: 修复openai模型在对接其他兼容openai接口平台时获取tokens错误

- ui/src/views/log/component/EditContentDialog.vue
> Pr@main@feat filterable

- ui/src/views/template/component/CreateModelDialog.vue
- ui/src/views/template/component/EditModel.vue
It provides users with some tips when adding/modifying models
Add additional tips via a tooltip to form items.
> perf: 优化模型设置的添加/修改模型的提示

- apps/common/auth/handle/impl/application_key.py
> fix: 对话API调用,输出报错 #192

- apps/application/serializers/application_serializers.py
> fix: 应用修改时保存提示未携带检索模式

- apps/embedding/migrations/0002_embedding_search_vector.py
> fix: 分词检索历史数据处理

- ui/src/components/read-write/index.vue
- ui/src/views/document/index.vue
- ui/src/views/problem/index.vue
> perf: 快速修改文档名称和问题，支持回车保存

- apps/embedding/migrations/0002_embedding_search_vector.py
- ui/src/components/ai-chat/index.vue
> Pr@main@perf stream

- apps/application/serializers/chat_serializers.py
- apps/application/views/chat_views.py
- apps/common/auth/handle/impl/application_key.py
- apps/common/auth/handle/impl/public_access_token.py
- apps/common/auth/handle/impl/user_token.py
- apps/common/constants/permission_constants.py
> fix: 应用修改获取对话详情被拒绝

- ui/src/components/ai-chat/index.vue
> fix: 修复对话Id缺失问题

- ui/src/components/dynamics-form/items/table/TableCheckbox.vue
- ui/src/components/dynamics-form/items/table/TableRadio.vue
- ui/src/views/application/index.vue
- ui/src/views/dataset/index.vue
- ui/src/views/document/index.vue
- ui/src/views/log/index.vue
- ui/src/views/paragraph/index.vue
- ui/src/views/problem/component/RelateProblemDialog.vue
- ui/src/views/problem/index.vue
- ui/src/views/team/component/PermissionSetting.vue
- ui/src/views/team/index.vue
- ui/src/views/template/index.vue
- ui/src/views/user-manage/index.vue
> perf: 搜索框可以支持一键清除(#252)

- ui/src/layout/components/breadcrumb/index.vue
- ui/src/views/application-overview/component/EditAvatarDialog.vue
> 修复设置Logo问题

- ui/src/views/application/components/ParamSettingDialog.vue
- ui/src/views/hit-test/index.vue
> perf: 优化检索模式参数设置

- apps/common/config/tokenizer_manage_config.py
- apps/setting/models_provider/impl/azure_model_provider/azure_model_provider.py
- apps/setting/models_provider/impl/azure_model_provider/model/azure_chat_model.py
- apps/setting/models_provider/impl/kimi_model_provider/model/kimi_chat_model.py
- apps/setting/models_provider/impl/openai_model_provider/model/openai_chat_model.py
- apps/setting/models_provider/impl/qwen_model_provider/model/qwen_chat_model.py
- apps/setting/models_provider/impl/qwen_model_provider/qwen_model_provider.py
- apps/setting/models_provider/impl/wenxin_model_provider/model/qian_fan_chat_model.py
- apps/setting/models_provider/impl/xf_model_provider/model/xf_chat_model.py
- apps/setting/models_provider/impl/zhipu_model_provider/model/zhipu_chat_model.py
- apps/setting/models_provider/impl/zhipu_model_provider/zhipu_model_provider.py
> fix: 私有部署计算tokens报错

- apps/setting/models_provider/impl/openai_model_provider/openai_model_provider.py
- ui/src/views/template/component/CreateModelDialog.vue
- ui/src/views/template/component/EditModel.vue
perf: 增加了更多常用的OpenAI模型及其描述 & 现在可以通过tooltip正常显示ModelInfo中desc的内容
> perf: 增加了更多常用的OpenAI模型及其描述 & 现在可以通过tooltip正常显示ModelInfo中desc的内容

- ui/src/layout/components/top-bar/index.vue
> perf: 隐藏国际化按钮

- apps/setting/models_provider/impl/ollama_model_provider/ollama_model_provider.py
> perf: 增加ollama基础模型选项

- apps/dataset/serializers/document_serializers.py
- apps/dataset/swagger_api/document_api.py
- apps/dataset/urls.py
- apps/dataset/views/document.py
- ui/src/api/document.ts
- ui/src/views/document/component/BatchEditDocumentDialog.vue
- ui/src/views/document/index.vue
> feat: 文档批量设置命中处理方式

- apps/application/chat_pipeline/step/chat_step/i_chat_step.py
- apps/application/chat_pipeline/step/chat_step/impl/base_chat_step.py
- apps/application/chat_pipeline/step/reset_problem_step/i_reset_problem_step.py
- apps/application/chat_pipeline/step/reset_problem_step/impl/base_reset_problem_step.py
- apps/application/serializers/application_serializers.py
- apps/application/serializers/chat_message_serializers.py
- apps/application/serializers/chat_serializers.py
- ui/src/components/ai-chat/index.vue
- ui/src/views/application/CreateAndSetting.vue
> perf: 应用模型不必填

- ui/src/components/ai-chat/index.vue
> fix: 快捷文档点击无法发送

- apps/application/chat_pipeline/step/chat_step/impl/base_chat_step.py
> perf: 优化未配置ai模型回答

- ui/src/api/type/application.ts
> fix: 【问答页面】提问达到最大限制的时候 返回内容重复。

- apps/application/chat_pipeline/step/chat_step/impl/base_chat_step.py
- apps/application/chat_pipeline/step/reset_problem_step/impl/base_reset_problem_step.py
> fix: 处理获取tokens失败情况

- apps/common/util/rsa_util.py
> perf: 优化超长文本rsa加密解密

- apps/embedding/migrations/0002_embedding_search_vector.py
> perf: 优化历史数据分词处理兜底操作

- ui/src/views/log/component/ChatRecordDrawer.vue
> perf: 对话日志摘要样式优化

- apps/application/chat_pipeline/step/generate_human_message_step/impl/base_generate_human_message_step.py
> fix: 修复当有引用分段未走应用提示词

- ui/src/api/dataset.ts
- ui/src/api/document.ts
- ui/src/request/index.ts
> fix: 延长分段接口超时时间 #306

- ui/src/views/document/index.vue
> fix: 普通文档重试按钮不生效

- apps/dataset/serializers/document_serializers.py
> fix: [知识库]相同类型的知识库之间无法迁移文档 #334

- apps/dataset/serializers/document_serializers.py
> fix: 相同类型的知识库之间迁移类型发生改变

- ui/src/components/markdown-renderer/MdRenderer.vue
> fix: ui文件打包报错 #348

- apps/dataset/serializers/document_serializers.py
> fix: 修改文档向量化重试,文档状态处理

- apps/users/serializers/user_serializers.py
> fix: 创建新用户时用户名含有 0 时校验不通过 #358

- ui/src/views/document/component/SelectDatasetDialog.vue
> perf: 优化迁移文档过滤知识库选项

- ui/src/components/app-table/index.vue
- ui/src/components/read-write/index.vue
> fix: 修复快捷修改组件问题和优化支持一键清空输入内容

- ui/src/views/paragraph/index.vue
> fix: 修复批量迁移问题

- ui/src/components/infinite-scroll/index.vue
- ui/src/layout/components/top-bar/avatar/AboutDialog.vue
- ui/src/views/dataset/component/ParagraphList.vue
- ui/src/views/dataset/step/StepSecond.vue
> fix: 修复版本号翻译问题

- ui/src/components/login-layout/index.vue
> perf: 优化登录页面

- ui/src/views/document/component/ImportDocumentDialog.vue
> fix: 文档设置相似度问题修复

- ui/src/components/app-table/index.vue
- ui/src/views/document/index.vue
- ui/src/views/problem/index.vue
> fix: 文档和问题批量删除问题修复

- README.md
> 更新了README.md

- ui/src/views/dataset/component/EditParagraphDialog.vue
- ui/src/views/dataset/step/StepSecond.vue
> fix: 修复关联问题为空时导入报错(#432)

- apps/dataset/serializers/paragraph_serializers.py
> fix: 修复导入的文档删除部分的分段后，字符数不会重新计算 #421

- ui/src/views/document/component/ImportDocumentDialog.vue
> fix: 修复批量导入文档问题

- ui/src/views/document/component/ImportDocumentDialog.vue
> fix: 修复批量设置问题

- apps/dataset/serializers/paragraph_serializers.py
> fix: 修复段落嵌入,文档字符串不变

- ui/src/views/template/component/CreateModelDialog.vue
- ui/src/views/template/component/EditModel.vue
- ui/src/views/template/index.vue
> perf: 优化模型代码

- ui/src/views/template/component/CreateModelDialog.vue
- ui/src/views/template/component/EditModel.vue
> perf: 优化添加模型,关闭时清除历史模型数据

- apps/application/serializers/application_serializers.py
- apps/common/cache/mem_cache.py
> fix: 修复应用修改模型后,历史对话未使用最新模型

- ui/src/views/document/index.vue
> perf: 文档重试改为重新向量化

- ui/src/components/ai-chat/ParagraphSourceDialog.vue
> perf: 知识来源使用markdown页面显示(#457)

- ui/src/views/application/CreateAndSetting.vue
> fix: 修复翻译问题

- ui/src/components/ai-chat/OperationButton.vue
- ui/src/components/ai-chat/ParagraphSourceDialog.vue
- ui/src/components/ai-chat/index.vue
- ui/src/views/chat/pc/index.vue
> perf: 优化对话页面

- ui/src/enums/common.ts
- ui/src/enums/document.ts
- ui/src/enums/team.ts
- ui/src/layout/hooks/useResize.ts
- ui/src/stores/modules/common.ts
- ui/src/views/chat/embed/index.vue
- ui/src/views/chat/pc/index.vue
- ui/src/views/document/component/ImportDocumentDialog.vue
- ui/src/views/document/index.vue
- ui/src/views/document/utils.ts
- ui/src/views/team/component/CreateMemberDialog.vue
- ui/src/views/team/component/PermissionSetting.vue
- ui/src/views/team/index.vue
- ui/src/views/team/utils.ts
> feat: 对话演示适配移动端和部分类型优化

- ui/src/views/chat/embed/index.vue
- ui/src/views/chat/pc/index.vue
> fix: 修复对话历史记录无法点赞问题

- ui/src/views/application/components/ParamSettingDialog.vue
> feat: 引用分段数最大值增大到 100 个(#503)

- ui/index.html
- ui/src/views/application/index.vue
- ui/src/views/chat/pc/index.vue
> fix: 修复对话相关问题

- ui/src/components/ai-chat/index.vue
> fix: 开场白不支持Markdown表格语法，无法显示一个表格。 #496

- ui/index.html
- ui/src/views/chat/pc/index.vue
> perf:  ios浏览器输入框变大问题优化(#514)

- ui/src/api/dataset.ts
> fix: 修复前端打包错误

- apps/application/urls.py
- apps/common/init/init_doc.py
- apps/smartdoc/urls.py
- ui/src/views/application-overview/index.vue
> perf: 优化API_KEY调用对话文档

- apps/common/handle/handle_exception.py
> perf: 优化错误提示

- apps/dataset/sql/update_document_char_length.sql
> fix: 修复删除文档最后一个分段报错

- apps/common/handle/base_parse_qa_handle.py
- apps/common/handle/impl/qa/csv_parse_qa_handle.py
- apps/common/handle/impl/qa/xls_parse_qa_handle.py
- apps/common/handle/impl/qa/xlsx_parse_qa_handle.py
- apps/dataset/serializers/document_serializers.py
> fix: 修复qa知识库导入失败错误

- ui/src/utils/utils.ts
> fix: 文档上传添加html格式限制

- ui/src/layout/components/top-bar/avatar/AboutDialog.vue
> feat: 修复版本号问题

- ui/src/views/dataset/index.vue
> perf: 知识库重新向量化优化提示

- apps/common/handle/base_parse_qa_handle.py
- apps/common/handle/impl/qa/xlsx_parse_qa_handle.py
> fix: 修复excel导入失败问题

- ui/src/components/ai-chat/index.vue
> fix: 【用户问题】此字段不能为空字符串。 #512

- ui/src/components/ai-chat/index.vue
> fix: 修复对话用户问题不能为空字符串。 #512

- ui/src/stores/modules/application.ts
- ui/src/stores/modules/user.ts
> fix: 修复不同页签之间认证共享问题

- ui/src/locales/lang/en_US/views/application-overview.ts
- ui/src/locales/lang/zh_CN/views/application-overview.ts
> perf: 优化文案

- ui/src/views/chat/pc/index.vue
> fix: 修复导出问题

- ui/src/views/chat/embed/index.vue
- ui/src/views/hit-test/index.vue
> perf: 部分优化

- apps/common/handle/impl/html_split_handle.py
> fix: 修复文档导入解析错误

- apps/common/event/listener_manage.py
> perf: 向量化文档后修改更新时间

- apps/application/serializers/chat_serializers.py
- ui/src/views/log/component/EditContentDialog.vue
- ui/src/views/paragraph/component/ParagraphForm.vue
> fix: 修复对话日志的关联问题字符超过256个

- apps/common/util/split_model.py
> fix: 修复分段超过分段长度限制

- apps/common/init/init_doc.py
> fix: 修复通过API进行对话的API文档接口错误 #587

- apps/application/serializers/chat_message_serializers.py
> fix: 修复对话冗余代码 #590

- apps/common/util/ts_vecto_util.py
> 修复:关键词提取的bug

- apps/common/util/split_model.py
> fix: 修复导入带有表格样式的md文件分段后表格格式丢失 #615

- ui/src/components/ai-chat/index.vue
- ui/src/views/application/components/ParamSettingDialog.vue
> perf: 支持10000以上最多引用字符数(#603)(#628)

- apps/setting/models_provider/impl/wenxin_model_provider/wenxin_model_provider.py
> fix: 修复升级langchain后千帆模型无法报错

- apps/application/serializers/application_serializers.py
> fix: 修复应用最多引用字符数校验10万字符无法保存

- ui/src/workflow/common/NodeCascader.vue
> fix: 【工作流】 修复父级节点删除后,节点变量未校验问题

- ui/src/layout/components/breadcrumb/index.vue
- ui/src/views/hit-test/index.vue
> fix: 修复breadcrumb未刷新列表问题

- ui/src/components/read-write/index.vue
- ui/src/layout/components/breadcrumb/index.vue
- ui/src/workflow/common/NodeContainer.vue
> feat: 读写插件增加交互方式

- apps/application/flow/step_node/condition_node/compare/__init__.py
- apps/application/flow/step_node/condition_node/compare/is_not_null_compare.py
- apps/application/flow/step_node/condition_node/compare/is_null_compare.py
> fix: 【应用编排】判断器分支判断结果错误

- ui/src/components/ai-chat/index.vue
> fix: 修复回答为空字符串的时候也应该显示执行详情

- apps/common/util/split_model.py
> fix: 修复【知识库】高级分段 自动清洗，把所有换行被去除

- ui/src/workflow/common/app-node.ts
> fix: 【工作流】修复结束锚点不能连接到已被链接的锚点

- apps/application/flow/step_node/condition_node/compare/__init__.py
- apps/application/flow/step_node/condition_node/compare/not_contain_compare.py
> fix: 【工作流】修复判断器不包含无效问题

- CONTRIBUTING.md
> chore: use unseq list

- apps/application/flow/workflow_manage.py
- apps/application/serializers/application_serializers.py
> fix: 修复【应用编排】没有权限的知识库，名称是空白的

- apps/application/serializers/application_serializers.py
> fix: 修复【知识库】设置中关联应用未显示在高级编排中使用该知识库的应用

- apps/common/template/email_template.html
- ui/src/styles/app.scss
> feat: 规范字体

- apps/common/config/embedding_config.py
对生成的模型嵌入向量归一化,提升检索速度
1. 修改common下的embedding_config 文件，添加归一化配置型
- [*] Made sure tests are passing and test coverage is added if needed.
- [*] Made sure commit message follow the rule of [Conventional Commits specification](https://www.conventionalcommits.org/).
- [*] Considered the docs impact and opened a new docs issue or PR with docs changes if needed.
> fix: 对模型嵌入归一化,提升检索速度

- ui/src/views/document/index.vue
- ui/src/views/problem/index.vue
- ui/src/views/team/component/PermissionSetting.vue
- ui/src/views/user-manage/index.vue
--bug=1043658 --user=王孝刚 【知识库】建议把右边的操作列固定一下 https://www.tapd.cn/57709429/s/1544924
> refactor: 固定操作列

- apps/application/serializers/application_serializers.py
- apps/common/util/common.py
- apps/dataset/serializers/dataset_serializers.py
- apps/setting/serializers/valid_serializers.py
- apps/setting/swagger_api/valid_api.py
- apps/setting/urls.py
- apps/setting/views/__init__.py
- apps/setting/views/valid.py
- apps/users/serializers/user_serializers.py
- ui/src/api/type/user.ts
- ui/src/api/user.ts
- ui/src/enums/common.ts
- ui/src/request/index.ts
- ui/src/stores/modules/common.ts
- ui/src/stores/modules/user.ts
- ui/src/utils/message.ts
- ui/src/views/application/component/CreateApplicationDialog.vue
- ui/src/views/user-manage/index.vue
> feat: 接口校验

- ui/src/api/system-api-key.ts
- ui/src/layout/components/top-bar/avatar/APIKeyDialog.vue
- ui/src/layout/components/top-bar/avatar/SettingAPIKeyDialog.vue
- ui/src/layout/components/top-bar/avatar/index.vue
- ui/src/locales/lang/en_US/layout.ts
- ui/src/locales/lang/zh_CN/layout.ts
--story=1015434 --user=王孝刚 【X-pack】系统API Key管理及接口文档 https://www.tapd.cn/57709429/s/1545690
> feat: 增加系统API_Keys

- ui/src/layout/components/sidebar/SidebarItem.vue
- ui/src/router/modules/setting.ts
- ui/src/views/authentication/component/LDAP.vue
- ui/src/views/authentication/index.vue
- ui/src/views/email/index.vue
- ui/src/views/theme/index.vue
> feat: 扩展二级目录

- apps/common/auth/authenticate.py
- apps/smartdoc/settings/__init__.py
- apps/smartdoc/settings/auth.py
> fix: 优化认证逻辑

- ui/src/App.vue
- ui/src/layout/components/app-main/index.vue
- ui/src/layout/layout-template/AppLayout.vue
- ui/src/layout/layout-template/DetailLayout.vue
- ui/src/layout/layout-template/SystemLayout.vue
- ui/src/router/modules/application.ts
- ui/src/router/modules/dataset.ts
- ui/src/router/modules/setting.ts
- ui/src/router/routes.ts
- ui/src/views/authentication/index.vue
> perf: 优化页面结构

- ui/src/layout/components/sidebar/SidebarItem.vue
- ui/src/router/modules/setting.ts
- ui/src/stores/modules/user.ts
> feat: 添加菜单权限

- ui/src/layout/components/top-bar/avatar/index.vue
> perf: 优化权限控制

- ui/src/layout/components/top-bar/index.vue
- ui/src/stores/modules/user.ts
- ui/src/styles/element-plus.scss
> feat: 新增License过期提示

- ui/src/layout/components/top-bar/avatar/APIKeyDialog.vue
> feat: APIKey样式修改

- ui/src/views/login/index.vue
> feat: 更新登录页面

- apps/users/models/user.py
- apps/users/serializers/user_serializers.py
> feat: ldap

- ui/src/views/authentication/component/LDAP.vue
> refactor: ldap

- ui/src/views/application-overview/index.vue
- ui/src/views/template/component/ModelCard.vue
> fix: 修复打开doc/chat显示404(#747)

- ui/src/workflow/nodes/condition-node/index.vue
https://github.com/1Panel-dev/MaxKB/issues/753
> fix: 修复判断器删除其中一个条件后，前端序号未更新的缺陷

- pyproject.toml
> feat: 升级django 4.2.14

- apps/application/flow/step_node/search_dataset_node/impl/base_search_dataset_node.py
> fix: 修复返回的分段结果排序不对，不是按照命中高低顺序排序[BUG] #746

- apps/dataset/serializers/document_serializers.py
> fix: 修复在线知识库爬取文档名超过128个字符报错 #706

- apps/users/serializers/user_serializers.py
- ui/src/views/user-manage/index.vue
> refactor: user

- ui/src/layout/components/top-bar/avatar/AboutDialog.vue
- ui/src/utils/time.ts
> feat: 增加license过期时间提示

- ui/src/views/login/index.vue
> refactor: 优化登录类型判断

- ui/src/components/ai-chat/index.vue
- ui/src/layout/components/app-header/index.vue
- ui/src/styles/app.scss
- ui/src/views/chat/base/index.vue
- ui/src/views/chat/embed/index.vue
- ui/src/views/chat/index.vue
- ui/src/views/chat/pc/index.vue
> feat: 对话可更换主题

- apps/common/util/split_model.py
1. 优化paragraph分割代码，代码逻辑更简洁
2. 修复最后一个title没有任何内容不显示
3. 修复第6级title无法分割
1. 优化split_model 里的文档分割逻辑
- [*] Made sure tests are passing and test coverage is added if needed.
- [*] Made sure commit message follow the rule of [Conventional Commits specification](https://www.conventionalcommits.org/).
> fix: 优化文档分割处理

- main.py
> feat: 添加main.py dev指令

- apps/common/management/commands/gunicorn.py
> fix: 修复无法流式输出

- ui/src/components/login-layout/index.vue
> fix: 修复登录页面无法显示图片

- apps/application/chat_pipeline/step/chat_step/i_chat_step.py
- apps/application/chat_pipeline/step/chat_step/impl/base_chat_step.py
- apps/application/flow/i_step_node.py
- apps/application/flow/step_node/ai_chat_step_node/i_chat_node.py
- apps/application/flow/step_node/ai_chat_step_node/impl/base_chat_node.py
- apps/application/flow/step_node/question_node/impl/base_question_node.py
- apps/application/flow/step_node/search_dataset_node/impl/base_search_dataset_node.py
- apps/application/serializers/application_serializers.py
- apps/application/serializers/chat_message_serializers.py
- apps/application/serializers/chat_serializers.py
- apps/setting/models/model_management.py
- apps/setting/models_provider/tools.py
> fix: 修复模型没权限使用时报错

- apps/setting/serializers/provider_serializers.py
- ui/src/api/type/model.ts
- ui/src/views/template/component/ModelCard.vue
> fix: 修复模型管理中,公共模型不能修改

- apps/users/serializers/user_serializers.py
> fix: 修复变量取值错误

- apps/application/serializers/application_serializers.py
> fix: 修复嵌入功能参数错误

- ui/src/views/template/component/ModelCard.vue
> fix: 修改模型权限判断

- ui/src/api/theme.ts
- ui/src/components/ai-chat/index.vue
- ui/src/components/index.ts
- ui/src/components/logo/SendIcon.vue
- ui/src/stores/modules/user.ts
- ui/src/views/application-workflow/index.vue
- ui/src/views/chat/index.vue
- ui/src/views/login/index.vue
- ui/src/views/template/component/CreateModelDialog.vue
- ui/src/views/template/component/EditModel.vue
> fix: 优化外观设置问题

- apps/users/serializers/user_serializers.py
> refactor: ldap_login

- apps/dataset/serializers/image_serializers.py
--bug=1044392 --user=王孝刚 【系统管理】外观设置，修改网站logo后再次修改报错 https://www.tapd.cn/57709429/s/1553208
> fix: 修复再次修改logo报错的缺陷

- ui/src/views/application-workflow/index.vue
- ui/src/views/application/ApplicationSetting.vue
- ui/src/views/chat/base/index.vue
- ui/src/views/chat/embed/index.vue
- ui/src/views/chat/pc/index.vue
> feat: 应用对话显示应用图标

- apps/setting/models/model_management.py
> fix: 修复应用无法保存

- apps/setting/serializers/provider_serializers.py
> fix: 模型修改时,删除模型缓存数据

- apps/application/serializers/application_serializers.py
> fix: 修复应用命中测试未关联知识库时,响应空数组

- apps/common/management/commands/gunicorn.py
- pyproject.toml
> fix: 修改启动方式

- apps/application/flow/i_step_node.py
- apps/application/serializers/application_serializers.py
- apps/application/serializers/chat_message_serializers.py
- apps/application/serializers/chat_serializers.py
- apps/application/views/application_views.py
- apps/common/constants/cache_code_constants.py
- apps/common/middleware/cross_domain_middleware.py
- apps/common/middleware/static_headers_middleware.py
- apps/common/util/cache_util.py
- apps/smartdoc/settings/base.py
- apps/smartdoc/urls.py
- main.py
> refactor: 重构部分代码

- apps/setting/serializers/provider_serializers.py
> fix: 修复【系统管理】创建模型，没有校验

- apps/application/serializers/application_serializers.py
> fix: 修复【应用】- 显示设置 恢复默认后，浮窗入口图标显示错误。

- apps/application/template/embed.js
> fix: 修复【浮窗】-拖拽机器人时应该跟随鼠标移动

- ui/src/views/template/component/ModelCard.vue
> fix: 修改模型取消下载提示

- ui/src/views/template/index.vue
> fix: 修复【系统管理】向量模型下载失败后，页面上的其他模型也会显示失败状态

- ui/src/views/application/ApplicationSetting.vue
- ui/src/views/dataset/component/BaseForm.vue
- ui/src/views/dataset/component/EditParagraphDialog.vue
- ui/src/views/dataset/component/ParagraphList.vue
- ui/src/views/paragraph/component/ProblemComponent.vue
- ui/src/workflow/nodes/ai-chat-node/index.vue
- ui/src/workflow/nodes/question-node/index.vue
> Pr@main@perf mode select

- ui/src/components/markdown/MdRenderer.vue
> fix: 修复特定情况下quick_question解析错误

- apps/dataset/serializers/common_serializers.py
> fix: 修复缓存模型key错误

- apps/common/management/commands/gunicorn.py
> feat: gunicorn启动使用gthread

- apps/common/management/commands/gunicorn.py
- apps/common/util/split_model.py
- apps/dataset/serializers/document_serializers.py
> fix: 修复上传文档，高级分段设置分段长度为10w字符，生成预览还是4096个字符一段

- apps/common/event/__init__.py
- apps/common/event/common.py
> fix: 修复向量化失败,缓存未被删除

- apps/application/serializers/application_serializers.py
> fix: 修复嵌入脚本

- apps/application/chat_pipeline/step/chat_step/i_chat_step.py
- apps/application/chat_pipeline/step/chat_step/impl/base_chat_step.py
> fix: 修复模型非必填报错

- apps/dataset/serializers/document_serializers.py
> fix: 修复WEB 知识库批量导入文档，中间有失败的，后面的文档都不会导入 #677

- apps/application/template/embed.js
> fix: 修复【应用】浮窗模式嵌入第三方，开启可拖动位置，手机上无法拖动

- apps/application/template/embed.js
> fix: 修复【应用】浮窗模式嵌入拖拽问题

- apps/common/chunk/impl/mark_chunk_handle.py
> feat: 段落分块设置最小分块字数

- ui/src/stores/modules/user.ts
> fix: 修复更新网站logo不生效的缺陷

- apps/application/flow/step_node/ai_chat_step_node/impl/base_chat_node.py
- apps/application/flow/step_node/question_node/impl/base_question_node.py
> fix: 修复节点输出,输出结果重复

- apps/common/event/listener_manage.py
> fix: 修复知识库问题管理修改问题报错

- apps/setting/models_provider/impl/ollama_model_provider/model/llm.py
- apps/setting/models_provider/impl/ollama_model_provider/ollama_model_provider.py
> fix: 修复ollama模型二级path无法添加问题 #805

- apps/dataset/serializers/image_serializers.py
> fix: 修复无法上传像素点很高的图片

- apps/common/handle/impl/qa/xls_parse_qa_handle.py
- apps/common/handle/impl/qa/xlsx_parse_qa_handle.py
> fix: 修复QA文件解析失败

- apps/application/flow/i_step_node.py
- apps/application/flow/step_node/ai_chat_step_node/impl/base_chat_node.py
- apps/application/flow/step_node/question_node/impl/base_question_node.py
> fix: 修复节点直接回答,不同节点信息用回车隔开

- ui/src/workflow/nodes/ai-chat-node/index.vue
- ui/src/workflow/nodes/base-node/index.vue
- ui/src/workflow/nodes/question-node/index.vue
- ui/src/workflow/nodes/reply-node/index.vue
> fix: 修复工作流提示词使用md格式输入框,输入框滚动问题

- apps/setting/serializers/provider_serializers.py
> fix: 模型管理,模型名称长度从20个字符调整到64个字符

- apps/dataset/serializers/document_serializers.py
> fix: 修复文档同步文档状态错误

- apps/application/serializers/chat_serializers.py
> fix: 修改调试页面多轮对话设置无效问题

- apps/common/util/split_model.py
> fix: 修复分段时,特殊情况会丢失数据 #938

- apps/dataset/serializers/dataset_serializers.py
> fix: 修复创建web知识库时,向量模型错误

- pyproject.toml
> fix: 升级django到 4.2.15

- .github/workflows/create-pr-from-push.yml
> ci: 增加自动生成PR的配置

- apps/setting/models_provider/impl/xinference_model_provider/xinference_model_provider.py
- apps/setting/models_provider/impl/zhipu_model_provider/model/llm.py
refactor: 优化Xorbits Inference名称显示
> refactor: 优化Xorbits Inference名称显示

- installer/Dockerfile
ci: 修改默认pip安装包路径，使用data目录并去掉volume
> ci: 修改默认pip安装包路径，使用data目录并去掉volume

- apps/application/flow/step_node/function_lib_node/impl/base_function_lib_node.py
- apps/application/flow/step_node/function_node/impl/base_function_node.py
> fix: 修复函数库节点为输出节点时类型错误

- ui/src/views/function-lib/component/FunctionFormDrawer.vue
- ui/src/views/function-lib/index.vue
> feat: 函数库增加复制功能

- installer/Dockerfile
> fix: 修复用户无法创建问题

- apps/setting/models_provider/impl/aws_bedrock_model_provider/aws_bedrock_model_provider.py
- apps/setting/models_provider/impl/aws_bedrock_model_provider/credential/llm.py
- apps/setting/models_provider/impl/aws_bedrock_model_provider/model/llm.py
- apps/setting/models_provider/impl/azure_model_provider/model/azure_chat_model.py
- apps/setting/models_provider/impl/ollama_model_provider/model/llm.py
- apps/setting/models_provider/impl/openai_model_provider/model/llm.py
- apps/setting/models_provider/impl/tencent_model_provider/credential/llm.py
- apps/setting/models_provider/impl/wenxin_model_provider/credential/llm.py
- apps/setting/models_provider/impl/wenxin_model_provider/model/llm.py
> refactor: aws

- apps/common/handle/impl/pdf_split_handle.py
> refactor: 使用lazy_load方式加载pdf

- apps/function_lib/serializers/function_lib_serializer.py
- apps/function_lib/views/function_lib_views.py
> feat: 函数库删除接口

- apps/common/handle/impl/pdf_split_handle.py
refactor: 逐页加载pdf, 图片类型单独保存成文件加载
> refactor: 逐页加载pdf, 图片类型单独保存成文件加载

- installer/Dockerfile
> chore: change env in dockerfile

- ui/src/locales/lang/en_US/views/application.ts
- ui/src/locales/lang/zh_CN/views/application.ts
- ui/src/views/application/component/CopyApplicationDialog.vue
- ui/src/views/application/index.vue
> feat: 增加复制应用功能(#768)

- apps/setting/models_provider/impl/base_chat_open_ai.py
fix: 修复Xinference 模型回答问题最后几个字会重复一次  --bug=1045125 --user=王孝刚 【模型管理】本地 Xinference 模型回答问题最后几个字会重复一次 https://www.tapd.cn/57709429/s/1565685
> fix: 修复Xinference 模型回答问题最后几个字会重复一次

- ui/src/views/application/component/CopyApplicationDialog.vue
- ui/src/views/function-lib/index.vue
> fix: 修复复制应用和函数库问题

- apps/common/management/commands/services/services/local_model.py
- apps/setting/models_provider/impl/local_model_provider/model/embedding.py
- apps/smartdoc/conf.py
- main.py
> fix: 解决local_model服务端口冲突问题

- ui/src/views/application/ApplicationSetting.vue
- ui/src/views/application/component/CreateApplicationDialog.vue
- ui/src/workflow/nodes/base-node/index.vue
> fix: 优化应用名称过滤带空格问题

- ui/src/views/application/component/CopyApplicationDialog.vue
- ui/src/views/function-lib/component/FunctionFormDrawer.vue
- ui/src/views/function-lib/index.vue
> perf: 优化函数复制功能

- apps/common/management/commands/celery.py
- apps/common/management/commands/services/command.py
- apps/common/management/commands/services/hands.py
- apps/common/management/commands/services/services/celery_base.py
- installer/Dockerfile
> fix: 修复无法启动问题

- apps/common/handle/impl/pdf_split_handle.py
> chore: 解析错误是输出错误原因

- apps/common/management/commands/celery.py
- apps/smartdoc/settings/logging.py
> fix: 修复dev 无法启动celery

- apps/common/util/function_code.py
- apps/dataset/models/data_set.py
- apps/function_lib/serializers/function_lib_serializer.py
fix: 修复函数库输入参数校验,搜索函数失败,编辑函数描述为空校验
> fix: 修复函数库输入参数校验,搜索函数失败,编辑函数描述为空校验

- apps/dataset/serializers/dataset_serializers.py
> fix: 修复创建web知识库错误

- apps/dataset/serializers/document_serializers.py
> fix: 修复上传文档时,向量化未发布异步任务

- apps/application/serializers/application_serializers.py
- apps/application/sql/list_application.sql
> fix: 修复复制 工作流数据未复制

- installer/run-maxkb.sh
> feat: 启动的时候,删除pid

- apps/setting/models_provider/impl/tencent_model_provider/credential/llm.py
> fix: 修复混元模型失败的缺陷

- apps/common/event/common.py
fix: 修复知识库手动添加分段报错的缺陷  --bug=1045628 --user=王孝刚 【知识库】手动添加分段报错 https://www.tapd.cn/57709429/s/1568695
> fix: 修复知识库手动添加分段报错的缺陷

- apps/application/serializers/application_serializers.py
- ui/src/workflow/nodes/ai-chat-node/index.vue
- ui/src/workflow/nodes/question-node/index.vue
> fix: 修复模型保存无法回显问题

- apps/application/serializers/chat_message_serializers.py
- apps/application/serializers/chat_serializers.py
- apps/smartdoc/settings/base.py
feat: 修复【应用】-设置的调试预览提问经常出现 会话不存在的情况
> feat: 修复【应用】-设置的调试预览提问经常出现 会话不存在的情况

- apps/application/chat_pipeline/step/chat_step/i_chat_step.py
- apps/application/serializers/chat_serializers.py
- ui/src/views/application/index.vue
> fix: 修复应用复制报错

- apps/application/flow/workflow_manage.py
> fix: 修复工作流模型不存在时报错

- apps/setting/models_provider/impl/vllm_model_provider/vllm_model_provider.py
> fix: 修复vLLM显示名称

- apps/setting/serializers/provider_serializers.py
- apps/setting/views/model.py
- ui/src/views/application/ApplicationSetting.vue
- ui/src/views/application/component/AIModeParamSettingDialog.vue
- ui/src/workflow/nodes/ai-chat-node/index.vue
- ui/src/workflow/nodes/question-node/index.vue
fix: 修复AI模型参数,切换模型时参数修改为当前模型的默认参数
> fix: 修复AI模型参数,切换模型时参数修改为当前模型的默认参数

- apps/application/flow/i_step_node.py
- apps/application/flow/step_node/function_lib_node/i_function_lib_node.py
- apps/application/flow/workflow_manage.py
- apps/function_lib/views/function_lib_views.py
- ui/src/api/function-lib.ts
- ui/src/views/application-workflow/index.vue
- ui/src/views/application/component/AIModeParamSettingDialog.vue
- ui/src/workflow/common/NodeContainer.vue
- ui/src/workflow/common/validate.ts
- ui/src/workflow/nodes/function-lib-node/index.vue
fix: 修复编排中引用函数，原函数更新后，编排中未同步更新
> fix: 修复编排中引用函数，原函数更新后，编排中未同步更新

- ui/src/views/application-workflow/index.vue
> fix: 修复工作流函数库id未赋值

- apps/application/flow/workflow_manage.py
> fix: 修复工作流无法发布

- apps/application/flow/i_step_node.py
- apps/application/flow/step_node/ai_chat_step_node/impl/base_chat_node.py
- apps/application/flow/step_node/question_node/impl/base_question_node.py
- apps/application/flow/workflow_manage.py
> fix: 修复ai对话节点输出内容回添加回车

- apps/common/init/init_doc.py
> fix: 修改swagger文档初始化

- ui/src/views/application/ApplicationSetting.vue
- ui/src/workflow/nodes/ai-chat-node/index.vue
- ui/src/workflow/nodes/question-node/index.vue
> fix: 修复应用设置页面清空 AI 模型报错

- ui/src/views/application/index.vue
> fix: 修复复制简易应用,AI 模型信息没有复制过去

- apps/common/handle/impl/doc_split_handle.py
- apps/common/handle/impl/html_split_handle.py
- apps/common/handle/impl/pdf_split_handle.py
- apps/common/handle/impl/text_split_handle.py
> fix: 修复上传文档中后缀为PDF 不识别

- apps/application/serializers/application_serializers.py
- apps/application/urls.py
- apps/application/views/application_views.py
- ui/src/api/application.ts
- ui/src/views/application/ApplicationSetting.vue
- ui/src/views/application/component/AIModeParamSettingDialog.vue
- ui/src/workflow/nodes/ai-chat-node/index.vue
- ui/src/workflow/nodes/question-node/index.vue
> fix: 修复应用授权给其他用户，其他用户编辑无法编辑模型

- apps/application/serializers/application_serializers.py
> fix: 修复应用复制,模型参数未复制

- apps/application/flow/step_node/function_lib_node/impl/base_function_lib_node.py
- apps/application/flow/step_node/function_node/impl/base_function_node.py
> fix: 修复工作流函数节点输入参数类型未校验

- apps/application/flow/step_node/function_lib_node/impl/base_function_lib_node.py
- apps/application/flow/step_node/function_node/impl/base_function_node.py
> fix: 修复工作流函数节点输入参数类型未校验错误

- apps/common/event/listener_manage.py
- apps/dataset/serializers/document_serializers.py
- apps/embedding/task/embedding.py
> fix: 修复新增段落迁移文档未索引

- ui/src/components/dynamics-form/index.vue
> fix: 修复工作流参数设置无效

- installer/start-maxkb.sh
> feat: 添加maxkb启动命令

- ui/src/workflow/common/NodeCascader.vue
- ui/src/workflow/nodes/ai-chat-node/index.vue
- ui/src/workflow/nodes/base-node/index.vue
- ui/src/workflow/nodes/condition-node/index.vue
- ui/src/workflow/nodes/function-lib-node/index.vue
- ui/src/workflow/nodes/function-node/index.vue
- ui/src/workflow/nodes/question-node/index.vue
- ui/src/workflow/nodes/reply-node/index.vue
- ui/src/workflow/nodes/search-dataset-node/index.vue
> fix: 修复画布事件冲突问题

- ui/src/workflow/nodes/function-node/index.vue
> fix: 修复工作流函数节点滚动事件导致整个页面变大

- apps/dataset/views/document.py
> feat: 分段接口添加认证

- apps/setting/models_provider/impl/ollama_model_provider/model/llm.py
- apps/setting/models_provider/impl/openai_model_provider/model/llm.py
> fix: 修复模型计算tokens消耗报错的缺陷

- apps/application/serializers/application_serializers.py
- apps/setting/models_provider/impl/openai_model_provider/model/llm.py
fix: 修复openai供应商计算tokens错误,修复旧版本应用编辑页面直接报错提示问题为必填参数错误
> fix: 修复openai供应商计算tokens错误,修复旧版本应用编辑页面直接报错提示问题为必填参数错误

- apps/setting/models_provider/impl/openai_model_provider/model/llm.py
> fix: 修复openai计算token错误

- apps/dataset/serializers/document_serializers.py
- apps/dataset/urls.py
- apps/dataset/views/document.py
- ui/src/enums/document.ts
--story=1016081 --user=王孝刚 【知识库】- 文档列表支持按文档状态、启用状态、命中处理方式进行筛选 https://www.tapd.cn/57709429/s/1571832
> feat: 知识库列表增加筛选

- ui/src/views/function-lib/component/FunctionDebugDrawer.vue
- ui/src/views/theme/index.vue
> feat: 外观设置增加自定义颜色

- ui/src/layout/components/top-bar/index.vue
- ui/src/stores/modules/user.ts
- ui/src/utils/theme.ts
- ui/src/views/theme/index.vue
> feat: 增加导航拦设置功能

- apps/setting/models_provider/impl/volcanic_engine_model_provider/credential/tts.py
- apps/setting/models_provider/impl/volcanic_engine_model_provider/volcanic_engine_model_provider.py
- apps/setting/models_provider/impl/xf_model_provider/credential/stt.py
- apps/setting/models_provider/impl/xf_model_provider/credential/tts.py
- apps/setting/models_provider/impl/xf_model_provider/xf_model_provider.py
> refactor: 自动填充api_url

- apps/application/serializers/application_serializers.py
- apps/application/serializers/chat_message_serializers.py
> fix: 修复对话中一定时间历史会话被清空 #1089

- apps/application/serializers/application_serializers.py
chore: fix nodes not in workflow
> chore: fix nodes not in workflow

- apps/application/serializers/application_serializers.py
- apps/application/views/application_views.py
- ui/src/components/ai-chat/index.vue
> refactor: 查询profile时返回stt配置

- ui/src/views/application-workflow/index.vue
- ui/src/workflow/nodes/base-node/index.vue
> fix: 修复高级模式下的stt调试

- apps/application/chat_pipeline/pipeline_manage.py
- apps/application/chat_pipeline/step/chat_step/impl/base_chat_step.py
- apps/application/flow/workflow_manage.py
- apps/application/serializers/chat_message_serializers.py
- apps/application/swagger_api/chat_api.py
- apps/application/urls.py
- apps/application/views/chat_views.py
- apps/common/auth/authenticate.py
- apps/common/exception/app_exception.py
- apps/common/handle/base_to_response.py
- apps/common/handle/impl/response/openai_to_response.py
- apps/common/handle/impl/response/system_to_response.py
- apps/setting/models_provider/impl/local_model_provider/model/reranker.py
- apps/setting/models_provider/impl/openai_model_provider/model/llm.py
> feat: 支持openai接口

- apps/setting/models_provider/impl/xinference_model_provider/credential/reranker.py
- apps/setting/models_provider/impl/xinference_model_provider/model/reranker.py
- apps/setting/models_provider/impl/xinference_model_provider/xinference_model_provider.py
> feat: 支持xinference Rerank模型

- apps/application/flow/step_node/start_node/impl/base_start_node.py
- ui/src/components/ai-chat/ExecutionDetailDialog.vue
> refactor: 执行详情显示全局变量

- apps/common/handle/base_parse_qa_handle.py
- apps/common/handle/impl/qa/csv_parse_qa_handle.py
- apps/common/handle/impl/qa/xls_parse_qa_handle.py
- apps/common/handle/impl/qa/xlsx_parse_qa_handle.py
- apps/dataset/serializers/document_serializers.py
> feat: 上传文档qa问答对支持xlsx文件单元格图片

- apps/application/views/application_views.py
- apps/setting/models_provider/impl/local_model_provider/credential/tts.py
- apps/setting/models_provider/impl/local_model_provider/local_model_provider.py
- apps/setting/models_provider/impl/local_model_provider/model/tts.py
- ui/src/components/ai-chat/index.vue
- ui/src/views/application-workflow/index.vue
- ui/src/views/application/ApplicationSetting.vue
- ui/src/views/chat/pc/index.vue
> refactor: 支持使用浏览器语音播放

- apps/common/handle/base_parse_table_handle.py
- apps/common/handle/impl/qa/xlsx_parse_qa_handle.py
- apps/common/handle/impl/table/csv_parse_table_handle.py
- apps/common/handle/impl/table/excel_parse_table_handle.py
- apps/common/handle/impl/tools.py
- apps/dataset/serializers/document_serializers.py
> feat: 上传文档表格对支持xlsx文件单元格图片

- apps/common/handle/impl/table/xls_parse_table_handle.py
- apps/common/handle/impl/table/xlsx_parse_table_handle.py
- apps/dataset/serializers/document_serializers.py
> fix: 表格数据区分xls和xlsx

- ui/src/components/ai-chat/index.vue
> fix: 修复前端没有input_field_list报错

- apps/application/flow/step_node/start_node/impl/base_start_node.py
> chore: fix typo.

- apps/application/flow/step_node/search_dataset_node/impl/base_search_dataset_node.py
- apps/common/constants/authentication_type.py
> fix: 修复工作流中,函数库使用知识库检索参数错误

- apps/application/flow/step_node/reranker_node/impl/base_reranker_node.py
> fix: 修复重排模型添加检索内容字段

- ui/src/views/application/component/AccessSettingDrawer.vue
> refactor: 优化页面

- ui/src/components/markdown/MdRenderer.vue
feat: 支持通过html_rander标签 对里面的html内容进行渲染
> feat: 支持通过html_rander标签 对里面的html内容进行渲染

- ui/src/components/ai-chat/index.vue
- ui/src/workflow/nodes/base-node/index.vue
> fix: 修复编写错误的字段名

- apps/application/serializers/application_serializers.py
- apps/application/template/embed.js
- apps/application/views/application_views.py
- ui/src/components/ai-chat/index.vue
chore: 修改参数提示<br>refactor: 接入时增加query参数
> refactor: 接入时增加query参数

- ui/src/components/ai-chat/index.vue
- ui/src/views/application-workflow/index.vue
- ui/src/views/chat/pc/index.vue
refactor: 调试时展示所有的参数，嵌入后仅展示用户输入，接口输入需要写在url上
> refactor: 调试时展示所有的参数，嵌入后仅展示用户输入，接口输入需要写在url上

- ui/src/workflow/nodes/base-node/index.vue
- ui/src/workflow/nodes/start-node/index.vue
> fix: 及时更新流程图里的变量

- ui/src/components/ai-chat/index.vue
> refactor: 调整采样率

- apps/setting/models_provider/impl/openai_model_provider/model/llm.py
- apps/users/serializers/user_serializers.py
refactor: 优化用户名校验逻辑  --story=1016296 --user=王孝刚 【系统管理】用户创建限制太过于严格，与某些用户/企业的习惯或要求不符合 https://www.tapd.cn/57709429/s/1579177
> refactor: 优化用户名校验逻辑

- apps/common/handle/impl/table/xls_parse_table_handle.py
- apps/common/handle/impl/table/xlsx_parse_table_handle.py
> refactor: 处理纵向合并的单元格

- apps/application/flow/step_node/start_node/i_start_node.py
- apps/application/flow/step_node/start_node/impl/base_start_node.py
- ui/src/workflow/nodes/start-node/index.vue
feat: 工作流开始节点添加上下文,会话id参数 #1094
> feat: 工作流开始节点添加上下文,会话id参数 #1094

- ui/src/components/ai-chat/OperationButton.vue
- ui/src/components/ai-chat/index.vue
refactor: 播放语音增加tts_type区分不同类型
> refactor: 播放语音增加tts_type区分不同类型

- ui/src/components/ai-chat/index.vue
fix: 修复历史数据没有展示变量值的问题  --bug=1046515 --user=刘瑞斌 【应用】查看历史对话，默认没有带变量值，点击重新生成答案会报错 https://www.tapd.cn/57709429/s/1579777
> fix: 修复历史数据没有展示变量值的问题

- ui/src/components/ai-chat/index.vue
> refactor: 增加弹框提示

- apps/setting/models_provider/impl/base_chat_open_ai.py
- apps/setting/models_provider/impl/qwen_model_provider/model/llm.py
> fix: 解决非流式返回报错的缺陷

- ui/src/workflow/nodes/reranker-node/ParamSettingDialog.vue
- ui/src/workflow/nodes/reranker-node/index.vue
> fix: 修复多路召回前端校验错误

- ui/src/views/application-overview/index.vue
- ui/src/workflow/nodes/reranker-node/index.vue
> perf: 【应用】概览访问凭证优化

- apps/application/serializers/application_serializers.py
- apps/application/serializers/chat_serializers.py
- ui/src/api/application-xpack.ts
- ui/src/stores/modules/application.ts
> feat: 增加应用profile 设置参数

- ui/src/components/ai-chat/OperationButton.vue
- ui/src/components/ai-chat/index.vue
> refactor: 语音播放时将内容处理成纯文本

- ui/src/components/ai-chat/OperationButton.vue
fix: 修复TTS播放语音不能暂停的问题  --bug=1046734 --user=刘瑞斌 【应用】选择语音输出模型，无法暂停播放 https://www.tapd.cn/57709429/s/1581642
> fix: 修复TTS播放语音不能暂停的问题

- apps/common/event/__init__.py
> fix: 修复项目重启后,文档状态错误

- apps/setting/models_provider/impl/openai_model_provider/model/stt.py
fix: 处理opanai语音识别报错的问题  --bug=1046791 --user=刘瑞斌 【应用】使用 openai 语音输入模型、输出模型进行输入输出报错 https://www.tapd.cn/57709429/s/1582133
> fix: 处理opanai语音识别报错的问题

- apps/setting/models_provider/impl/volcanic_engine_model_provider/credential/stt.py
- apps/setting/models_provider/impl/volcanic_engine_model_provider/credential/tts.py
> chore: 豆包模型配置label修改

- apps/setting/models_provider/impl/volcanic_engine_model_provider/model/stt.py
> fix: 修复豆包模型配置校验失败的问题

- apps/setting/models_provider/impl/tencent_model_provider/model/hunyuan.py
> fix: 修复混元大模型使用system角色报错

- apps/common/handle/impl/qa/csv_parse_qa_handle.py
- apps/common/handle/impl/qa/xls_parse_qa_handle.py
- apps/common/handle/impl/qa/xlsx_parse_qa_handle.py
> fix: 修复知识库导出后再导入，有一部分内容会丢失

- apps/dataset/serializers/problem_serializers.py
> fix: 修复创建问题，输入超长字符报错

- apps/application/serializers/application_serializers.py
> fix: 修复简易模型无法显示浮窗

- ui/src/components/ai-chat/LogOperationButton.vue
- ui/src/components/ai-chat/index.vue
fix: 修复对话日志里的语音不能播放的问题  --bug=1046835 --user=刘瑞斌 【应用】应用对话日志中，点击播放按钮没有反应 https://www.tapd.cn/57709429/s/1582747
> fix: 修复对话日志里的语音不能播放的问题

- apps/common/handle/impl/response/openai_to_response.py
fix: 修复【模型设置】使用应用baseurl创建模型报错
> fix: 修复【模型设置】使用应用baseurl创建模型报错

- apps/application/flow/step_node/function_lib_node/impl/base_function_lib_node.py
fix: 修复【应用编排】应用编排中引用函数，函数被禁用后应用里还可以正常执行
> fix: 修复【应用编排】应用编排中引用函数，函数被禁用后应用里还可以正常执行

- apps/setting/models_provider/impl/local_model_provider/model/embedding.py
- apps/setting/models_provider/impl/local_model_provider/model/reranker.py
> fix: 修复本地模型加载失败时,错误信息未输出

- apps/common/handle/impl/doc_split_handle.py
fix: 修复【知识库】语雀导出的word，导入知识库是空白的 #1148
> fix: 修复【知识库】语雀导出的word，导入知识库是空白的 #1148

- ui/src/views/application-overview/component/EmbedDialog.vue
- ui/src/views/application-overview/index.vue
- ui/src/workflow/nodes/base-node/component/FieldFormDialog.vue
> refactor: 全局变量增加默认值

- apps/application/flow/step_node/reranker_node/impl/base_reranker_node.py
> fix: reranker添加检索内容数据

- ui/src/workflow/nodes/base-node/index.vue
fix: 修复没有选择语音模型，点发布不能拦截的问题  --bug=1046729 --user=刘瑞斌 【应用】应用语音播放选择模型播放后，不选择具体的模型，点击播放按钮没有反应 https://www.tapd.cn/57709429/s/1583384
> fix: 修复没有选择语音模型，点发布不能拦截的问题

- ui/src/enums/model.ts
- ui/src/views/template/component/CreateModelDialog.vue
- ui/src/views/template/component/EditModel.vue
> chore: 优化提示

- ui/src/views/application-workflow/index.vue
- ui/src/workflow/common/validate.ts
- ui/src/workflow/nodes/function-lib-node/index.vue
fix: 修复函数禁用后,在工作流中应该节点状态应该改为不可用
> fix: 修复函数禁用后,在工作流中应该节点状态应该改为不可用

- apps/application/flow/workflow_manage.py
fix: 修复使用应用编排的baseurl创建openai模型报错
> fix: 修复使用应用编排的baseurl创建openai模型报错

- ui/src/components/dynamics-form/FormItem.vue
fix: 【模型管理】新建或编辑模型时，API key为空时提示问题
> fix: 【模型管理】新建或编辑模型时，API key为空时提示问题

- apps/application/flow/step_node/start_node/impl/base_start_node.py
- apps/application/flow/workflow_manage.py
- ui/src/workflow/nodes/reranker-node/index.vue
> feat: 工作流处理默认参数

- apps/embedding/task/embedding.py
fix: 修复向量模型服务未起，重新向量问答一直显示排队中。
> fix: 修复向量模型服务未起，重新向量问答一直显示排队中。

- apps/application/serializers/application_serializers.py
> fix: 修复简单应用，修改问题优化提示词没生效

- apps/application/template/embed.js
fix: 【应用】-浮窗框模式，拖拽浮窗入口图标， 图标会变大
> fix: 【应用】-浮窗框模式，拖拽浮窗入口图标， 图标会变大

- apps/setting/models_provider/impl/xinference_model_provider/xinference_model_provider.py
> fix: 去掉不主流的模型

- ui/src/views/application-overview/component/EmbedDialog.vue
- ui/src/views/application-overview/index.vue
fix: 公开链接显示接口输入类型的变量  --bug=1047029 --user=刘瑞斌 【应用编排】- 公开访问连接中未自动生成 接口传参的变量 https://www.tapd.cn/57709429/s/1584536
> fix: 公开链接显示接口输入类型的变量

- ui/src/views/team/index.vue
> fix: 【团队成员】左侧内容超出问题优化(#1199)

- ui/src/components/ai-chat/LogOperationButton.vue
- ui/src/components/ai-chat/OperationButton.vue
> refactor: 浏览器播放的语音支持暂停和继续播放

- apps/application/flow/workflow_manage.py
fix: 修复高级编排没有记录对话日志的缺陷  --bug=1046962 --user=王孝刚 【应用】接入第三方应用后，在第三方应用里的对话信息没有存到对话记录里 https://www.tapd.cn/57709429/s/1585116
> fix: 修复高级编排没有记录对话日志的缺陷

- apps/setting/models_provider/impl/volcanic_engine_model_provider/model/tts.py
> fix: 豆包模型按行发送接收，合并mp3后返回前端

- apps/common/handle/impl/pdf_split_handle.py
> fix: 处理文本前后的空白字符

- apps/application/chat_pipeline/step/reset_problem_step/i_reset_problem_step.py
- apps/application/chat_pipeline/step/reset_problem_step/impl/base_reset_problem_step.py
> fix: 修复建议应用问题优化无效

- apps/application/flow/default_workflow.json
> style: 【应用编排】-优化基本信息节点宽度

- apps/application/serializers/chat_message_serializers.py
- apps/application/views/chat_views.py
fix: 修复【API 接口】应用对话接口 stream false ,提问报错
> fix: 修复【API 接口】应用对话接口 stream false ,提问报错

- apps/dataset/serializers/problem_serializers.py
> fix: 修复创建问题长度为256

- ui/src/components/markdown/EchartsRander.vue
> fix: 修复无法无法使用echarts实例

- apps/application/flow/default_workflow.json
- ui/src/workflow/common/app-node.ts
- ui/src/workflow/nodes/base-node/index.ts
> fix: 工作流基础节点宽度加宽

- apps/common/util/function_code.py
- installer/Dockerfile
build: sandbox权限限制，/opt/maxkb/app 目录下的文件只能读取自己的 /opt/maxkb/app/sandbox
> build: sandbox权限限制，/opt/maxkb/app 目录下的文件只能读取自己的 /opt/maxkb/app/sandbox

- apps/application/serializers/application_serializers.py
> fix: 修复旧数据,嵌入脚本报错

- ui/src/workflow/common/NodeContainer.vue
> fix: 添加组件函数库滚动条无法滚动

- ui/src/views/application-workflow/index.vue
fix: 修复工作流调试页面选择下拉框参数,调试框被关掉错误
> fix: 修复工作流调试页面选择下拉框参数,调试框被关掉错误

- ui/src/views/application/ApplicationSetting.vue
- ui/src/views/application/index.vue
- ui/src/views/dataset/index.vue
- ui/src/views/user-manage/index.vue
fix: 修复弹出提示框文字颜色问题<br>fix: 修复关联知识库名称显示不全问题(#1210)
> fix: 修复关联知识库名称显示不全问题(#1210)

- pyproject.toml
fix: 修复aws 在使用anthropic供应商模型时报错
> fix: 修复aws 在使用anthropic供应商模型时报错

- apps/function_lib/serializers/py_lint_serializer.py
- apps/function_lib/swagger_api/py_lint_api.py
- apps/function_lib/urls.py
- apps/function_lib/views/__init__.py
- apps/function_lib/views/py_lint.py
- pyproject.toml
- ui/package.json
- ui/src/api/function-lib.ts
- ui/src/components/codemirror-editor/index.vue
- ui/src/styles/app.scss
- ui/src/styles/variables.scss
- ui/src/views/function-lib/component/FunctionFormDrawer.vue
- ui/src/workflow/nodes/function-node/index.vue
> feat: 支持函数库脚本代码校验

- ui/src/components/codemirror-editor/index.vue
> fix: 修复打包失败

- ui/src/components/codemirror-editor/index.vue
- ui/src/views/function-lib/component/FunctionDebugDrawer.vue
> fix: 修复代码调试 调试状态错误

- ui/src/views/application-overview/index.vue
- ui/src/views/team/component/PermissionSetting.vue
fix: 修改BaseUrl非点击<br>feat: 【团队管理】权限增加全选功能
> feat: 【团队管理】权限增加全选功能

- .gitignore
> 修复后端models文件夹被ignore

- apps/setting/models_provider/impl/xinference_model_provider/credential/stt.py
- apps/setting/models_provider/impl/xinference_model_provider/model/stt.py
- apps/setting/models_provider/impl/xinference_model_provider/model/tts.py
- apps/setting/models_provider/impl/xinference_model_provider/xinference_model_provider.py
> feat: 增加xinference语音模型

- ui/src/views/template/index.vue
> refactor: 优化左侧显示模型

- apps/application/flow/i_step_node.py
- apps/application/flow/step_node/ai_chat_step_node/impl/base_chat_node.py
- apps/application/flow/step_node/function_lib_node/impl/base_function_lib_node.py
- apps/application/flow/workflow_manage.py
- ui/src/workflow/common/app-node.ts
- ui/src/workflow/common/validate.ts
> feat: 工作流编排支持并行 #1154

- apps/common/forms/switch_field.py
- ui/src/components/dynamics-form/DemoConstructor.vue
- ui/src/components/dynamics-form/constructor/index.vue
- ui/src/components/dynamics-form/constructor/items/SliderConstructor.vue
- ui/src/components/dynamics-form/constructor/items/SwitchInputConstructor.vue
- ui/src/components/dynamics-form/constructor/items/TextInputConstructor.vue
- ui/src/components/dynamics-form/items/switch/SwitchInput.vue
> feat: 新增动态表单收集器

- ui/src/components/card-box/index.vue
- ui/src/components/dynamics-form/constructor/index.vue
- ui/src/components/dynamics-form/constructor/items/SingleSelectConstructor.vue
- ui/src/components/dynamics-form/constructor/items/SliderConstructor.vue
- ui/src/components/dynamics-form/constructor/items/SwitchInputConstructor.vue
- ui/src/components/dynamics-form/constructor/items/TextInputConstructor.vue
- ui/src/views/template/component/AddParamDrawer.vue
- ui/src/views/template/component/ModelCard.vue
- ui/src/views/template/component/ParamSettingDialog.vue
> refactor: 模型设置支持配置参数

- apps/application/serializers/chat_serializers.py
- apps/dataset/serializers/document_serializers.py
> fix: 修复excel导出内容有特殊字符出错

- ui/src/views/application-workflow/component/DropdownMenu.vue
> feat: 应用编排-添加组件支持搜索

- apps/application/serializers/chat_serializers.py
- apps/application/views/chat_views.py
- ui/src/api/log.ts
- ui/src/request/index.ts
- ui/src/views/log/index.vue
> feat: 对话日志支持自定义时间

- apps/setting/views/model.py
- ui/src/api/model.ts
- ui/src/views/template/component/SelectProviderDialog.vue
> refactor: 选择模型时支持按照模型类型筛选

- apps/common/handle/impl/doc_split_handle.py
解决issue提出的问题 ： #1380 
我在解决问题中注意到，<w:pict>中的图片在解析过程中，image对象使用type函数返回类型与<pic:pic>中的图片的type不一致。目前已在1.6.1版本上测试过。还请再仔细测试下后merge
```python
def image_to_mode(image, doc: Document, images_list, get_image_id, is_new_docx=True):
if is_new_docx:
image_ids = image.xpath('.//a:blip/@r:embed')
else:
image_ids = image.xpath('.//v:imagedata/@r:id', namespaces=combine_nsmap)
for img_id in image_ids:  # 获取图片id
part = doc.part.related_parts[img_id]  # 根据图片id获取对应的图片
if isinstance(part, ImagePart):
image_uuid = get_image_id(img_id)
if len([i for i in images_list if i.id == image_uuid]) == 0:
image = Image(id=image_uuid, image=part.blob, image_name=part.filename)
images_list.append(image)
return f'![](/api/image/{image_uuid})'
```
> fix: 修复知识库上传旧版本docx文件后，图片未正常识别导入的问题

- ui/src/views/application/ApplicationSetting.vue
- ui/src/workflow/nodes/base-node/index.vue
> style: 浏览器播放的语音不展示设置

- apps/setting/models_provider/impl/xinference_model_provider/xinference_model_provider.py
fix: 修复xinference模型创建失败的缺陷  https://github.com/1Panel-dev/MaxKB/issues/1389
> fix: 修复xinference模型创建失败的缺陷

- apps/setting/models_provider/impl/xf_model_provider/credential/embedding.py
- apps/setting/models_provider/impl/xf_model_provider/model/embedding.py
- apps/setting/models_provider/impl/xf_model_provider/xf_model_provider.py
> feat: 支持讯飞向量模型

- apps/setting/models_provider/impl/aliyun_bai_lian_model_provider/credential/embedding.py
- apps/setting/models_provider/impl/aliyun_bai_lian_model_provider/credential/reranker.py
- apps/setting/models_provider/impl/xf_model_provider/credential/embedding.py
> fix: 修复模型key未进行加密

- apps/setting/models_provider/impl/base_chat_open_ai.py
> fix: 修复vllm模型不能正常生成问题的bug

- apps/setting/models_provider/impl/tencent_model_provider/credential/embedding.py
- apps/setting/models_provider/impl/tencent_model_provider/model/embedding.py
- apps/setting/models_provider/impl/tencent_model_provider/tencent_model_provider.py
> feat: 支持腾讯混元向量模型

- apps/function_lib/serializers/py_lint_serializer.py
> fix: 修复应用编排添加自定义函数后报错

- apps/application/flow/step_node/function_node/impl/base_function_node.py
- apps/application/flow/step_node/question_node/impl/base_question_node.py
> fix: 修复应用编排调试应用，问题优化节点报错

- ui/src/views/application/ApplicationSetting.vue
- ui/src/workflow/nodes/base-node/index.vue
style: 修复el-form-item label样式没生效的问题
> style: 修复el-form-item label样式没生效的问题

- apps/common/handle/impl/pdf_split_handle.py
- ui/src/views/application-overview/component/LimitDialog.vue
> style: 优化样式

- apps/application/serializers/application_serializers.py
- apps/common/util/common.py
- apps/setting/serializers/valid_serializers.py
- apps/users/serializers/user_serializers.py
> refactor: 重构校验

- ui/src/components/dynamics-form/constructor/index.vue
- ui/src/components/dynamics-form/constructor/items/DatePickerConstructor.vue
- ui/src/components/dynamics-form/constructor/items/SliderConstructor.vue
- ui/src/components/dynamics-form/constructor/items/TextInputConstructor.vue
> feat: 动态表单收集添加日期格式

- ui/src/components/ai-chat/index.vue
- ui/src/components/dynamics-form/constructor/items/SingleSelectConstructor.vue
- ui/src/workflow/nodes/base-node/component/ApiInputFieldTable.vue
- ui/src/workflow/nodes/base-node/component/UserFieldFormDialog.vue
- ui/src/workflow/nodes/base-node/component/UserInputFieldTable.vue
- ui/src/workflow/nodes/start-node/index.vue
> refactor: 高级应用区分用户输入和接口传入的参数

- ui/src/components/dynamics-form/constructor/index.vue
- ui/src/components/dynamics-form/constructor/items/DatePickerConstructor.vue
> fix: 修复动态表单时间选择集无法回显

- ui/src/components/dynamics-form/constructor/index.vue
- ui/src/components/dynamics-form/constructor/items/DatePickerConstructor.vue
- ui/src/components/dynamics-form/constructor/items/SingleSelectConstructor.vue
- ui/src/components/dynamics-form/constructor/items/SliderConstructor.vue
- ui/src/components/dynamics-form/constructor/items/SwitchInputConstructor.vue
- ui/src/components/dynamics-form/constructor/items/TextInputConstructor.vue
> refactor: 重构动态表单收集框回显逻辑

- apps/common/cache/file_cache.py
> fix: 修复文件缓存timeout错误

- apps/application/flow/workflow_manage.py
> fix: 修复工作流节点错误无法在详情里面显示

- apps/application/flow/workflow_manage.py
> fix: 修复多路连接,日志显示不全

- apps/application/serializers/application_serializers.py
- apps/application/views/application_views.py
- apps/common/auth/handle/impl/public_access_token.py
- apps/common/util/common.py
- ui/src/api/application.ts
- ui/src/components/ai-chat/index.vue
- ui/src/request/index.ts
- ui/src/stores/modules/application.ts
- ui/src/views/chat/auth/component/password.vue
- ui/src/views/chat/auth/index.vue
- ui/src/views/chat/base/index.vue
- ui/src/views/chat/embed/index.vue
- ui/src/views/chat/index.vue
- ui/src/views/chat/pc/index.vue
> refactor: 对话框秘钥校验

- apps/common/auth/authenticate.py
- apps/common/auth/handle/impl/public_access_token.py
> fix: 修复对话框秘钥校验无法弹出

- apps/application/serializers/application_serializers.py
> fix: 修复对话校验错误

- apps/setting/models_provider/impl/tencent_model_provider/model/embedding.py
> fix: 修复腾讯云向量化失败

- ui/src/components/dynamics-form/constructor/index.vue
- ui/src/workflow/nodes/base-node/component/UserFieldFormDialog.vue
- ui/src/workflow/nodes/base-node/index.vue
> fix: 修复工作流接口传参历史数据兼容

- ui/src/components/dynamics-form/constructor/items/SingleSelectConstructor.vue
- ui/src/components/dynamics-form/constructor/items/TextInputConstructor.vue
- ui/src/workflow/nodes/base-node/component/UserFieldFormDialog.vue
fix: 添加参数时默认选中文本框  --bug=1047782 --user=刘瑞斌 【应用编排】-用户输入-添加参数时组件类型选择下拉选项，默认显示一个选项值 https://www.tapd.cn/57709429/s/1596098
> fix: 添加参数时默认选中文本框

- ui/src/views/chat/index.vue
> fix: 修复演示页面加载出错

- apps/application/serializers/application_serializers.py
fix: 修复应用开启公开访问链失败的缺陷  --bug=1047920 --user=王孝刚 【应用】应用概览页面-关闭/开启公开访问链接 提示异常 https://www.tapd.cn/57709429/s/1596807
> fix: 修复应用开启公开访问链失败的缺陷

- apps/common/util/field_message.py
- ui/src/views/application-overview/component/XPackDisplaySettingDialog.vue
> fix: 修复参数设置页面,回显问题

- apps/application/serializers/application_serializers.py
- apps/application/template/embed.js
> feat: 嵌入图标位置设置

- apps/setting/models_provider/impl/xinference_model_provider/xinference_model_provider.py
refactor: xinference 支持手动输入语音模型
> refactor: xinference 支持手动输入语音模型

- ui/src/components/dynamics-form/Demo.vue
- ui/src/components/dynamics-form/FormItem.vue
- ui/src/components/dynamics-form/constructor/index.vue
- ui/src/components/dynamics-form/constructor/items/JsonInputConstructor.vue
- ui/src/components/dynamics-form/items/JsonInput.vue
> fix: 添加JSON文本框

- apps/application/serializers/application_serializers.py
- apps/setting/models_provider/impl/aliyun_bai_lian_model_provider/model/tts.py
- apps/setting/models_provider/impl/openai_model_provider/model/tts.py
- apps/setting/models_provider/impl/volcanic_engine_model_provider/model/tts.py
- apps/setting/models_provider/impl/xf_model_provider/model/tts.py
- apps/setting/models_provider/impl/xinference_model_provider/model/tts.py
- ui/src/views/application/ApplicationSetting.vue
- ui/src/views/application/component/TTSModeParamSettingDialog.vue
- ui/src/workflow/nodes/base-node/index.vue
> fix: 修复语音模型传入不正确参数报错的问题

- ui/src/views/chat/auth/component/password.vue
fix: 修复密钥弹窗回车会重新开一个页面的缺陷  --bug=1048069 --user=王孝刚 【应用编排】-浮窗模式输入验证密码后 回车，会多打开一个页面 https://www.tapd.cn/57709429/s/1597919
> fix: 修复密钥弹窗回车会重新开一个页面的缺陷

- ui/src/views/authentication/component/EditModal.vue
> fix: 修复前端校验

- ui/src/components/dynamics-form/DemoConstructor.vue
- ui/src/components/dynamics-form/FormItem.vue
- ui/src/components/dynamics-form/constructor/items/JsonInputConstructor.vue
- ui/src/components/dynamics-form/items/JsonInput.vue
> fix: 修复json文本框未转换为对象问题

- apps/application/serializers/chat_serializers.py
refactor: 优化导出日志的时间格式  --bug=1048109 --user=王孝刚 【应用】对话日志导出后，提问时间格式显示问题 https://www.tapd.cn/57709429/s/1598300
> refactor: 优化导出日志的时间格式

- ui/src/components/dynamics-form/index.vue
> fix: 修复动态表单开关组件默认值初始化错误

- ui/src/views/authentication/component/EditModal.vue
- ui/src/views/login/components/wecomQrCode.vue
> refactor: 优化样式

- apps/dataset/serializers/dataset_serializers.py
- apps/dataset/task/sync.py
- apps/dataset/task/tools.py
> fix: 修复知识库替换同步未对本地知识库进行覆盖

- ui/src/views/template/component/CreateModelDialog.vue
- ui/src/views/template/component/EditModel.vue
> fix: 修复切换模型类型，基础模型没清空。

- apps/setting/models_provider/impl/volcanic_engine_model_provider/model/tts.py
> fix: 修复豆包语音合成不能处理全字符文本的问题

- ui/src/components/dynamics-form/constructor/data.ts
- ui/src/components/dynamics-form/constructor/index.vue
- ui/src/components/dynamics-form/constructor/items/DatePickerConstructor.vue
- ui/src/components/dynamics-form/constructor/items/JsonInputConstructor.vue
- ui/src/components/dynamics-form/constructor/items/SingleSelectConstructor.vue
- ui/src/components/dynamics-form/constructor/items/SliderConstructor.vue
- ui/src/components/dynamics-form/constructor/items/SwitchInputConstructor.vue
- ui/src/components/dynamics-form/constructor/items/TextInputConstructor.vue
- ui/src/views/template/component/AddParamDrawer.vue
- ui/src/views/template/component/ParamSettingDialog.vue
> fix: 修复表单构造器相关bug

- apps/application/serializers/chat_message_serializers.py
fix: 修复首次对话message大于1024报错 #1467
> fix: 修复首次对话message大于1024报错 #1467

- ui/src/components/dynamics-form/constructor/items/SingleSelectConstructor.vue
- ui/src/components/dynamics-form/items/JsonInput.vue
- ui/src/views/application/component/AIModeParamSettingDialog.vue
- ui/src/views/application/component/TTSModeParamSettingDialog.vue
> fix: 修复模型参数保存未校验

- ui/src/components/dynamics-form/constructor/items/SliderConstructor.vue
> fix: 修复模型参数，滑块类型参数，步长不能设置为0

- ui/src/components/dynamics-form/constructor/index.vue
- ui/src/components/dynamics-form/items/label/TooltipLabel.vue
fix: 修复模型添加参数，各个字段没有限制长度，并且在应用设置中显示样式错误
> fix: 修复模型添加参数，各个字段没有限制长度，并且在应用设置中显示样式错误

- ui/src/views/application-overview/component/XPackDisplaySettingDialog.vue
- ui/src/views/authentication/component/SCAN.vue
refactor: 应用概览页显示设置页面样式优化  --bug=1048207 --user=王孝刚 【应用】应用概览页显示设置页面样式优化 https://www.tapd.cn/57709429/s/1599274
> refactor: 应用概览页显示设置页面样式优化

- ui/src/components/dynamics-form/constructor/items/SingleSelectConstructor.vue
- ui/src/components/dynamics-form/items/select/SingleSelect.vue
> fix: 修复下拉框字数太多,超出部分隐藏

- ui/src/views/application-overview/component/LimitDialog.vue
- ui/src/views/application-overview/component/XPackDisplaySettingDialog.vue
fix: 修复数字类型输入框可以输入1-3的缺陷  --bug=1048215 --user=王孝刚 【应用】显示设置-图标默认位置输入框输入1-2提交后提示字段不能为空 https://www.tapd.cn/57709429/s/1599573
> fix: 修复数字类型输入框可以输入1-3的缺陷

- apps/common/util/field_message.py
- ui/src/views/login/index.vue
fix: 修复双击ldap结果跳转到oidc的缺陷  --bug=1048233 --user=王孝刚 【用户登录】登录首页-点击LDAP两下，会提示跳转至认证源页面登录 https://www.tapd.cn/57709429/s/1599607
> fix: 修复双击ldap结果跳转到oidc的缺陷

- apps/common/handle/impl/doc_split_handle.py
> fix: 修复导入word文档，有的图片导入不进去

- apps/common/chunk/impl/mark_chunk_handle.py
- apps/setting/models_provider/impl/tencent_model_provider/model/embedding.py
- ui/src/components/markdown/MdRenderer.vue
> fix: 修复知识库文档中若图片不存，前端对话闪烁问题

- apps/application/serializers/chat_serializers.py
- ui/src/views/log/index.vue
fix: 修复对话日志导出，引用分段数、分段标题+内容、知识库检索结果 显示错误的缺陷  --bug=1048277 --user=王孝刚 【应用编排】对话日志导出，引用分段数、分段标题+内容、知识库检索结果 显示错误 https://www.tapd.cn/57709429/s/1599889
> fix: 修复对话日志导出，引用分段数、分段标题+内容、知识库检索结果 显示错误的缺陷

- ui/src/views/log/index.vue
fix: 修复保存清除策略报错的缺陷  --bug=1048275 --user=王孝刚 【应用】有一个应用设置日志清除策略，提示“引用分段数”字段必填 https://www.tapd.cn/57709429/s/1600113
> fix: 修复保存清除策略报错的缺陷

- ui/src/components/markdown/MdRenderer.vue
- ui/src/workflow/nodes/function-node/index.vue
> fix: 修复应用编排自定义函数，数据未清空

- apps/common/handle/impl/pdf_split_handle.py
refactor: PDF分段强制按字数限制  --bug=1047568 --user=刘瑞斌 【github#1363】pdf 文件高级分段默认分段长度为500，但生成的段落长度超过29000字符 https://www.tapd.cn/57709429/s/1600183
> refactor: PDF分段强制按字数限制

- ui/src/components/dynamics-form/constructor/items/JsonInputConstructor.vue
fix: 修复json类型参数没有开启必填，应用中显示了必填标志
> fix: 修复json类型参数没有开启必填，应用中显示了必填标志

- apps/users/serializers/user_serializers.py
> fix: 修复邮箱未设置提示

- ui/src/stores/index.ts
- ui/src/stores/modules/prompt.ts
- ui/src/views/document/component/GenerateRelatedDialog.vue
- ui/src/views/paragraph/component/GenerateRelatedDialog.vue
> refactor: 按用户保存提示词缓存

- ui/src/views/application-overview/component/XPackDisplaySettingDialog.vue
fix: 修复应用恢复默认样式不生效的缺陷  --bug=1048192 --user=王孝刚 【应用】显示设置恢复默认无效 https://www.tapd.cn/57709429/s/1600563
> fix: 修复应用恢复默认样式不生效的缺陷

- apps/dataset/serializers/document_serializers.py
- apps/dataset/serializers/paragraph_serializers.py
> chore: 重复提交的生成任务弹框提示

- apps/dataset/serializers/document_serializers.py
> fix: 修复知识库导出无文档知识库导出无法打开文件

- .gitignore
> fix: 忽略icon文件

- ui/src/views/login/components/dingtalkQrCode.vue
fix: 修复前端报错的缺陷  --bug=1048335 --user=王孝刚 【系统设置】扫描登录页面弹出错误信息：Missing parameters https://www.tapd.cn/57709429/s/1601519
> fix: 修复前端报错的缺陷

- ui/src/components/dynamics-form/constructor/items/SliderConstructor.vue
> fix: 修复模型参数校验问题

- ui/src/locales/lang/zh_CN/views/application-overview.ts
- ui/src/views/application-overview/component/DisplaySettingDialog.vue
- ui/src/views/application-overview/component/EditAvatarDialog.vue
- ui/src/views/log/index.vue
fix: 修复保存清楚时间报错的缺陷  --bug=1048275 --user=王孝刚 【应用】有一个应用设置日志清除策略，提示“引用分段数”字段必填 https://www.tapd.cn/57709429/s/1601736
> fix: 修复保存清楚时间报错的缺陷

- apps/application/serializers/application_serializers.py
> refactor: 删除不必要的代码

- ui/src/components/dynamics-form/items/select/SingleSelect.vue
> fix: 修复对话窗口，全局变量下拉框选项显示不全

- apps/application/serializers/application_serializers.py
fix: 修复应用语音播放试听不生效的问题  --bug=1048023 --user=刘瑞斌 【应用】社区版，应用设置界面，语音合成模型，点击试听没有反应 https://www.tapd.cn/57709429/s/1601904
> fix: 修复应用语音播放试听不生效的问题

- ui/src/views/application/component/TTSModeParamSettingDialog.vue
> fix: 打开语音参数配置时刷新最新的模型参数设置

- apps/application/template/embed.js
fix: 修复浮窗模式嵌入第三方，入口位置调整后引导图没有跟随变更位置
> fix: 修复浮窗模式嵌入第三方，入口位置调整后引导图没有跟随变更位置

- ui/src/components/dynamics-form/index.ts
- ui/src/views/application-workflow/index.vue
- ui/src/workflow/common/app-node.ts
- ui/src/workflow/index.vue
> perf: 优化应用编排历史版本

- ui/src/components/dynamics-form/constructor/index.vue
- ui/src/views/template/component/ParamSettingDialog.vue
> perf: 优化模型表单弹框

- apps/common/cache/file_cache.py
- apps/common/util/cache_util.py
- apps/smartdoc/settings/base.py
> fix: 修复多work导致数据不同步问题

- apps/application/flow/workflow_manage.py
> fix: 修复ai对话回答俩次

- ui/src/views/chat/auth/component/password.vue
> fix: 修复对话认证交互

- ui/src/components/dynamics-form/index.vue
> fix: 修复模型参数修改后,未清除旧数据

- apps/application/flow/step_node/search_dataset_node/impl/base_search_dataset_node.py
fix: 修复工作流知识库检索结果标题不存在的时候显示错误 #1535
> fix: 修复工作流知识库检索结果标题不存在的时候显示错误 #1535

- apps/application/flow/workflow_manage.py
fix: 修复工作流节点未输出数据无法获取执行详情问题 #1550
> fix: 修复工作流节点未输出数据无法获取执行详情问题 #1550

- ui/src/views/template/component/SelectProviderDialog.vue
> refactor: 添加模型时可以过滤图片模型

- ui/src/workflow/common/data.ts
> fix: 修复工作流未展示表单,图片理解,文档提取节点

- apps/application/flow/step_node/document_extract_node/i_document_extract_node.py
- apps/application/flow/step_node/document_extract_node/impl/base_document_extract_node.py
- apps/application/flow/step_node/image_understand_step_node/i_image_understand_node.py
- apps/application/flow/step_node/image_understand_step_node/impl/base_image_understand_node.py
- apps/application/flow/step_node/start_node/impl/base_start_node.py
- apps/application/flow/workflow_manage.py
- apps/application/serializers/chat_message_serializers.py
- apps/application/views/chat_views.py
- ui/src/api/type/application.ts
- ui/src/components/ai-chat/component/chat-input-operate/index.vue
- ui/src/components/ai-chat/component/question-content/index.vue
- ui/src/workflow/nodes/document-extract-node/index.vue
> feat: 高级编排支持文件上传(WIP)

- ui/src/components/ai-chat/component/answer-content/index.vue
> fix: 修复如果工作流未响应数据,响应默认数据

- apps/application/flow/workflow_manage.py
- ui/src/components/ai-chat/component/answer-content/index.vue
> fix: 修复ai对话框无法正常显示对话内容

- apps/application/flow/workflow_manage.py
- apps/application/serializers/application_serializers.py
- apps/application/serializers/chat_serializers.py
> fix: 修复对话时,模型参数删除后依然进行校验

- apps/application/flow/step_node/document_extract_node/impl/base_document_extract_node.py
> fix: 处理多文档时文件内容提取不正确的问题

- ui/src/components/ai-chat/index.vue
> perf: 优化打开chatId代码

- ui/src/workflow/nodes/form-node/index.vue
> style: 修复表单收集样式

- ui/src/components/ai-chat/component/chat-input-operate/index.vue
> refactor: 根据配置类型限制上传文件格式

- ui/src/views/log/component/EditContentDialog.vue
- ui/src/views/log/index.vue
> fix(应用): 修复对话日志添加的知识库的相关问题

- apps/application/serializers/chat_serializers.py
- ui/src/components/ai-chat/ExecutionDetailDialog.vue
fix(知识库): 修复知识库字符未更新的缺陷  --bug=1049232 --user=王孝刚 【应用】对话日志-添加到知识库后，文档字符数未同步更新 https://www.tapd.cn/57709429/s/1614059
> fix(知识库): 修复知识库字符未更新的缺陷

- apps/application/flow/step_node/start_node/impl/base_start_node.py
- ui/src/components/ai-chat/component/question-content/index.vue
fix: 修复对话详情中没有文档展示的问题  --bug=1049251 --user=刘瑞斌 【应用编排】上传文件后，执行详情里没显示文件信息 https://www.tapd.cn/57709429/s/1614098
> fix: 修复对话详情中没有文档展示的问题

- ui/src/views/application/index.vue
- ui/src/views/dataset/index.vue
- ui/src/views/function-lib/index.vue
> refactor: 优化文案

- ui/src/components/ai-chat/component/chat-input-operate/index.vue
fix: 修复单次上传文件限制  --bug=1049382 --user=刘瑞斌 【应用编排】文件上传，单词上传最多文件数没限制住 https://www.tapd.cn/57709429/s/1615405
> fix: 修复单次上传文件限制

- apps/common/handle/impl/table/csv_parse_table_handle.py
- apps/common/handle/impl/table/xls_parse_table_handle.py
- apps/common/handle/impl/table/xlsx_parse_table_handle.py
> chore: 文档内容无法提取的时候输出错误信息

- ui/src/components/ai-chat/component/chat-input-operate/index.vue
fix: 修复对话页面pdf不能正常上传的问题  --bug=1049431 --user=刘瑞斌 【应用编排】应用对话，上传文档无法选择pdf文档 https://www.tapd.cn/57709429/s/1616013
> fix: 修复对话页面pdf不能正常上传的问题

- apps/application/flow/step_node/document_extract_node/impl/base_document_extract_node.py
> refactor: 多文档分割线展示为多个‘-’

- apps/application/chat_pipeline/I_base_chat_pipeline.py
- apps/application/chat_pipeline/step/search_dataset_step/impl/base_search_dataset_step.py
- apps/application/sql/list_dataset_paragraph_by_paragraph_id.sql
- ui/src/components/ai-chat/KnowledgeSource.vue
- ui/src/components/ai-chat/component/ParagraphCard.vue
refactor: 优化知识来源显示  --story=1016652 --user=王孝刚 【南区】应用对话回复支持显示引用分段来知识库的文档来源等信息 https://www.tapd.cn/57709429/s/1616642
> refactor: 优化知识来源显示

- ui/src/workflow/nodes/base-node/component/UserFieldFormDialog.vue
- ui/src/workflow/nodes/base-node/component/UserInputFieldTable.vue
> feat: 高级应用用户输入参数增加多选类型

- ui/src/workflow/nodes/base-node/component/UserFieldFormDialog.vue
- ui/src/workflow/nodes/base-node/component/UserInputFieldTable.vue
> feat: 高级应用用户输入参数增加选项卡类型

- ui/src/components/ai-chat/ExecutionDetailDialog.vue
> refactor: 执行详情展示图片理解模型的tokens

- ui/src/components/ai-chat/ExecutionDetailDialog.vue
> fix: 去掉本次对话

- ui/src/components/ai-chat/component/chat-input-operate/index.vue
refactor: 上传附件tooltip展示大写后缀以、分割
> refactor: 上传附件tooltip展示大写后缀以、分割

- ui/src/components/ai-chat/ExecutionDetailDialog.vue
> refactor: 优化执行详情展示

- apps/application/serializers/chat_message_serializers.py
- apps/application/serializers/chat_serializers.py
- apps/dataset/serializers/paragraph_serializers.py
fix: 修复在对话日志中删除保存的文档，关联的问题未删除的缺陷  --bug=1049555 --user=王孝刚 【应用】将对话日志保存到文档后，在对话日志中删除保存的文档，关联的问题未删除 https://www.tapd.cn/57709429/s/1617726
> fix: 修复在对话日志中删除保存的文档，关联的问题未删除的缺陷

- apps/common/db/sql_execute.py
- apps/common/event/listener_manage.py
- apps/common/util/page_utils.py
- apps/dataset/serializers/document_serializers.py
- ui/src/views/document/component/Status.vue
- ui/src/views/document/component/StatusTable.vue
> fix: 修复文档状态数据数据错误问题

- apps/application/serializers/chat_serializers.py
fix: 修复删除知识库的段落后，日志内容还是显示标注的缺陷
> fix: 修复删除知识库的段落后，日志内容还是显示标注的缺陷

- apps/common/event/listener_manage.py
- apps/dataset/migrations/0011_document_status_meta_paragraph_status_meta_and_more.py
- apps/dataset/serializers/document_serializers.py
- apps/dataset/task/generate.py
- apps/embedding/task/embedding.py
- apps/smartdoc/settings/lib.py
- ui/src/views/document/component/StatusTable.vue
- ui/src/views/document/index.vue
> fix: 修复文档状态部分问题

- apps/application/flow/step_node/document_extract_node/impl/base_document_extract_node.py
- apps/application/flow/step_node/image_understand_step_node/impl/base_image_understand_node.py
fix: 修复文档提取参数选择了开始问题报会话不存在的问题  --bug=1049648 --user=刘瑞斌 【应用编排】文档内容提取节点，节点设置选择 “开始-用户问题” 对话报错 https://www.tapd.cn/57709429/s/1619714
> fix: 修复文档提取参数选择了开始问题报会话不存在的问题

- apps/application/flow/step_node/document_extract_node/i_document_extract_node.py
- apps/application/flow/step_node/document_extract_node/impl/base_document_extract_node.py
- apps/common/handle/base_split_handle.py
- apps/common/handle/impl/doc_split_handle.py
- apps/common/handle/impl/html_split_handle.py
- apps/common/handle/impl/pdf_split_handle.py
- apps/common/handle/impl/text_split_handle.py
- apps/dataset/serializers/file_serializers.py
> fix: 修复文档提取doc图片没有保存和展示的问题

- apps/application/serializers/application_serializers.py
fix: 修复应用复制没有把语音和文件上传配置一起复制的问题  --bug=1049519 --user=刘瑞斌 【应用】应用复制，复制的副本没有将语音输入和语音合成模型复制过来 https://www.tapd.cn/57709429/s/1620615
> fix: 修复应用复制没有把语音和文件上传配置一起复制的问题

- apps/common/handle/impl/table/xlsx_parse_table_handle.py
> fix: 修复上传xlsx里的图片没在文档提取中显示的问题

- apps/application/flow/step_node/application_node/impl/base_application_node.py
- ui/src/workflow/icons/application-node-icon.vue
fix: 修复嵌入应用的指定回复节点回复None的缺陷  --bug=1049643 --user=王孝刚 【应用】简单应用输出节点连接多个执行回复节点，回复节点引用简单应用的输出结果变量，执行后回复结果为None https://www.tapd.cn/57709429/s/1621456
> fix: 修复嵌入应用的指定回复节点回复None的缺陷

- apps/application/flow/i_step_node.py
- apps/application/flow/step_node/form_node/i_form_node.py
- apps/application/flow/step_node/form_node/impl/base_form_node.py
- apps/application/flow/workflow_manage.py
- apps/application/serializers/chat_message_serializers.py
- apps/application/views/chat_views.py
- apps/common/handle/base_to_response.py
- apps/common/handle/impl/response/openai_to_response.py
- apps/common/handle/impl/response/system_to_response.py
- apps/dataset/migrations/0011_document_status_meta_paragraph_status_meta_and_more.py
- ui/src/api/type/application.ts
- ui/src/components/ai-chat/index.vue
- ui/src/components/markdown/FormRander.vue
> fix: 修复工作流节点输出等问题

- apps/application/flow/step_node/form_node/impl/base_form_node.py
- apps/application/serializers/chat_message_serializers.py
fix: 修复工作流多个form表单收集后面节点无法使用表单数据
> fix: 修复工作流多个form表单收集后面节点无法使用表单数据

- apps/application/flow/workflow_manage.py
- ui/src/api/type/application.ts
- ui/src/components/ai-chat/ExecutionDetailDialog.vue
- ui/src/components/ai-chat/component/answer-content/index.vue
- ui/src/components/ai-chat/index.vue
- ui/src/components/markdown/FormRander.vue
- ui/src/components/markdown/MdRenderer.vue
> fix: 修复对话中禁止表单提交

- apps/application/chat_pipeline/step/chat_step/impl/base_chat_step.py
- ui/src/api/type/application.ts
> fix: 修复简易应用对话无法显示内容

- ui/src/workflow/nodes/form-node/index.vue
> fix: 修复表单添加无法点击无效

- apps/embedding/vector/base_vector.py
> fix: 修复关联问题不生效

- apps/application/flow/workflow_manage.py
> fix: 修复对话后未生成对话日志

- apps/application/flow/step_node/start_node/impl/base_start_node.py
> fix: 修复表单设置后的文档内容提取节点不能输出内容

- apps/dataset/serializers/document_serializers.py
> fix: 修复web站点知识库同步状态错误

- apps/dataset/migrations/0011_document_status_meta_paragraph_status_meta_and_more.py
fix: 修复历史数据状态错误<br>fix: 修复历史数据状态错误
> fix: 修复历史数据状态错误

- ui/src/components/ai-chat/ExecutionDetailDialog.vue
> feat: 执行详情表单收集显示样式修改

- ui/package.json
> build: 打包指定内存为4G

- ui/src/workflow/nodes/form-node/index.vue
> fix: 修复表单收集删除表单配置后，参数输出没有及时更新

- apps/embedding/task/embedding.py
fix: 修复选择不可用的本地模型进行向量化,状态一直是排队中
> fix: 修复选择不可用的本地模型进行向量化,状态一直是排队中

- apps/common/job/clean_chat_job.py
- ui/src/views/authentication/component/EditModal.vue
- ui/src/views/authentication/component/SCAN.vue
refactor: 钉钉扫码认证设置优化  --bug=1048604 --user=王孝刚 【系统管理】钉钉扫码认证设置优化 https://www.tapd.cn/57709429/s/1622777
> refactor: 钉钉扫码认证设置优化

- ui/src/components/ai-chat/component/operation-button/LogOperationButton.vue
fix: 修复重复修改内容增加新的分段缺陷  --bug=1049256 --user=王孝刚 【应用日志】日志详情，修改内容，多次修改不应该新增新的分段 https://www.tapd.cn/57709429/s/1623112
> fix: 修复重复修改内容增加新的分段缺陷

- ui/src/components/ai-chat/component/answer-content/index.vue
- ui/src/components/ai-chat/component/operation-button/index.vue
- ui/src/components/ai-chat/index.vue
- ui/src/views/team/component/PermissionSetting.vue
> fix: 修复团队成员勾选管理同时勾选查看(#1664)

- apps/application/flow/i_step_node.py
- apps/application/flow/step_node/application_node/i_application_node.py
- apps/application/flow/step_node/application_node/impl/base_application_node.py
- apps/application/flow/step_node/form_node/i_form_node.py
- apps/application/flow/step_node/form_node/impl/base_form_node.py
- apps/application/flow/workflow_manage.py
- apps/application/migrations/0019_application_file_upload_enable_and_more.py
- apps/application/models/application.py
- apps/application/serializers/chat_message_serializers.py
- apps/application/views/chat_views.py
- apps/common/handle/impl/response/openai_to_response.py
- apps/common/handle/impl/response/system_to_response.py
- apps/embedding/task/embedding.py
- ui/src/api/type/application.ts
- ui/src/components/ai-chat/component/answer-content/index.vue
- ui/src/components/ai-chat/index.vue
- ui/src/components/markdown/FormRander.vue
- ui/src/components/markdown/MdRenderer.vue
> fix: 修复子应用表单调用无法调用问题

- apps/dataset/serializers/document_serializers.py
fix: 修复删除文档不会删除文档中分段关联的问题的缺陷  --bug=1048687 --user=王孝刚 【知识库】删除文档不会删除文档中分段关联的问题 https://www.tapd.cn/57709429/s/1623302
> fix: 修复删除文档不会删除文档中分段关联的问题的缺陷

- apps/common/util/fork.py
fix: 修复字符集不匹配的情况提取web的问题  --bug=1048607 --user=刘瑞斌 【github#1577】有个网站导入web知识库报错 https://www.tapd.cn/57709429/s/1623295
> fix: 修复字符集不匹配的情况提取web的问题

- ui/src/views/login/index.vue
style: 修改登录样式  --bug=1049910 --user=王孝刚 【登录】oauth2缩写字号；整体颜色改为主色 B500 https://www.tapd.cn/57709429/s/1623524
> style: 修改登录样式

- ui/src/components/dynamics-form/constructor/items/RadioRowConstructor.vue
- ui/src/workflow/nodes/base-node/component/UserInputFieldTable.vue
- ui/src/workflow/nodes/form-node/index.vue
fix: 修复表单收集列表中的默认值显示问题  --bug=1049462 --user=刘瑞斌 【表单收集】- 单选项、多选项、选项卡的默认值显示的不是标签 https://www.tapd.cn/57709429/s/1623556<br>fix: 修复表单收集列表中的单行选项卡问题  --bug=1049886 --user=刘瑞斌 【应用编排】表单添加单行选项卡字段，添加后变成了选项卡类型 https://www.tapd.cn/57709429/s/1623563
> fix: 修复表单收集列表中的单行选项卡问题

- ui/package.json
> build: 设置前端打包内存

- apps/application/flow/workflow_manage.py
- ui/src/components/ai-chat/index.vue
> fix: 修复没有输出节点时无法处理内容

- ui/src/components/dynamics-form/items/radio/RadioCard.vue
- ui/src/components/dynamics-form/items/radio/RadioRow.vue
> fix: 修复选项卡设置为禁用

- ui/src/views/authentication/component/OAuth2.vue
> refactor: 修改OAuth2

- ui/src/workflow/common/NodeCascader.vue
- ui/src/workflow/nodes/form-node/index.vue
> fix: 修复form表单数据无法响应式更新

- apps/dataset/serializers/document_serializers.py
- apps/dataset/serializers/paragraph_serializers.py
fix: 修复批量删除文档没有删除问题的缺陷  --bug=1048687 --user=王孝刚 【知识库】删除文档不会删除文档中分段关联的问题 https://www.tapd.cn/57709429/s/1624544
> fix: 修复批量删除文档没有删除问题的缺陷

- apps/common/event/__init__.py
- apps/smartdoc/settings/lib.py
> fix: 修复项目重启后文档状态不正确

- apps/dataset/serializers/dataset_serializers.py
- apps/dataset/serializers/document_serializers.py
- ui/src/workflow/common/NodeCascader.vue
> fix: 修复知识库向量化提示错误

- ui/src/views/login/index.vue
refactor: 优化退出登录后刷新页面  --bug=1049954 --user=王孝刚 【系统设置】退出登录后登录页面刷新两次，需优化 https://www.tapd.cn/57709429/s/1624834
> refactor: 优化退出登录后刷新页面

- ui/src/views/document/component/Status.vue
> fix: 修复文档状态在有取消向量化的情况下状态错误

- apps/application/flow/step_node/form_node/impl/base_form_node.py
> fix: 修复form表单表单数据未解构

- apps/dataset/serializers/document_serializers.py
> fix: 修复迁移文档分段数没有重置

- apps/common/management/commands/services/command.py
> refactor: 修改默认worker计算方法

- ui/src/components/ai-chat/component/answer-content/index.vue
- ui/src/components/markdown/FormRander.vue
- ui/src/components/markdown/MdRenderer.vue
> fix: 修复对话日志中表单未被禁用

- apps/common/util/common.py
- apps/dataset/serializers/document_serializers.py
> refactor: 优化大量数据批量入库

- ui/src/components/ai-chat/component/operation-button/ChatOperationButton.vue
- ui/src/components/ai-chat/component/operation-button/LogOperationButton.vue
> fix: 语音播放去掉formrander相关文本

- apps/setting/models_provider/impl/aliyun_bai_lian_model_provider/model/embedding.py
> fix: 修复阿里百炼项目模型v3调用方式

- ui/src/views/authentication/component/EditModal.vue
fix: 企业微信扫码信息配置错误  --bug=1050048 --user=王孝刚 【企业微信-扫码登录】配置信息错误 https://www.tapd.cn/57709429/s/1626175
> fix: 企业微信扫码信息配置错误

- apps/setting/models_provider/impl/zhipu_model_provider/credential/image.py
- apps/setting/models_provider/impl/zhipu_model_provider/model/image.py
- apps/setting/models_provider/impl/zhipu_model_provider/zhipu_model_provider.py
> feat: 支持智谱图片理解模型

- ui/src/router/modules/application.ts
- ui/src/router/modules/dataset.ts
- ui/src/router/modules/function-lib.ts
> fix: 修复前端路由警告

- ui/src/components/ai-chat/component/question-content/index.vue
fix: 修复历史记录不显示图片的缺陷  --bug=1050151 --user=王孝刚 【应用】演示界面、全屏嵌入、浮窗嵌入历史记录和对话日志中不显示上传的图片 https://www.tapd.cn/57709429/s/1627628
> fix: 修复历史记录不显示图片的缺陷

- ui/src/components/ai-chat/component/operation-button/ChatOperationButton.vue
- ui/src/components/ai-chat/component/operation-button/LogOperationButton.vue
> fix: 语音播放去掉form_rander相关文本

- apps/application/serializers/chat_message_serializers.py
- ui/src/api/type/application.ts
- ui/src/workflow/nodes/ai-chat-node/index.vue
> fix: 修复工作流对话bug

- ui/src/components/ai-chat/component/operation-button/ChatOperationButton.vue
- ui/src/components/ai-chat/component/operation-button/LogOperationButton.vue
> fix: 处理回复中的html标签和内容

- README_EN.md
> chore: Update README_EN.md

- apps/application/flow/step_node/image_generate_step_node/impl/base_image_generate_node.py
refactor: Image generate model history message show images
> refactor: Image generate model history message show images

- installer/Dockerfile
build: Add ffmpeg Linux dependency
> build: Add ffmpeg Linux dependency

- installer/Dockerfile
> build: Ffmpeg Linux address

- .github/workflows/build-and-push.yml
- installer/Dockerfile
security: minimize permission of sandbox user
> security: minimize permission of sandbox user

- apps/setting/models_provider/impl/gemini_model_provider/credential/image.py
- apps/setting/models_provider/impl/gemini_model_provider/gemini_model_provider.py
- apps/setting/models_provider/impl/gemini_model_provider/model/image.py
feat: Gemini Image understand model
> feat: Gemini Image understand model

- apps/application/flow/step_node/speech_to_text_step_node/impl/base_speech_to_text_node.py
- apps/common/util/common.py
- apps/dataset/serializers/file_serializers.py
- apps/setting/models_provider/impl/vllm_model_provider/credential/llm.py
- apps/setting/models_provider/impl/vllm_model_provider/vllm_model_provider.py
- ui/src/components/ai-chat/component/chat-input-operate/index.vue
- ui/src/workflow/nodes/base-node/component/FileUploadSettingDialog.vue
refactor: Support uploading multiple audio files
> refactor: Support uploading multiple audio files

- apps/application/flow/step_node/speech_to_text_step_node/impl/base_speech_to_text_node.py
> fix: any_to_mp3

- apps/common/util/common.py
> fix: set audio channels

- apps/application/template/embed.js
> fix: Support embedding multiple Applications

- apps/application/flow/step_node/speech_to_text_step_node/i_speech_to_text_node.py
- apps/application/flow/step_node/text_to_speech_step_node/i_text_to_speech_node.py
- ui/src/views/application-workflow/index.vue
- ui/src/workflow/nodes/speech-to-text-node/index.vue
- ui/src/workflow/nodes/text-to-speech-node/index.vue
fix: fix workflow parameter verification  --bug=1050548 --user=王孝刚 【应用】-高级编排语音转文本组件的语音文件为空可以发布应用 https://www.tapd.cn/57709429/s/1634944
> fix: fix workflow parameter verification

- apps/application/flow/workflow_manage.py
refactor: Workflow execution logic
> refactor: Workflow execution logic

- apps/common/util/common.py
> fix: fix audio frame rate

- apps/setting/models_provider/impl/aliyun_bai_lian_model_provider/model/stt.py
> fix: fix bailian stt

- apps/application/serializers/application_serializers.py
fix: Import application and add file format verification
> fix: Import application and add file format verification

- apps/application/serializers/application_serializers.py
- apps/application/template/embed.js
fix: The application cannot be embedded
> fix: The application cannot be embedded

- apps/application/serializers/application_serializers.py
- apps/application/template/embed.js
- ui/src/views/application-workflow/component/DropdownMenu.vue
- ui/src/workflow/index.vue
- ui/src/workflow/nodes/function-lib-node/index.vue
fix: The application cannot be embedded<br>fix: When dragging and adding a workflow function node, it prompts that the ID does not exist
> fix: When dragging and adding a workflow function node, it prompts that the ID does not exist

- ui/src/views/application/index.vue
fix: Multiple imports of the same file without response
> fix: Multiple imports of the same file without response

- apps/application/serializers/application_serializers.py
- apps/application/urls.py
- apps/application/views/application_views.py
- ui/src/api/application.ts
- ui/src/workflow/common/NodeContainer.vue
- ui/src/workflow/nodes/application-node/index.vue
fix: refactoring embedded application logic
> fix: refactoring embedded application logic

- apps/setting/models_provider/impl/aws_bedrock_model_provider/credential/embedding.py
- apps/setting/models_provider/impl/aws_bedrock_model_provider/credential/llm.py
- apps/setting/models_provider/impl/aws_bedrock_model_provider/model/embedding.py
- apps/setting/models_provider/impl/aws_bedrock_model_provider/model/llm.py
- apps/setting/serializers/provider_serializers.py
fix: aws credentials_profile_name
> fix: aws credentials_profile_name

- installer/Dockerfile
build: Specify the poetry version
> build: Specify the poetry version

- apps/setting/models_provider/impl/volcanic_engine_model_provider/credential/embedding.py
- apps/setting/models_provider/impl/volcanic_engine_model_provider/model/embedding.py
- apps/setting/models_provider/impl/volcanic_engine_model_provider/volcanic_engine_model_provider.py
refactor: support volcanic engine embeddings
> refactor: support volcanic engine embeddings

- ui/src/locales/lang/en_US/index.ts
- ui/src/locales/lang/en_US/views/system.ts
- ui/src/locales/lang/zh_CN/index.ts
- ui/src/locales/lang/zh_CN/views/system.ts
- ui/src/locales/lang/zh_TW/index.ts
- ui/src/locales/lang/zh_TW/views/system.ts
- ui/src/router/modules/setting.ts
- ui/src/views/email/index.vue
> feat: email i18n

- apps/dataset/serializers/common_serializers.py
- apps/dataset/serializers/dataset_serializers.py
- apps/dataset/serializers/document_serializers.py
- apps/dataset/serializers/file_serializers.py
- apps/dataset/serializers/image_serializers.py
- apps/dataset/serializers/paragraph_serializers.py
- apps/dataset/serializers/problem_serializers.py
- apps/dataset/swagger_api/document_api.py
- apps/dataset/swagger_api/image_api.py
- apps/dataset/swagger_api/problem_api.py
- apps/dataset/task/generate.py
- apps/dataset/task/sync.py
- apps/dataset/task/tools.py
- apps/dataset/views/dataset.py
- apps/dataset/views/document.py
- apps/dataset/views/file.py
- apps/dataset/views/image.py
- apps/dataset/views/paragraph.py
- apps/dataset/views/problem.py
- apps/setting/models_provider/impl/anthropic_model_provider/credential/image.py
- apps/setting/models_provider/impl/anthropic_model_provider/credential/llm.py
> feat: dataset support i18n

- apps/dataset/serializers/document_serializers.py
- apps/dataset/views/file.py
- apps/locales/en_US/LC_MESSAGES/django.po
- apps/locales/zh_CN/LC_MESSAGES/django.po
- apps/locales/zh_Hant/LC_MESSAGES/django.po
> feat: Generate i18n file

- apps/application/flow/step_node/application_node/i_application_node.py
- apps/application/flow/step_node/function_node/i_function_node.py
- apps/application/flow/step_node/search_dataset_node/i_search_dataset_node.py
- apps/locales/en_US/LC_MESSAGES/django.po
- apps/locales/zh_CN/LC_MESSAGES/django.po
- apps/locales/zh_Hant/LC_MESSAGES/django.po
- ui/src/locales/lang/en_US/views/system.ts
- ui/src/locales/lang/zh_CN/views/system.ts
- ui/src/locales/lang/zh_TW/views/system.ts
> feat: i18n

- ui/src/views/application-workflow/index.vue
- ui/src/workflow/common/app-node.ts
- ui/src/workflow/common/edge.ts
- ui/src/workflow/common/teleport.ts
- ui/src/workflow/index.vue
perf: Optimize the rendering logic of front-end nodes
> perf: Optimize the rendering logic of front-end nodes

- apps/locales/en_US/LC_MESSAGES/django.po
- apps/locales/zh_CN/LC_MESSAGES/django.po
- apps/locales/zh_Hant/LC_MESSAGES/django.po
> feat: xpack i18n

- ui/src/components/dynamics-form/items/JsonInput.vue
- ui/src/locales/lang/en_US/views/function-lib.ts
- ui/src/locales/lang/zh_CN/views/function-lib.ts
- ui/src/locales/lang/zh_TW/views/function-lib.ts
- ui/src/views/function-lib/component/FunctionFormDrawer.vue
- ui/src/workflow/nodes/function-node/index.vue
fix: 1050995  --bug=1050995 --user=王孝刚 【函数库】-创建函数，Python 代码为空时提示语和界面显示标题的不符 https://www.tapd.cn/57709429/s/1647978
> fix: 1050995

- installer/Dockerfile
> feat: compilemessages i18n

- installer/Dockerfile-python-pg
> build: install gettext

- apps/smartdoc/conf.py
- installer/Dockerfile
> build: compilemessages i18n

- pyproject.toml
> feat: django version

- ui/src/components/ai-chat/component/operation-button/ChatOperationButton.vue
fix: When there is only a voice file in the answer, an error is reported when reading it aloud.  --bug=1051784 --user=刘瑞斌 【应用编排】回答中只有语音文件的时候，朗读报错 https://www.tapd.cn/57709429/s/1649307
> fix: When there is only a voice file in the answer, an error is reported when reading it aloud.

- apps/application/flow/workflow_manage.py
fix: Workflow global variables
> fix: Workflow global variables

- ui/package.json
- ui/src/components/markdown/MdEditor.vue
> feat: add markdown language

- ui/src/locales/lang/en-US/views/application-overview.ts
- Refined terminology for better clarity and consistency
- Adjusted "Public Access Link" to "Public URL" for a more natural expression
- Revised "Authentication Password" to "Access Password" to align with the actual use case
- Updated "User Satisfaction" to "User Feedback Metrics" for better relevance in RAG evaluation
- Changed "Embed in website" to "Get Embed Code" to match the functionality
- Change "Do" to "Are you sure" to align with the language convention of confirmation dialogs
Refer to the commit details for more changes
/release-note none
> chore: improve UI translation for workflow application overview page

- apps/common/event/listener_manage.py
- apps/dataset/sql/update_paragraph_status.sql
fix: Fix the defect that the knowledge base vectorization time is inconsistent with the system  --bug=1052060 --user=王孝刚 【知识库】-同步Web站点知识库，同步状态的时间与当前时区不一致，晚8小时 https://www.tapd.cn/57709429/s/1651754
> fix: Fix the defect that the knowledge base vectorization time is inconsistent with the system

- ui/src/views/authentication/component/LDAP.vue
fix: Prompt message error  --bug=1052066 --user=王孝刚 [系统设置] LDAP环境测试连接失败 https://www.tapd.cn/57709429/s/1651802
> fix: Prompt message error

- ui/src/locales/lang/en-US/ai-chat.ts
- ui/src/locales/lang/en-US/views/application-overview.ts
- Changed "Approval" → "Like" and "Disapproval" → "Dislike" for statistical labels to better align with UI feedback terminology.
- Updated "Agree" / "Disagree" to "Like" / "Dislike" to match common UI expressions.
- Refined translations for clearer and more natural English phrasing.
- Adjusted button labels and tooltips for better user experience.
Wording optimization：
- “No History” → “No Chat History” （更明确）
- “Re-answer” → “Regenerate Response” （更贴近 AI 对话场景）
- “Output stopped” → “Response Stopped”（“Output” 过于技术化）
- “Thinking” → “Generating Response”（更贴合 AI 交互）
- “Download File” → “Click to Download”（更贴合 UI 按钮文案）
- “Enter password to open the link” → “Enter Password to Access”（更精炼）
- “Tokens” → “Token Consumption”（避免单词歧义）
- “Run Time” → “Processing Time”（更自然）
> chore(i18n): improve UI translation for AI chat page

- ui/src/utils/utils.ts
- ui/src/views/dataset/component/SetRules.vue
- ui/src/views/dataset/component/UploadComponent.vue
fix: Dealing with the issue of filename exceeding 128 characters when uploading documents(#2144)
> fix: Dealing with the issue of filename exceeding 128 characters when uploading documents(#2144)

- USE-CASES.md
> chore: Add USE-CASES.md

- USE-CASES.md
> Add a case

- README.md
> docs: Update screenshots in README.md

- README.md
> chore: Add Star History

- apps/locales/zh_CN/LC_MESSAGES/django.po
fix: chat record message export error
> fix: chat record message export error

- apps/application/serializers/application_serializers.py
- ui/src/views/application-overview/component/DisplaySettingDialog.vue
fix: application set language error
> fix: application set language error

- .github/workflows/build-and-push-python-pg.yml
- .github/workflows/build-and-push-vector-model.yml
- .github/workflows/build-and-push.yml
- https://github.com/tonistiigi/binfmt/issues/215
> perf: 更新 qemu

- ui/src/workflow/nodes/base-node/component/UserFieldFormDialog.vue
feat: Support switch input for application user params  --story=1017769 --user=刘瑞斌 【越秀农牧】希望用户输入可以添加一个开关组件 https://www.tapd.cn/57709429/s/1654429
> feat: Support switch input for application user params

- apps/application/swagger_api/chat_api.py
- apps/locales/en_US/LC_MESSAGES/django.po
- apps/locales/zh_CN/LC_MESSAGES/django.po
- apps/locales/zh_Hant/LC_MESSAGES/django.po
fix: Complete document parameters  --bug=1052250 --user=王孝刚 【API】在swagger上调用对话API ，希望把参数给补充完整。（比如，上传文档的一些参数） https://www.tapd.cn/57709429/s/1655242
> fix: Complete document parameters

- ui/src/components/ai-chat/component/user-form/index.vue
- ui/src/components/dynamics-form/constructor/items/TextInputConstructor.vue
- ui/src/locales/lang/en-US/dynamics-form.ts
- ui/src/locales/lang/zh-CN/dynamics-form.ts
- ui/src/locales/lang/zh-Hant/dynamics-form.ts
- ui/src/workflow/nodes/base-node/component/UserInputFieldTable.vue
- ui/src/workflow/nodes/base-node/component/UserInputTitleDialog.vue
feat: Supports specified user input title  --story=1017888 --user=刘瑞斌 【高级编排应用】“用户输入”可以自定义。 #2288 https://www.tapd.cn/57709429/s/1655214<br>feat: Supports user input field type password  --story=1017895 --user=刘瑞斌 【用户输入】- 组件类型为文本框类型的支持密文显示#2134 https://www.tapd.cn/57709429/s/1655257
> feat: Supports user input field type password

- ui/package.json
- ui/src/components/ai-chat/component/question-content/index.vue
- ui/src/components/markdown/MdRenderer.vue
- ui/src/components/markdown/ReasoningRander.vue
- ui/src/views/chat/base/index.vue
> Pr@main/chat style

- apps/application/chat_pipeline/step/search_dataset_step/i_search_dataset_step.py
- apps/application/flow/step_node/search_dataset_node/i_search_dataset_node.py
- apps/application/serializers/application_serializers.py
- apps/dataset/serializers/dataset_serializers.py
> fix: bad code copy

- ui/src/views/application/component/AccessSettingDrawer.vue
修复 Slack 设置的 Drawer title 没有显示的问题
**Before:**
**After:**
> fix: drawer title for slack setting

- ui/src/locales/lang/en-US/views/dataset.ts
- ui/src/locales/lang/en-US/views/system.ts
optimize english translations and standardize title case
> chore(i18n): optimize english translations and standardize title case

- ui/src/locales/lang/en-US/views/application-workflow.ts
- ui/src/locales/lang/zh-CN/views/application-workflow.ts
- ui/src/locales/lang/zh-Hant/views/application-workflow.ts
- ui/src/views/application-workflow/index.vue
> perf: Add a tip before exiting the workflow

- pyproject.toml
feat: Upgrade xinference client
> feat: Upgrade xinference client

- apps/function_lib/serializers/function_lib_serializer.py
fix: Fix import function lib permission  --bug=1052409 --user=刘瑞斌 【函数库】导入一个原来是公有的函数，函数的权限依然是公有 https://www.tapd.cn/57709429/s/1658705
> fix: Fix import function lib permission

- apps/application/serializers/chat_serializers.py
fix: Dialogue log export, question time does not match on the page
> fix: Dialogue log export, question time does not match on the page

- apps/smartdoc/settings/base.py
> perf: enable gzip.

- apps/application/chat_pipeline/step/chat_step/impl/base_chat_step.py
fix: record log content error  --bug=1052670 --user=王孝刚 应用-企业微信对接应用后，在企业微信中与应用对话，对话日志中<think></think>思考过程输出了两次 https://www.tapd.cn/57709429/s/1661186
> fix: record log content error

- apps/setting/models_provider/impl/aliyun_bai_lian_model_provider/model/tts.py
fix: Compatible with dashscope tts  --bug=1052708 --user=刘瑞斌 【应用】-使用阿里云语音合成模型sambert-zhichu-v1，对话报错 https://www.tapd.cn/57709429/s/1661551
> fix: Compatible with dashscope tts

- ui/src/views/function-lib/index.vue
refactor: disable buttons based on permission type  --bug=1052737 --user=刘瑞斌 【函数库】-非当前用户所有的函数，不应该支持复制和导出 https://www.tapd.cn/57709429/s/1661776
> refactor: disable buttons based on permission type

- apps/setting/models_provider/impl/azure_model_provider/model/azure_chat_model.py
refactor: add model_name parameter to AzureChatModel initialization  --bug=1052553 --user=刘瑞斌 【模型】添加 Azure OpenAI 添加DeepSeek -R1 模型报错 https://www.tapd.cn/57709429/s/1661953
> refactor: add model_name parameter to AzureChatModel initialization

- USE-CASES.md
> chore: Update USE-CASES.md

- apps/function_lib/views/function_lib_views.py
refactor: Add mysql function log recorder
> refactor: Add mysql function log recorder

- apps/dataset/views/file.py
> chore: fix some log recorder

- apps/common/encoder/encoder.py
> chore: add some encoder type

- ui/src/request/index.ts
> fix: type-check

- apps/application/serializers/application_serializers.py
- apps/common/util/common.py
fix: Application import deserialization vulnerability #2604
> fix: Application import deserialization vulnerability #2604

- apps/locales/en_US/LC_MESSAGES/django.po
- apps/locales/zh_CN/LC_MESSAGES/django.po
- apps/locales/zh_Hant/LC_MESSAGES/django.po
> feat: export operate log

- apps/application/serializers/application_serializers.py
- ui/src/locales/lang/en-US/views/application-overview.ts
- ui/src/locales/lang/zh-CN/views/application-overview.ts
- ui/src/locales/lang/zh-Hant/views/application-overview.ts
- ui/src/views/application-overview/component/XPackDisplaySettingDialog.vue
- ui/src/views/dataset/DatasetSetting.vue
- ui/src/views/dataset/component/CreateDatasetDialog.vue
refactor: Optimization of Q&A page  --story=1018176 --user=王孝刚 【问答页面】优化对话页面显示 https://www.tapd.cn/57709429/s/1674146
> refactor: Optimization of Q&A page

- ui/src/components/generate-related-dialog/index.vue
- ui/src/components/model-select/index.vue
- ui/src/views/application/ApplicationSetting.vue
- ui/src/views/dataset/component/BaseForm.vue
- ui/src/views/template/component/CreateModelDialog.vue
- ui/src/views/template/component/SelectProviderDialog.vue
- ui/src/views/template/index.vue
- ui/src/workflow/nodes/ai-chat-node/index.vue
- ui/src/workflow/nodes/base-node/index.vue
- ui/src/workflow/nodes/image-generate/index.vue
- ui/src/workflow/nodes/image-understand/index.vue
- ui/src/workflow/nodes/question-node/index.vue
- ui/src/workflow/nodes/reranker-node/index.vue
- ui/src/workflow/nodes/speech-to-text-node/index.vue
- ui/src/workflow/nodes/text-to-speech-node/index.vue
fix: Optimize the creation of models  --bug=1053742 --user=王孝刚 【模型管理】- 创建模型时，若在选择供应商列表选择了模型类型，进入供应商表单时，携带模型类型 https://www.tapd.cn/57709429/s/1674767
> fix: Optimize the creation of models

- ui/src/components/ai-chat/component/operation-button/ChatOperationButton.vue
fix: Voice playback is not played in order
> fix: Voice playback is not played in order

- ui/src/components/ai-chat/component/user-form/index.vue
fix: enhance validation for required form fields  --bug=1052705 --user=刘瑞斌 【工作流】添加”开关”按钮参数， 默认值为关闭，保存之后页面还会提示“请填写所填字段” https://www.tapd.cn/57709429/s/1675323
> fix: enhance validation for required form fields

- apps/setting/models_provider/impl/aliyun_bai_lian_model_provider/model/tts.py
fix: handle audio generation failure by raising an exception
> fix: handle audio generation failure by raising an exception

- apps/locales/zh_CN/LC_MESSAGES/django.po
- apps/locales/zh_Hant/LC_MESSAGES/django.po
refactor: i18n  --bug=1054121 --user=王孝刚 操作日志：修改应用的访问限制在操作日志中显示为修改应用的access token https://www.tapd.cn/57709429/s/1678535
> refactor: i18n

- README_CN.md
> chore: Update README_CN.md

- ui/src/locales/lang/en-US/views/document.ts
- ui/src/views/application-overview/component/APIKeyDialog.vue
- ui/src/views/application-overview/index.vue
- ui/src/views/dataset/ImportDocumentDataset.vue
- ui/src/views/function-lib/component/FunctionFormDrawer.vue
> perf: Optimize application setting switch button control

- ui/src/workflow/nodes/condition-node/index.vue
fix: When the discriminator is true, there is no problem with the value
> fix: When the discriminator is true, there is no problem with the value

- .github/dependabot.yml
- .gitignore
- apps/maxkb/const.py
- pyproject.toml
chore: add dependabot configuration for pip updates<br>feat: load environment variables from .env file and update config loading logic
> feat: load environment variables from .env file and update config loading logic

- .github/dependabot.yml
chore: add dependabot configuration for weekly pip updates for v2
> chore: add dependabot configuration for weekly pip updates for v2

- apps/locales/en_US/LC_MESSAGES/django.po
- apps/locales/zh_CN/LC_MESSAGES/django.po
- apps/locales/zh_Hant/LC_MESSAGES/django.po
> chore: add some i18n code

- pyproject.toml
dependencies: Upgrade Django to 4.2.20
> dependencies: Upgrade Django to 4.2.20

- ui/src/workflow/nodes/mcp-node/index.vue
> perf: The style of MCP nodes when there is no data

- apps/setting/models_provider/constants/model_provider_constants.py
- apps/setting/models_provider/impl/regolo_model_provider/__init__.py
- apps/setting/models_provider/impl/regolo_model_provider/credential/embedding.py
- apps/setting/models_provider/impl/regolo_model_provider/credential/image.py
- apps/setting/models_provider/impl/regolo_model_provider/credential/llm.py
- apps/setting/models_provider/impl/regolo_model_provider/credential/tti.py
- apps/setting/models_provider/impl/regolo_model_provider/icon/regolo_icon_svg
- apps/setting/models_provider/impl/regolo_model_provider/model/embedding.py
- apps/setting/models_provider/impl/regolo_model_provider/model/image.py
- apps/setting/models_provider/impl/regolo_model_provider/model/llm.py
- apps/setting/models_provider/impl/regolo_model_provider/model/tti.py
- apps/setting/models_provider/impl/regolo_model_provider/regolo_model_provider.py
Adds [regolo.ai](https://regolo.ai/) as model provider.
Added another provider
> feat(provider): added regolo.ai

- apps/application/sql/export_application_chat.sql
fix: dialogue log export error
> fix: dialogue log export error

- installer/Dockerfile
build: Sensitive directory permissions
> build: Sensitive directory permissions

- apps/application/urls.py
- apps/application/views/application.py
- apps/application/views/application_access_token.py
- apps/application/views/application_api_key.py
- apps/application/views/application_chat.py
- apps/application/views/application_chat_record.py
- apps/application/views/application_stats.py
- apps/application/views/application_version.py
- apps/common/auth/authentication.py
- apps/common/auth/handle/impl/user_token.py
- ui/src/api/user/resource-authorization.ts
- ui/src/views/resource-authorization/index.vue
feat: application add workspace manage role
> feat: application add workspace manage role

- ui/src/api/system/role.ts
- ui/src/api/type/role.ts
- ui/src/locales/lang/zh-CN/views/role.ts
- ui/src/views/role/component/CreateOrUpdateRoleDialog.vue
- ui/src/views/role/component/Member.vue
- ui/src/views/role/component/PermissionConfiguration.vue
- ui/src/views/role/index.vue
> feat: role member

- ui/src/api/application/application.ts
- ui/src/stores/modules/user.ts
- ui/src/views/application-overview/index.vue
> feat: application ui overview

- apps/system_manage/sql/get_user_resource_permission.sql
> fix: resource permission auth

- apps/application/serializers/application.py
- apps/application/serializers/application_chat_record.py
- apps/application/urls.py
- apps/application/views/application_chat_record.py
- apps/chat/serializers/chat.py
- ui/src/api/application/application.ts
- ui/src/api/application/chat-log.ts
- ui/src/api/model/model.ts
- ui/src/components/ai-chat/index.vue
- ui/src/components/model-select/index.vue
- ui/src/request/index.ts
- ui/src/stores/modules/application.ts
- ui/src/views/application/ApplicationSetting.vue
- ui/src/views/application/component/AIModeParamSettingDialog.vue
- ui/src/views/application/component/ParamSettingDialog.vue
feat: simple application debug chat
> feat: simple application debug chat

- apps/maxkb/conf.py
> feat local model config

- ui/src/api/application/application-key.ts
- ui/src/api/application/application.ts
- ui/src/api/chat/chat.ts
- ui/src/request/chat/Result.ts
- ui/src/request/chat/index.ts
- ui/src/stores/modules/user.ts
- ui/src/views/chat/index.vue
- ui/vite.config.ts
> feat: workspace to store

- apps/common/auth/authentication.py
> fix: role authentication

- apps/common/log/log.py
> feat: operate log workspace

- ui/src/router/modules/application-detail.ts
- ui/src/router/routes.ts
- ui/src/stores/modules/user.ts
- ui/src/utils/permission/data.ts
- ui/src/utils/permission/index.ts
- ui/src/utils/permission/type.ts
- ui/src/views/Permission.vue
> feat: ui hasPermission

- ui/src/components/generate-related-shared-dialog/index.vue
> fix(knowledge): bug fix

- apps/chat/urls.py
- apps/chat/views/chat.py
> feat: chat captcha

- ui/src/router/chat/index.ts
> fix: chat route

- apps/common/auth/common.py
> fix: chat user token

- ui/src/api/chat/chat.ts
- ui/src/request/chat/index.ts
- ui/src/router/chat/index.ts
- ui/src/stores/modules/chat-user.ts
- ui/src/views/chat/user-login/index.vue
> feat: chat auth

- apps/common/auth/handle/impl/user_token.py
- apps/users/serializers/user.py
- ui/src/router/modules/1application.ts
- ui/src/router/modules/2knowledge.ts
- ui/src/stores/modules/user.ts
> fix: ui 404

- apps/maxkb/conf.py
> fix: redis db

- apps/common/auth/handle/impl/user_token.py
- apps/users/views/user.py
- ui/src/router/modules/system.ts
> fix: permission

- apps/common/auth/handle/impl/user_token.py
> fix: permission role

- apps/models_provider/views/model.py
> fix: model permission

- apps/setting/models_provider/impl/xinference_model_provider/model/reranker.py
> fix: Reorganize the model cache

- apps/common/auth/handle/impl/chat_anonymous_user_token.py
- ui/src/api/chat/chat.ts
- ui/src/stores/modules/chat-user.ts
- ui/src/views/application-overview/xpack-component/XPackLimitDrawer.vue
- ui/src/views/chat/auth/component/password.vue
- ui/src/views/chat/user-login/auth/password/index.vue
- ui/src/views/chat/user-login/index.vue
> feat: chat password auth

- apps/users/serializers/user.py
- ui/src/api/type/user.ts
- ui/src/layout/layout-header/workspace-dropdown/index.vue
- ui/src/stores/modules/user.ts
> fix: workspace

- apps/system_manage/serializers/user_resource_permission.py
> fix: resource auth

- ui/src/views/knowledge/index.vue
fix: Knowledge create permission
> fix: Knowledge create permission

- apps/common/constants/permission_constants.py
fix: resource permission group list
> fix: resource permission group list

- ui/src/router/modules/1application.ts
- ui/src/views/application-overview/index.vue
- ui/src/views/application/ApplicationSetting.vue
- ui/src/views/application/index.vue
- ui/src/views/chat-log/index.vue
- ui/src/views/document/index.vue
- ui/src/views/knowledge/index.vue
- ui/src/views/model/component/ModelCard.vue
- ui/src/views/model/index.vue
- ui/src/views/problem/index.vue
- ui/src/views/shared/model-shared/component/ModelCard.vue
- ui/src/views/system-chat-user/user-manage/index.vue
- ui/src/views/tool/ToolFormDrawer.vue
- ui/src/views/tool/index.vue
> fix: Common user permission

- ui/src/views/resource-authorization/index.vue
> fix(authorization): knowledge

- apps/application/views/application.py
- apps/application/views/application_access_token.py
- apps/application/views/application_api_key.py
- apps/application/views/application_chat.py
- apps/application/views/application_chat_record.py
- apps/application/views/application_stats.py
- apps/application/views/application_version.py
- apps/common/constants/permission_constants.py
- ui/vite.config.ts
> fix: Complete application permissions

- apps/application/serializers/application.py
- apps/application/urls.py
- ui/src/api/application/application.ts
- ui/src/views/application-workflow/index.vue
> feat: application publish

- apps/application/serializers/application.py
- apps/application/sql/list_application_user_ee.sql
> fix: application query

- ui/src/permission/index.ts
- ui/src/permission/knowledge/index.ts
- ui/src/permission/knowledge/system-manage.ts
- ui/src/permission/knowledge/system-share.ts
- ui/src/permission/knowledge/workspace.ts
- ui/src/permission/model/index.ts
- ui/src/permission/model/system-manage.ts
- ui/src/permission/model/system-share.ts
- ui/src/permission/model/workspace.ts
- ui/src/permission/tool/index.ts
- ui/src/permission/tool/system-manage.ts
- ui/src/permission/tool/system-share.ts
- ui/src/permission/tool/workspace.ts
- ui/src/views/tool/index.vue
> feat: permission split

- apps/knowledge/serializers/knowledge.py
> fix: knowledge list

- ui/src/permission/tool/workspace.ts
- ui/src/router/modules/document.ts
- ui/src/views/application/index.vue
- ui/src/views/document/index.vue
- ui/src/views/knowledge/KnowledgeSetting.vue
- ui/src/views/knowledge/index.vue
- ui/src/views/problem/index.vue
- ui/src/views/tool/ToolFormDrawer.vue
- ui/src/views/tool/index.vue
> feat: Tool permission

- apps/system_manage/serializers/user_resource_permission.py
> fix: resource permission

- apps/application/serializers/application.py
- apps/knowledge/serializers/knowledge.py
fix: application knowledge list
> fix: application knowledge list

- ui/src/permission/knowledge/system-share.ts
- ui/src/permission/knowledge/workspace.ts
- ui/src/views/problem/index.vue
feat: Knowledge problem permission
> feat: Knowledge problem permission

- ui/src/router/index.ts
- ui/src/router/routes.ts
> feat: route permission

- ui/src/permission/knowledge/system-manage.ts
- ui/src/permission/knowledge/system-share.ts
- ui/src/permission/knowledge/workspace.ts
- ui/src/router/modules/system.ts
feat: Shared knowledge permission
> feat: Shared knowledge permission

- ui/src/views/paragraph/component/ParagraphCard.vue
> fix(paragraph): bug fix

- ui/src/router/modules/application.ts
- ui/src/router/modules/knowledge.ts
- ui/src/router/modules/model.ts
- ui/src/router/modules/tool.ts
> fix: route

- apps/models_provider/serializers/model_serializer.py
> fix: model share

- ui/src/permission/knowledge/workspace.ts
- ui/src/permission/model/workspace.ts
- ui/src/permission/tool/workspace.ts
fix: Shared resource permission
> fix: Shared resource permission

- ui/src/views/system-chat-user/authentication/component/CAS.vue
- ui/src/views/system-chat-user/group/index.vue
feat: System chat user group permission
> feat: System chat user group permission

- apps/common/constants/permission_constants.py
feat: Knowledge chat user permission
> feat: Knowledge chat user permission

- apps/common/auth/handle/impl/user_token.py
- apps/common/constants/permission_constants.py
- ui/src/utils/permission/data.ts
> feat: add extends role

- ui/src/layout/layout-header/avatar/index.vue
- ui/src/router/modules/system.ts
> fix: Avatar permission

- apps/application/chat_pipeline/step/search_dataset_step/impl/base_search_dataset_step.py
- apps/application/flow/step_node/search_knowledge_node/impl/base_search_knowledge_node.py
feat: Knowledge base search based on authorized users
> feat: Knowledge base search based on authorized users

- apps/application/chat_pipeline/step/search_dataset_step/i_search_dataset_step.py
- apps/application/chat_pipeline/step/search_dataset_step/impl/base_search_dataset_step.py
- apps/chat/serializers/chat.py
> fix: search knowledge

- apps/application/views/application_chat.py
> fix: Debugging dialogue error

- ui/src/views/application-overview/index.vue
> fix: chat url

- apps/common/constants/permission_constants.py
- apps/knowledge/views/knowledge.py
- ui/src/router/modules/document.ts
- ui/src/router/modules/system.ts
- ui/src/views/chat-user/index.vue
- ui/src/views/tool/ToolFormDrawer.vue
> feat: hit test permission

- ui/src/api/system-shared/knowledge-chat-user.ts
feat: Shared knowledge chat user api
> feat: Shared knowledge chat user api

- apps/common/constants/permission_constants.py
> fix: Application permission

- apps/common/auth/handle/impl/user_token.py
- apps/common/constants/permission_constants.py
> fix: role user permission

- apps/application/serializers/application.py
> fix: Related knowledge base

- apps/application/migrations/0001_initial.py
- apps/application/serializers/application.py
- ui/src/layout/components/breadcrumb/index.vue
- ui/src/utils/common.ts
- ui/src/views/application-overview/index.vue
- ui/src/views/tool/component/ToolListContainer.vue
> fix: URL 404

- apps/common/auth/handle/impl/user_token.py
fix: Community user permissions
> fix: Community user permissions

- ui/src/router/modules/application-detail.ts
- ui/src/router/modules/knowledge.ts
- ui/src/router/modules/model.ts
- ui/src/router/modules/tool.ts
fix: Application community permission
> fix: Application community permission

- apps/common/auth/authentication.py
- apps/common/constants/permission_constants.py
- apps/tools/views/tool.py
fix: System common user permission by role
> fix: System common user permission by role

- ui/src/router/modules/document.ts
> Document enter permission

- apps/application/flow/step_node/application_node/impl/base_application_node.py
- apps/chat/serializers/chat.py
> feat: application node

- apps/locales/zh_CN/LC_MESSAGES/django.po
- ui/src/locales/lang/en-US/theme.ts
- ui/src/locales/lang/zh-CN/theme.ts
- ui/src/locales/lang/zh-Hant/theme.ts
> fix: Locales

- apps/application/chat_pipeline/step/search_dataset_step/impl/base_search_dataset_step.py
- apps/application/flow/step_node/document_extract_node/impl/base_document_extract_node.py
- apps/chat/views/chat.py
- apps/knowledge/models/knowledge.py
- apps/maxkb/urls.py
- ui/src/api/application/application.ts
- ui/src/api/chat/chat.ts
- ui/src/components/ai-chat/component/chat-input-operate/index.vue
- ui/src/views/application/component/CreateApplicationDialog.vue
> feat: application upload file

- apps/models_provider/views/model.py
fix: Model list permission while create knowledge or application
> fix: Model list permission while create knowledge or application

- apps/tools/views/tool.py
- ui/src/views/tool/toolStore/ToolStoreDialog.vue
> fix: Add tool from tool store

- apps/chat/serializers/chat.py
fix: Simple application without dialogue logs
> fix: Simple application without dialogue logs

- ui/src/views/tool/ToolFormDrawer.vue
- ui/src/views/tool/component/ToolListContainer.vue
fix: Update visibility handling after user profile retrieval and enhance permission checks in dropdown items
> fix: Update visibility handling after user profile retrieval and enhance permission checks in dropdown items

- apps/oss/serializers/file.py
- ui/src/components/ai-chat/component/knowledge-source-component/index.vue
- ui/src/utils/common.ts
> fix: PDF Preview

- apps/system_manage/serializers/user_resource_permission.py
fix: Resource automatic authorization type error
> fix: Resource automatic authorization type error

- apps/common/auth/handle/impl/user_token.py
fix: Resource authorization dirty data
> fix: Resource authorization dirty data

- apps/common/auth/handle/impl/chat_anonymous_user_token.py
> fix: Password authentication

- apps/knowledge/views/paragraph.py
fix: knowledge document paragraph read permission
> fix: knowledge document paragraph read permission

- apps/application/flow/step_node/application_node/i_application_node.py
- apps/chat/serializers/chat.py
fix: The sub application cannot have a conversation
> fix: The sub application cannot have a conversation

- apps/application/flow/step_node/application_node/impl/base_application_node.py
fix: The sub application cannot use the current node
> fix: The sub application cannot use the current node

- apps/system_manage/serializers/user_resource_permission.py
fix: The type of resource authorization is incorrect
> fix: The type of resource authorization is incorrect

- apps/application/serializers/application.py
- apps/application/views/application.py
- apps/common/utils/common.py
fix: Application import and export
> fix: Application import and export

- apps/application/flow/step_node/mcp_node/impl/base_mcp_node.py
fix: MCP node execution failed
> fix: MCP node execution failed

- ui/src/views/model/component/CreateModelDialog.vue
fix: Button permission while creating model
> fix: Button permission while creating model

- ui/src/views/system/resource-authorization/index.vue
feat: Remove the community version role button display
> feat: Remove the community version role button display

- ui/src/components/model-select/index.vue
- ui/src/views/application/component/AIModeParamSettingDialog.vue
fix: Model permission while setting knowledge or application
> fix: Model permission while setting knowledge or application

- apps/locales/en_US/LC_MESSAGES/django.po
- apps/locales/zh_CN/LC_MESSAGES/django.po
- apps/locales/zh_Hant/LC_MESSAGES/django.po
> feat: Locales

- ui/src/api/shared-workspace.ts
- ui/src/router/modules/document.ts
- ui/src/views/chat-user/index.vue
- ui/src/views/document/index.vue
feat: Workspace shared knowledge permission
> feat: Workspace shared knowledge permission

- ui/src/layout/layout-header/avatar/index.vue
fix: Role tag visibility of community
> fix: Role tag visibility of community

- apps/common/cache_data/application_access_token_cache.py
- apps/common/middleware/__init__.py
- apps/common/middleware/chat_headers_middleware.py
- apps/common/middleware/cross_domain_middleware.py
- apps/common/middleware/gzip.py
- apps/maxkb/settings/base.py
feat: Apikey call supports cross domain and application whitelist
> feat: Apikey call supports cross domain and application whitelist

- ui/src/router/chat/index.ts
- ui/src/views/chat/user-login/index.vue
fix: After entering the password for the public access link, the parameters carried by the URL address are missing
> fix: After entering the password for the public access link, the parameters carried by the URL address are missing

- ui/src/views/tool/component/ToolListContainer.vue
> fix: Imported tool create

- ui/src/views/chat-user/index.vue
fix: Resource chat user of common user
> fix: Resource chat user of common user

- apps/maxkb/urls.py
> fix: Chat ui prefix

- apps/application/serializers/application_chat_record.py
- apps/chat/api/chat_authentication_api.py
- apps/chat/serializers/chat.py
fix: The conversation user is not authorized to use
> fix: The conversation user is not authorized to use

- apps/system_manage/models/__init__.py
- apps/system_manage/models/chat_user.py
> refactor: Chat user model

- apps/chat/serializers/chat_authentication.py
- apps/common/auth/handle/impl/chat_anonymous_user_token.py
> fix: chat user

- apps/system_manage/models/chat_user.py
> fix: Chat user model

- apps/chat/serializers/chat_authentication.py
fix: Simple application dialogue not handled as published
> fix: Simple application dialogue not handled as published

- apps/chat/serializers/chat_record.py
- apps/chat/urls.py
- apps/chat/views/chat_record.py
Historical conversation batch delete
> Historical conversation batch delete

- ui/src/api/chat/chat.ts
- ui/src/views/chat/component/HistoryPanel.vue
- ui/src/views/chat/pc/index.vue
> feat: Clear chat log

- ui/src/views/application/index.vue
> fix: Application import

- ui/src/views/problem/index.vue
fix: Workspace share knowledge problem
> fix: Workspace share knowledge problem

- ui/src/views/hit-test/index.vue
> fix: Hit test share

- apps/knowledge/views/paragraph.py
- apps/knowledge/views/problem.py
fix: Knowledge document problem related permission
> fix: Knowledge document problem related permission

- apps/common/job/__init__.py
- apps/common/job/client_access_num_job.py
> feat: Access num reset job

- ui/src/router/chat/index.ts
fix: Dialogue interface parameters are missing
> fix: Dialogue interface parameters are missing

- apps/application/flow/step_node/start_node/impl/base_start_node.py
fix: User input parameters do not take effect
> fix: User input parameters do not take effect

- apps/knowledge/views/paragraph.py
fix: Knowledge document paragraph permission
> fix: Knowledge document paragraph permission
