apps/dataset/serializers/dataset_serializers.py

fix: 在线知识库全量同步无法使用 #51

---

apps/dataset/serializers/paragraph_serializers.py
ui/src/views/paragraph/component/ProblemComponent.vue

fix: 添加分段时无法关联问题 #53

---

.gitignore

deps: poetry.lock should be commit
poetry.lock should be commit to repo, If not commit why not using requirements.txt.
https://python-poetry.org/docs/basic-usage/#committing-your-poetrylock-file-to-version-control
- [ x ] Made sure tests are passing and test coverage is added if needed.
- [ x ] Made sure commit message follow the rule of [Conventional Commits specification](https://www.conventionalcommits.org/).
- [ x ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed.

perf: Update .gitignore poetry.lock should be commit

---

ui/src/components/ai-chat/index.vue

fix: 【应用】问答页面用户提问时，只输入空格不能发送（#108）

---

ui/src/components/ai-chat/index.vue

fix: 【应用】问答页面在回答中...时，点击停止回答不生效 #109

---

ui/src/layout/components/top-bar/index.vue

perf: 导航栏增加用户手册、项目地址、论坛求助入口(#83)

---

apps/application/template/embed.js
ui/index.html
ui/src/layout/components/top-bar/index.vue
ui/src/views/chat/index.vue

perf: 部分线条样式优化(#105)

---

ui/package.json
ui/src/theme/index.ts

原来的依赖包中，缺少一个库"@ctrl/tinycolor"，运行开发环境会报错，而如果直接通过 `npm install @ctrl/tinycolor` 安装这个库的话，会发现安装的是 4.1.0 版，但代码不能兼容。
- 在 package.json 文件中增加 "@ctrl/tinycolor" 依赖
- 在 index.ts 文件中，修改引入 TinyColor 的方式，原来是一个函数，现在是一个类，同时也修改调用的位置

修复前端缺少 @ctrl/tinycolor 依赖库,以及不兼容4.1.x版本的问题

---

apps/common/handle/base_split_handle.py
apps/common/handle/impl/doc_split_handle.py
apps/common/handle/impl/pdf_split_handle.py
apps/common/handle/impl/text_split_handle.py
apps/dataset/serializers/document_serializers.py

feat: 【知识库】docx支持图片上传 #69

---

ui/src/views/template/component/CreateModelDialog.vue
ui/src/views/template/component/EditModel.vue

perf: 优化模型管理基础模型提示

---

apps/application/serializers/chat_message_serializers.py
apps/application/serializers/chat_serializers.py
apps/common/util/rsa_util.py
apps/setting/serializers/provider_serializers.py

fix: 模型添加长字符的加密解密方式

---

apps/application/chat_pipeline/step/reset_problem_step/impl/base_reset_problem_step.py
apps/application/serializers/application_serializers.py

fix: 应用，不选择模型，开启问题优化和多轮对话就会出现错误 #326

---

apps/common/event/listener_manage.py
apps/dataset/serializers/document_serializers.py
apps/dataset/serializers/paragraph_serializers.py
apps/dataset/urls.py
apps/dataset/views/paragraph.py
apps/embedding/vector/base_vector.py
apps/embedding/vector/pg_vector.py
ui/src/api/paragraph.ts
ui/src/styles/app.scss
ui/src/views/document/index.vue
ui/src/views/paragraph/component/SelectDocumentDialog.vue
ui/src/views/paragraph/index.vue
ui/src/views/problem/component/RelateProblemDialog.vue

Pr@main@document batch delete

---

ui/src/views/dataset/CreateDataset.vue
ui/src/views/dataset/component/EditParagraphDialog.vue
ui/src/views/dataset/component/ParagraphPreview.vue
ui/src/views/dataset/step/StepSecond.vue

feat: 导入时支持设置分段标题为关联问题(#177)

---

apps/common/util/ts_vecto_util.py

fix: 修复分词超过数据库最大限制

---

ui/src/views/dataset/component/ParagraphList.vue
ui/src/views/dataset/component/ParagraphPreview.vue

perf: 优化文档分段前端懒加载

---

ui/src/views/document/index.vue
ui/src/views/log/index.vue
ui/src/views/problem/index.vue

fix: 文档问题列表多选框点击范围优(#424)

---

apps/setting/models_provider/impl/ollama_model_provider/ollama_model_provider.py

fix: 修复Ollama模型中没有已下载的模型时，在 MaxKB 添加 Ollama模型报错。#437

---

apps/application/chat_pipeline/step/chat_step/impl/base_chat_step.py

fix: 提问后模型返回异常信息时也要记录到对话日志中 #416

---

ui/package.json
ui/src/views/chat/pc/index.vue

与 #471 有关，但未实现PDF导出
使用marked和file-saver实现Markdown文件和HTML文件导出。
在实现PDF导出时，发现中文和特殊字符在导出PDF时会出现乱码问题。如果使用html2canvas后再导出PDF，则会导致文本无法复制。对于面向程序开发等场景的知识库来说，无法复制文本/代码是一个非常糟糕的问题，因此决定暂时不放出导出PDF的方法。
- [ Y ] Made sure tests are passing and test coverage is added if needed.
- [ Y ] Made sure commit message follow the rule of [Conventional Commits specification](https://www.conventionalcommits.org/).
- [ Y ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed.

feat: 支持导出单次对话的全部提问记录为Markdown文件或HTML文件

---

apps/common/handle/impl/html_split_handle.py
apps/dataset/serializers/document_serializers.py
ui/src/utils/utils.ts
ui/src/views/dataset/component/UploadComponent.vue

feat: 支持上传html格式的文档 #364

---

ui/src/locales/lang/en_US/views/application-overview.ts
ui/src/locales/lang/en_US/views/index.ts
ui/src/locales/lang/zh_CN/views/404.ts
ui/src/locales/lang/zh_CN/views/application-overview.ts
ui/src/locales/lang/zh_CN/views/index.ts
ui/src/views/application-overview/component/APIKeyDialog.vue
ui/src/views/application-overview/component/EditAvatarDialog.vue
ui/src/views/application-overview/component/EmbedDialog.vue
ui/src/views/application-overview/component/LimitDialog.vue
ui/src/views/application-overview/component/SettingAPIKeyDialog.vue
ui/src/views/application-overview/component/StatisticsCharts.vue
ui/src/views/application-overview/index.vue

- 进行了 'views/application-overview' 页面的国际化工作
- 使用 GPT-4 Turbo 进行翻译，确保准确性和文化相关性
- 修复了404页面中一处错误
- 国际化按钮默认已隐藏
- Made sure tests are passing and test coverage is added if needed.
- Made sure commit message follow the rule of [Conventional Commits specification](https://www.conventionalcommits.org/).
- Considered the docs impact and opened a new docs issue or PR with docs changes if needed.

feat：国际化页面views/application-overview

---

ui/src/components/ai-chat/index.vue
ui/src/views/chat/embed/index.vue
ui/src/views/chat/pc/index.vue

perf: 对话文本输入框自适应调整(#616)

---

apps/application/serializers/chat_message_serializers.py
ui/src/views/log/component/EditContentDialog.vue

feat: 对话用户问题调整为10万字符 #628

---

ui/src/components/ai-chat/index.vue
ui/src/components/common-list/index.vue
ui/src/views/chat/embed/index.vue
ui/src/views/chat/pc/index.vue

feat:  历史记录增加删除功能优化

---

apps/common/util/ts_vecto_util.py

fix:知识库上传文档操作报异常，错误发生在 ts_vecto_util.py 文件的 replace_word 函数中：错误的原因是正则表达式模式在某个位置缺少一个右括号，使得子模式未完全结束。该提交修复了这个问题。
**MaxKB 版本**
v1.2.0
**问题描述**
[BUG]知识库上传文档操作报异常，错误发生在 ts_vecto_util.py 文件的 replace_word 函数中：错误的原因是正则表达式模式在某个位置缺少一个右括号，使得子模式未完全结束。
**重现步骤**
1.知识库，上传文档：<Oracle21C-database-pl-sql-language-reference.pdf>
[Oracle21C-database-pl-sql-language-reference.pdf](https://github.com/user-attachments/files/15984729/Oracle21C-database-pl-sql-language-reference.pdf)
2.界面和日志出现如下异常：
```shell
2024-06-26 13:25:09 [listener_manage ERROR] 向量化文档:323837a2-3360-11ef-aaed-0242ac120003出现错误missing ), unterminated subpattern at position 8Traceback (most recent call last):
File "/opt/maxkb/app/apps/common/event/listener_manage.py", line 141, in embedding_by_document …
```

fix:知识库上传文档操作报异常，错误的原因是正则表达式模式在某个位置缺少一个右括号，该提交修复了这个问题。

---

apps/dataset/serializers/common_serializers.py
apps/dataset/serializers/dataset_serializers.py
apps/dataset/serializers/document_serializers.py
apps/dataset/serializers/paragraph_serializers.py

fix: 修复【知识库】知识库上传 有关联问题的会阻塞

---

apps/application/views/application_views.py
apps/common/auth/authentication.py
apps/common/handle/handle_exception.py
apps/smartdoc/urls.py

- Applied automated fixes for the pylint warning `no-else-return`.
"Used in order to highlight an unnecessary block of code following an if containing a return statement. As such, it will warn when it encounters an else following a chain of ifs, all of them containing a return statement.. See [https://pylint.pycqa.org/en/latest/user_guide/messages/refactor/no-else-return.html](https://pylint.pycqa.org/en/latest/user_guide/messages/refactor/no-else-return.html)"
This pull request is part of a research project conducted by researchers from TU Delft, titled "PyWarnFixer: Using ML to Fix Pylint Warnings." The goal of this study is to investigate the perceptions and practices of code quality among developers in Python open-source projects and to develop a tool that uses AI to automatically fix …

Fix pylint warning `no-else-return`

---

ui/src/api/type/application.ts
ui/src/components/ai-chat/index.vue

fix: 修复【应用编排】客户端提问达到限制时，隐藏知识来源

---

apps/application/chat_pipeline/step/chat_step/impl/base_chat_step.py
apps/application/chat_pipeline/step/generate_human_message_step/impl/base_generate_human_message_step.py

fix: 修复大模型返回json时，解析出错 #656

---

apps/application/serializers/application_serializers.py

fix: 修复应用关联知识库取消关联未删除关联关系

---

ui/src/workflow/common/NodeCascader.vue

feat: 【应用编排】修复选择器滚动条问题

---

apps/application/flow/step_node/direct_reply_node/impl/base_reply_node.py

fix: 修复AI编排中，指定回复的内容，不能在任务流程中传递 #726

---

apps/application/flow/step_node/search_dataset_node/i_search_dataset_node.py
apps/application/serializers/application_serializers.py
apps/embedding/vector/pg_vector.py

fix: 修复【问答页面】- 当应用关联的知识库中含有禁用状态的文档时，问答时点击换个答案不会换一批命中分段 #759

---

ui/src/components/ai-chat/index.vue
ui/src/components/markdown/MdRenderer.vue

feat: 支持解析<quick_question>标签内容当做快捷问题解析#762

---

apps/application/chat_pipeline/step/search_dataset_step/impl/base_search_dataset_step.py
apps/application/flow/step_node/search_dataset_node/impl/base_search_dataset_node.py

fix: 修复知识库检索向量模型不一致时错误提示

---

apps/common/config/embedding_config.py
apps/setting/models_provider/base_model_provider.py
apps/setting/models_provider/impl/xf_model_provider/model/llm.py

fix: 修复讯飞星火模型多用户同时提问后，回答内容会错乱 #917

---

apps/application/flow/i_step_node.py
apps/application/flow/step_node/ai_chat_step_node/i_chat_node.py
apps/application/flow/step_node/ai_chat_step_node/impl/base_chat_node.py
apps/application/flow/step_node/direct_reply_node/i_reply_node.py
apps/application/flow/step_node/direct_reply_node/impl/base_reply_node.py
apps/application/flow/step_node/question_node/i_question_node.py
apps/application/flow/step_node/question_node/impl/base_question_node.py
apps/application/flow/tools.py
apps/application/flow/workflow_manage.py
ui/src/workflow/common/data.ts
ui/src/workflow/nodes/ai-chat-node/index.vue
ui/src/workflow/nodes/question-node/index.vue
ui/src/workflow/nodes/reply-node/index.vue

Pr@main@feat is return

---

apps/common/event/listener_manage.py
apps/embedding/vector/base_vector.py
apps/embedding/vector/pg_vector.py

refactor: 优化向量化相关代码

---

apps/dataset/serializers/image_serializers.py
apps/smartdoc/settings/base.py

fix: 修改图片上传像素校验位200亿

---

installer/Dockerfile

ci: 修改默认pip安装包路径

---

apps/setting/models_provider/impl/ollama_model_provider/model/llm.py
apps/setting/models_provider/impl/openai_model_provider/model/llm.py
apps/setting/models_provider/impl/qwen_model_provider/credential/llm.py
apps/setting/models_provider/impl/qwen_model_provider/model/llm.py
apps/setting/models_provider/impl/tencent_model_provider/model/llm.py
apps/setting/models_provider/impl/volcanic_engine_model_provider/model/llm.py

refactor: update model params

---

apps/common/handle/impl/pdf_split_handle.py

chore: 解析错误是输出错误原因

---

ui/src/api/function-lib.ts
ui/src/views/application/component/CopyApplicationDialog.vue
ui/src/views/application/component/CreateApplicationDialog.vue
ui/src/views/application/index.vue
ui/src/views/function-lib/index.vue

feat: 增加函数库删除功能

---

apps/dataset/serializers/document_serializers.py

fix: 修复知识库迁移报错的缺陷  --bug=1045659 --user=王孝刚 【知识库】通用知识库，文档迁移报错了 https://www.tapd.cn/57709429/s/1568795

fix: 修复知识库迁移报错的缺陷

---

apps/common/util/split_model.py

fix: 修复上传PDF文件智能分段时提示 分段内容不能超过102400个字符 #998

fix: 修复上传PDF文件智能分段时提示 分段内容不能超过102400个字符 #998

---

ui/src/views/template/component/ModelCard.vue

fix: 修复【系统管理】模型设置，模型名称省略显示的时候，模型图标会消失

fix: 修复【系统管理】模型设置，模型名称省略显示的时候，模型图标会消失

---

ui/src/views/template/component/CreateModelDialog.vue

fix: 修复创建模型，不显示参数的缺陷  --bug=1045668 --user=王孝刚 【系统管理】模型设置，添加模型时先输入基础模型再选择模型类型，不限时apikey等输入框 https://www.tapd.cn/57709429/s/1569266

fix: 修复创建模型，不显示参数的缺陷

---

apps/application/flow/step_node/ai_chat_step_node/i_chat_node.py
apps/application/flow/step_node/ai_chat_step_node/impl/base_chat_node.py
apps/application/flow/step_node/question_node/i_question_node.py
apps/application/flow/step_node/question_node/impl/base_question_node.py

fix: 修复工作流编排历史数据模型参数必填

---

apps/setting/models_provider/impl/volcanic_engine_model_provider/model/stt.py
apps/setting/models_provider/impl/volcanic_engine_model_provider/model/tts.py
apps/setting/models_provider/impl/xf_model_provider/model/stt.py
apps/setting/models_provider/impl/xf_model_provider/model/tts.py

fix: 修复wss链接的证书问题

---

apps/common/handle/impl/pdf_split_handle.py

refactor: 格式规范的pdf通过目录来分段

---

apps/application/serializers/application_serializers.py
apps/application/urls.py
apps/application/views/application_views.py
ui/package.json
ui/src/api/application.ts
ui/src/components/ai-chat/index.vue
ui/src/request/index.ts

refactor: 调试语音输入和语音播放

---

apps/application/flow/workflow_manage.py
apps/application/serializers/application_serializers.py
apps/application/serializers/chat_message_serializers.py
apps/application/views/chat_views.py
ui/src/components/ai-chat/index.vue
ui/src/components/dynamics-form/items/DatePicker.vue
ui/src/workflow/nodes/base-node/component/FieldFormDialog.vue
ui/src/workflow/nodes/base-node/index.vue
ui/src/workflow/nodes/start-node/index.vue

feat: 支持用户输入变量  --story=1016155 --user=刘瑞斌 【应用编排】-支持设置用户输入变量 https://www.tapd.cn/57709429/s/1576480

feat: 支持用户输入变量

---

ui/src/components/markdown/HtmlRander.vue
ui/src/components/markdown/MdRenderer.vue

feat: 支持通过html_rander标签 支持script执行

feat: 支持通过html_rander标签 支持script执行

---

ui/src/components/markdown/EchartsRander.vue
ui/src/components/markdown/MdRenderer.vue

feat: 支持通过echarts_rander标签 渲染图表

feat: 支持通过echarts_rander标签 渲染图表

---

ui/src/views/application/component/AccessSettingDrawer.vue

fix: 解决前端ts类型错误

---

apps/dataset/urls.py
apps/dataset/views/document.py
apps/setting/models_provider/impl/aws_bedrock_model_provider/credential/llm.py
apps/setting/models_provider/impl/azure_model_provider/credential/llm.py
apps/setting/models_provider/impl/deepseek_model_provider/credential/llm.py
apps/setting/models_provider/impl/gemini_model_provider/credential/llm.py
apps/setting/models_provider/impl/kimi_model_provider/credential/llm.py
apps/setting/models_provider/impl/ollama_model_provider/credential/llm.py
apps/setting/models_provider/impl/openai_model_provider/credential/llm.py
apps/setting/models_provider/impl/qwen_model_provider/credential/llm.py
apps/setting/models_provider/impl/vllm_model_provider/credential/llm.py
apps/setting/models_provider/impl/volcanic_engine_model_provider/credential/llm.py
apps/setting/models_provider/impl/wenxin_model_provider/credential/llm.py
apps/setting/models_provider/impl/xf_model_provider/credential/llm.py
apps/setting/models_provider/impl/xinference_model_provider/credential/llm.py
apps/setting/models_provider/impl/zhipu_model_provider/credential/llm.py
ui/src/api/document.ts
ui/src/views/application/component/AccessSettingDrawer.vue
ui/src/views/document/index.vue

--bug=1046202 --user=王孝刚 【github#1144】【应用】参数设置，输出最大tokens描述错误 https://www.tapd.cn/57709429/s/1579168

fix: 修复tokens描述错误的缺陷

---

ui/src/styles/app.scss
ui/src/views/application-overview/index.vue
ui/src/views/application/ApplicationSetting.vue

feat: 简易应用支持设置应用Logo

---

ui/src/workflow/nodes/base-node/index.vue

fix: 修复语音播放没选中浏览器播放为默认值的问题  --bug=1046703 --user=刘瑞斌 【应用编排】应用编排开启语音播放，默认应该选中浏览器播放 https://www.tapd.cn/57709429/s/1580874

fix: 修复语音播放没选中浏览器播放为默认值的问题

---

ui/src/views/application/ApplicationSetting.vue
ui/src/workflow/nodes/base-node/index.vue

refactor: 增加应用不选择语音模型报错提示  --bug=1046729 --user=刘瑞斌 【应用】应用语音播放选择模型播放后，不选择具体的模型，点击播放按钮没有反应 https://www.tapd.cn/57709429/s/1581681

refactor: 增加应用不选择语音模型报错提示

---

ui/src/components/ai-chat/index.vue

fix: 修复接口传入类型参数没有输入时，历史会话重新生成没有拦截的问题

fix: 修复接口传入类型参数没有输入时，历史会话重新生成没有拦截的问题

---

apps/common/event/listener_manage.py
apps/dataset/serializers/problem_serializers.py
apps/dataset/swagger_api/problem_api.py
apps/dataset/views/problem.py
apps/embedding/task/embedding.py
apps/embedding/vector/base_vector.py
ui/src/api/problem.ts
ui/src/views/problem/component/RelateProblemDialog.vue
ui/src/views/problem/index.vue

feat: 批量关联问题

---

ui/src/components/ai-chat/OperationButton.vue

fix: 处理调试时获取不到appid的问题

---

apps/function_lib/serializers/function_lib_serializer.py

fix: 修复【应用编排】添加不是自己创建的公用函数失败

---

apps/application/serializers/application_serializers.py

fix: 修复【应用】简单应用设置历史聊天记录，输入小数或者超大的数字，提示信息错误

fix: 修复【应用】简单应用设置历史聊天记录，输入小数或者超大的数字，提示信息错误

---

ui/src/components/ai-chat/index.vue

fix: 修复接口传入类型的参数校验必填项的问题  --bug=1046919 --user=刘瑞斌 【应用编排】接口传参类型的全局变量，设置了非必填后提问还是会提示需要填写 https://www.tapd.cn/57709429/s/1583325

fix: 修复接口传入类型的参数校验必填项的问题

---

apps/setting/serializers/provider_serializers.py

fix: 修复被关联的语音模型可以直接删除的问题  --bug=1046965 --user=刘瑞斌 【模型管理】OpenAI语音输入模型在简单应用中使用，模型管理中还可删除 https://www.tapd.cn/57709429/s/1583615

fix: 修复被关联的语音模型可以直接删除的问题

---

apps/application/flow/step_node/reranker_node/impl/base_reranker_node.py
apps/setting/models_provider/impl/xinference_model_provider/model/reranker.py

fix: 修复【应用编排】多路召回设置了引用分段5个，但是实际还是引用了3个

fix: 修复【应用编排】多路召回设置了引用分段5个，但是实际还是引用了3个

---

ui/src/components/ai-chat/LogOperationButton.vue
ui/src/components/ai-chat/OperationButton.vue

fix: 修复返回为空的文本不能播放默认提示的问题  --bug=1047018 --user=刘瑞斌 【应用】应用对话没有输出内容时，点击播放按钮console有报错 https://www.tapd.cn/57709429/s/1584399

fix: 修复返回为空的文本不能播放默认提示的问题

---

apps/common/handle/impl/pdf_split_handle.py

fix: 处理不规范的pdf中前言部分没在目录中标识出来，导致不能正常识别的问题

fix: 处理不规范的pdf中前言部分没在目录中标识出来，导致不能正常识别的问题

---

ui/src/workflow/common/NodeContainer.vue

fix: 修复【应用编排】判断器点击右侧+添加组件后，连线有点长，建议调整一下组件距离

fix: 修复【应用编排】判断器点击右侧+添加组件后，连线有点长，建议调整一下组件距离

---

ui/src/workflow/nodes/base-node/index.vue

fix: 修复前端obj为null的时候导致页面卡顿的问题

---

apps/dataset/serializers/dataset_serializers.py
apps/dataset/serializers/document_serializers.py
ui/src/api/dataset.ts
ui/src/api/document.ts

fix: 修复段落过长导出知识库报错

---

apps/setting/models_provider/impl/xinference_model_provider/credential/llm.py
apps/setting/models_provider/impl/xinference_model_provider/xinference_model_provider.py

当XInference供应商模型开启认证后，添加模型时的获取模型列表接口未传递 Authorization 导致模型添加失败。页面报 “API 域名无效” 错误。该 PR 修复该问题。
如果添加模型时设置了API KEY，在调用 XInference 接口时传递该参数。
不涉及。

fix: 修复 XInference 供应商加载模型时的未认证导致 API 域名无效的问题

---

ui/src/components/ai-chat/index.vue

chore: 取消录音时控制台的日志

---

apps/application/serializers/application_serializers.py
ui/src/api/application.ts
ui/src/locales/lang/en_US/views/application-overview.ts
ui/src/locales/lang/zh_CN/views/application-overview.ts
ui/src/stores/modules/application.ts
ui/src/views/application-overview/component/LimitDialog.vue
ui/src/views/chat/embed/index.vue
ui/src/views/chat/pc/index.vue

feat: 访问限制中新增身份验证设置

---

apps/application/flow/step_node/search_dataset_node/impl/base_search_dataset_node.py

feat: 高级编排检索结果字符串添加标题字段

---

apps/setting/models_provider/impl/wenxin_model_provider/credential/embedding.py
apps/setting/models_provider/impl/wenxin_model_provider/model/embedding.py
apps/setting/models_provider/impl/wenxin_model_provider/wenxin_model_provider.py

feat: 支持百度千帆向量模型

---

apps/setting/models_provider/impl/aws_bedrock_model_provider/aws_bedrock_model_provider.py
apps/setting/models_provider/impl/aws_bedrock_model_provider/credential/embedding.py
apps/setting/models_provider/impl/aws_bedrock_model_provider/model/embedding.py

feat: aws向量模型

---

apps/application/serializers/application_serializers.py
apps/application/urls.py
apps/application/views/application_views.py
apps/setting/models_provider/impl/aliyun_bai_lian_model_provider/model/tts.py
apps/setting/models_provider/impl/openai_model_provider/model/tts.py
apps/setting/models_provider/impl/volcanic_engine_model_provider/model/tts.py
apps/setting/models_provider/impl/xf_model_provider/model/tts.py
apps/setting/models_provider/impl/xinference_model_provider/model/tts.py
ui/src/api/application.ts
ui/src/views/application/ApplicationSetting.vue
ui/src/views/application/component/TTSModeParamSettingDialog.vue
ui/src/workflow/nodes/base-node/index.vue

refactor: 配置TTS参数支持试听功能

---

apps/setting/models_provider/impl/base_chat_open_ai.py

fix: 修复豆包智能体对话报错的缺陷  --bug=1047570 --user=王孝刚 【github#1374】【大模型】豆包模型对接企业微信，可以正常询问问题。对接豆包智能体大模型，在企业微信询问问题，后台日志报错 https://www.tapd.cn/57709429/s/1595490

fix: 修复豆包智能体对话报错的缺陷

---

apps/common/util/common.py
apps/setting/serializers/valid_serializers.py

fix: 修复license校验问题

---

ui/src/views/document/component/GenerateRelatedDialog.vue
ui/src/views/paragraph/component/GenerateRelatedDialog.vue

fix: 保留上次选择的模型和提示词  --bug=1047752 --user=刘瑞斌 【应用】-生成关联问题设置模型和提示词后，再次点击生成关联问题，默认显示用户上次设置的模型和提示词。 https://www.tapd.cn/57709429/s/1596140

fix: 保留上次选择的模型和提示词

---

apps/setting/models_provider/base_model_provider.py
apps/setting/models_provider/impl/aws_bedrock_model_provider/model/llm.py
apps/setting/models_provider/impl/azure_model_provider/model/azure_chat_model.py
apps/setting/models_provider/impl/deepseek_model_provider/model/llm.py
apps/setting/models_provider/impl/gemini_model_provider/model/llm.py
apps/setting/models_provider/impl/kimi_model_provider/model/llm.py
apps/setting/models_provider/impl/ollama_model_provider/model/llm.py
apps/setting/models_provider/impl/openai_model_provider/model/llm.py
apps/setting/models_provider/impl/qwen_model_provider/model/llm.py
apps/setting/models_provider/impl/tencent_model_provider/model/llm.py
apps/setting/models_provider/impl/vllm_model_provider/model/llm.py
apps/setting/models_provider/impl/volcanic_engine_model_provider/model/llm.py
apps/setting/models_provider/impl/wenxin_model_provider/model/llm.py
apps/setting/models_provider/impl/xf_model_provider/model/llm.py
apps/setting/models_provider/impl/xinference_model_provider/model/llm.py
apps/setting/models_provider/impl/zhipu_model_provider/model/llm.py

feat: 大语言模型支持自定义参数入参

---

ui/src/layout/components/top-bar/avatar/ResetPassword.vue
ui/src/views/application-workflow/component/PublishHistory.vue
ui/src/views/application-workflow/index.vue
ui/src/views/application/component/AddDatasetDialog.vue
ui/src/workflow/index.vue
ui/src/workflow/nodes/base-node/component/ApiInputFieldTable.vue
ui/src/workflow/nodes/base-node/component/UserInputFieldTable.vue
ui/src/workflow/nodes/base-node/index.vue

fix: 调整修改密码逻辑(#1311)

---

ui/src/components/ai-chat/index.vue

fix: 修复高级应用调试时接口传入的参数不能填充默认值的问题  --bug=1047927 --user=刘瑞斌 【应用编排】接口传参必填项默认值不显示 https://www.tapd.cn/57709429/s/1598598

fix: 修复高级应用调试时接口传入的参数不能填充默认值的问题

---

ui/src/views/application/component/TTSModeParamSettingDialog.vue

fix: 修复配置TTS模型参数时必填项没有拦截的问题  --bug=1048068 --user=刘瑞斌 【应用】语音合成模型参数设置了必填，没有填写的参数的时候点确认没有提示 https://www.tapd.cn/57709429/s/1598728

fix: 修复配置TTS模型参数时必填项没有拦截的问题

---

ui/src/views/template/component/SelectProviderDialog.vue

fix: 添加模型时选择框里的模型按照名称排序  --bug=1048208 --user=刘瑞斌 优化：【系统管理-模型设置】添加模型，显示的供应商里列表和左边的供应商列表排序不一致 https://www.tapd.cn/57709429/s/1599397

fix: 添加模型时选择框里的模型按照名称排序

---

apps/application/flow/step_node/search_dataset_node/impl/base_search_dataset_node.py

fix: 修复【应用编排】知识库检索节点 最大应用字符数 不生效

fix: 修复【应用编排】知识库检索节点 最大应用字符数 不生效

---

.github/workflows/typos_check.yml
.typos.toml
ui/src/views/document/index.vue

fix: 修复文档表格按照状态过滤没有生成问题中的缺陷  --bug=1048200 --user=刘瑞斌 【知识库】文档列表按文件状态排序，少了一个「生成问题中」的选项 https://www.tapd.cn/57709429/s/1601157

fix: 修复文档表格按照状态过滤没有生成问题中的缺陷

---

ui/src/workflow/nodes/base-node/component/ApiFieldFormDialog.vue
ui/src/workflow/nodes/base-node/component/UserFieldFormDialog.vue

fix: 修复添加参数对话框的标题文字不对应的问题  --bug=1047778 --user=刘瑞斌 【应用编排】- 用户输入，点击编辑参数后，关闭对话框，再点击添加参数打开的还是编辑参数对话框 https://www.tapd.cn/57709429/s/1601532

fix: 修复添加参数对话框的标题文字不对应的问题

---

ui/src/views/application/ApplicationSetting.vue
ui/src/workflow/nodes/base-node/index.vue

fix: 关闭语音开关后清除模型id  --bug=1047571 --user=刘瑞斌 【github#1376】【应用】在应用处关闭语音模型开关，去模型处删除模型，提示关联了一个应用，无法删除该模型。 https://www.tapd.cn/57709429/s/1601917

fix: 关闭语音开关后清除模型id

---

apps/application/serializers/application_serializers.py
apps/dataset/serializers/dataset_serializers.py
apps/dataset/views/dataset.py
apps/function_lib/serializers/function_lib_serializer.py
apps/function_lib/views/function_lib_views.py
apps/users/serializers/user_serializers.py
apps/users/urls.py
apps/users/views/user.py
ui/src/api/application.ts
ui/src/components/card-box/index.vue
ui/src/styles/variables.scss
ui/src/views/application/index.vue
ui/src/views/dataset/index.vue
ui/src/views/function-lib/index.vue

feat: 应用、知识库、函数库增加创建者  --story=1016834 --user=王孝刚 应用、知识库、函数增加创建者，可以按创建用户查看资源 #1304 https://www.tapd.cn/57709429/s/1605886

feat: 应用、知识库、函数库增加创建者

---

apps/common/cache/file_cache.py

fix: 修复应用发布后无法使用最新的应用设置

---

apps/common/handle/impl/doc_split_handle.py

fix: 修复旧word文档图片无法正常识别 #1533

---

ui/src/workflow/common/NodeContainer.vue
ui/src/workflow/common/app-node.ts
ui/src/workflow/nodes/condition-node/index.ts

feat: 工作流编排应用记住节点的收起/展开状态 #1543

feat: 工作流编排应用记住节点的收起/展开状态 #1543

---

ui/src/views/team/component/PermissionSetting.vue

fix: 【团队成员】修复全选的问题 (#1558)

---

apps/setting/models_provider/impl/xinference_model_provider/credential/embedding.py
apps/setting/models_provider/impl/xinference_model_provider/model/embedding.py

fix: 修复xinference向量模型添加失败的缺陷

---

apps/application/flow/step_node/function_lib_node/impl/base_function_lib_node.py

fix: 修复函数库,非必填引用类型,不传值 执行报错 #1564

fix: 修复函数库,非必填引用类型,不传值 执行报错 #1564

---

ui/src/views/authentication/component/EditModal.vue
ui/src/views/authentication/component/SCAN.vue

refactor: 优化文案

---

apps/application/flow/workflow_manage.py

fix: 添加对话stream流式结束标记

---

apps/application/flow/step_node/search_dataset_node/impl/base_search_dataset_node.py

feat: 去除工作流直接返回内容的标题数据

---

ui/src/api/log.ts

fix: 修复日志导出格式不正确的缺陷  --bug=1048673 --user=王孝刚 【应用】导出对话日志是xls格式，excel 打开提示文件格式不对 https://www.tapd.cn/57709429/s/1608292

fix: 修复日志导出格式不正确的缺陷

---

apps/application/migrations/0020_application_record_update_time.py
apps/application/serializers/chat_message_serializers.py
apps/application/serializers/chat_serializers.py
ui/src/views/log/index.vue

feat: 对话日志默认使用最后对话时间  --story=1017064 --user=王孝刚 【对话日志】- 列表排序使用最后对话时间 issue #1587 https://www.tapd.cn/57709429/s/1609354

feat: 对话日志默认使用最后对话时间

---

apps/common/config/swagger_conf.py
apps/smartdoc/settings/base.py

fix: 修复swagger接口文档中schema不正确的问题

fix: 修复swagger接口文档中schema不正确的问题

---

apps/application/flow/i_step_node.py

fix: 修复直接回答对话无法显示文本

---

ui/src/workflow/common/NodeContainer.vue

fix: 修复工作流节点收缩后无法发布 #1582

---

apps/application/flow/step_node/document_extract_node/impl/base_document_extract_node.py
apps/application/flow/step_node/image_understand_step_node/i_image_understand_node.py
apps/application/flow/step_node/image_understand_step_node/impl/base_image_understand_node.py
apps/application/views/chat_views.py
apps/common/job/__init__.py
apps/common/job/clean_debug_file_job.py
ui/src/components/ai-chat/component/chat-input-operate/index.vue
ui/src/components/ai-chat/index.vue
ui/src/workflow/nodes/image-understand/index.vue

refactor: 处理历史会话中图片的问题

---

apps/common/handle/impl/pdf_split_handle.py

--bug=1048190 --user=刘瑞斌 【知识库】- 上传PDF文档 报错  ，关联issue #1468 https://www.tapd.cn/57709429/s/1611070

fix: 处理PDF中出现 \0 字符报 Null characters are not allowed

---

apps/setting/models_provider/impl/aliyun_bai_lian_model_provider/aliyun_bai_lian_model_provider.py
apps/setting/models_provider/impl/aliyun_bai_lian_model_provider/credential/llm.py
apps/setting/models_provider/impl/aliyun_bai_lian_model_provider/model/llm.py
ui/src/views/login/index.vue

feat(模型管理): 支持阿里云百炼大模型

---

ui/src/components/ai-chat/index.vue

feat: 添加对话中图片数据

---

ui/src/views/team/component/CreateMemberDialog.vue

fix(系统设置): 修复添加已存在的成员失败后，删除该成员，仍不能继续添加的缺陷  --bug=1049026 --user=王孝刚 【系统设置】团队成员-添加成员时，选中已存在的成员之后再删除，仍不能继续添加 https://www.tapd.cn/57709429/s/1611718

fix(系统设置): 修复添加已存在的成员失败后，删除该成员，仍不能继续添加的缺陷

---

ui/src/components/dynamics-form/constructor/data.ts
ui/src/components/dynamics-form/constructor/items/MultiSelectConstructor.vue
ui/src/components/dynamics-form/constructor/items/RadioCardConstructor.vue
ui/src/components/dynamics-form/constructor/items/RadioRowConstructor.vue
ui/src/components/dynamics-form/items/radio/RadioRow.vue
ui/src/workflow/nodes/form-node/index.vue

feat: 表单节点添加多选框,选项卡等组件

---

ui/src/api/type/application.ts
ui/src/components/dynamics-form/constructor/items/RadioCardConstructor.vue
ui/src/components/dynamics-form/constructor/items/RadioRowConstructor.vue

fix: 修复前端类型错误

---

apps/application/flow/workflow_manage.py
ui/src/workflow/common/validate.ts
ui/src/workflow/nodes/base-node/index.vue

fix: 图片理解节点可以作为结束节点  --bug=1049088 --user=刘瑞斌 【应用编排】图片理解模型应该可以作为结束节点 https://www.tapd.cn/57709429/s/1612298<br>fix: 开启文件上传开关时设置默认值  --bug=1049087 --user=刘瑞斌 【应用编排】开启文件上传后，全局变量列表没有自动生成文件变量 https://www.tapd.cn/57709429/s/1612303

fix: 开启文件上传开关时设置默认值

---

apps/application/flow/step_node/image_understand_step_node/impl/base_image_understand_node.py

refactor: 处理多张图片的HumanMessage

---

apps/application/flow/step_node/application_node/i_application_node.py
apps/application/flow/step_node/application_node/impl/base_application_node.py
ui/src/views/application-workflow/component/DropdownMenu.vue
ui/src/views/application/index.vue
ui/src/views/dataset/index.vue
ui/src/views/function-lib/index.vue
ui/src/workflow/nodes/application-node/index.vue

refactor(应用): 优化嵌入应用

---

ui/src/enums/model.ts

fix: 修复模型card上没显示图片理解类型  --bug=1049276 --user=刘瑞斌 [系统管理]模型设置-添加的OpenAI图片理解模型后，模型类型显示为空 https://www.tapd.cn/57709429/s/1614428

fix: 修复模型card上没显示图片理解类型

---

ui/src/views/dataset/component/SetRules.vue

上传文档后进行分段设置的页面中，页面宽度较小的情况下会发生checkbox文本被遮盖。
修改style，文本自动换行。

style: 设置文本自动换行

---

ui/src/components/ai-chat/ExecutionDetailDialog.vue

fix: 修复查看详情时没有上传图片不显示提示词的问题

---

ui/src/workflow/nodes/base-node/index.vue
ui/src/workflow/nodes/start-node/index.vue

fix: 修复关闭文件上传开关后开始节点没有取消document和image  --bug=1049507 --user=刘瑞斌 【应用】应用设置-基本信息中开启文件上传 再关闭，开始节点的参数输出“文档”没有同步删除 https://www.tapd.cn/57709429/s/1617263

fix: 修复关闭文件上传开关后开始节点没有取消document和image

---

apps/application/flow/step_node/document_extract_node/impl/base_document_extract_node.py
ui/src/components/ai-chat/ExecutionDetailDialog.vue

refactor: 文档提取details保存content长度限制为500

refactor: 文档提取details保存content长度限制为500

---

apps/application/flow/step_node/document_extract_node/impl/base_document_extract_node.py
apps/common/handle/impl/doc_split_handle.py
apps/common/handle/impl/html_split_handle.py
apps/common/handle/impl/pdf_split_handle.py
apps/common/handle/impl/text_split_handle.py

fix: 修复文档提取报错没有显示的问题

---

ui/src/components/ai-chat/component/chat-input-operate/index.vue

fix: 修复文件配置全没勾选的情况下还能上传文件的问题  --bug=1049620 --user=刘瑞斌 【应用编排】文件上传设置没勾选文档也没勾选图片，发布后对话还是能上传文档和图片 https://www.tapd.cn/57709429/s/1618519

fix: 修复文件配置全没勾选的情况下还能上传文件的问题

---

ui/src/components/ai-chat/KnowledgeSource.vue
ui/src/components/ai-chat/component/ParagraphCard.vue

fix: 修复引用分段详情弹框和执行详情里的文档名称不能点的缺陷  --bug=1049682 --user=王孝刚 【应用】引用分段详情弹框和执行详情里的文档名称不能点 https://www.tapd.cn/57709429/s/1619877

fix: 修复引用分段详情弹框和执行详情里的文档名称不能点的缺陷

---

ui/src/utils/utils.ts
ui/src/views/dataset/component/UploadComponent.vue

fix: 上传文本文件去掉csv  --bug=1049721 --user=刘瑞斌 【知识库】上传文本文件夹，里面包含csv文件，csv文件也能上传成功 https://www.tapd.cn/57709429/s/1620432

fix: 上传文本文件去掉csv

---

apps/application/flow/step_node/image_understand_step_node/impl/base_image_understand_node.py

fix: 修复执行历史详情里节点和工作流类型的展示问题  --bug=1049655 --user=刘瑞斌 【应用编排】图片理解模型，历史记录选择节点和工作流的效果反了 https://www.tapd.cn/57709429/s/1620986

fix: 修复执行历史详情里节点和工作流类型的展示问题

---

ui/src/components/dynamics-form/constructor/items/MultiSelectConstructor.vue
ui/src/components/dynamics-form/constructor/items/RadioCardConstructor.vue
ui/src/components/dynamics-form/constructor/items/RadioRowConstructor.vue
ui/src/components/dynamics-form/constructor/items/SingleSelectConstructor.vue

refactor: 添加参数时单选、多选、选项卡设置第一个条目  --bug=1049778 --user=刘瑞斌 【表单收集】- 组件类型选择单选框、多选框、选项卡、单行选项卡后，默认显示一行选项值。 https://www.tapd.cn/57709429/s/1621602

refactor: 添加参数时单选、多选、选项卡设置第一个条目

---

ui/src/components/dynamics-form/constructor/items/JsonInputConstructor.vue
ui/src/components/dynamics-form/constructor/items/MultiSelectConstructor.vue
ui/src/components/dynamics-form/constructor/items/SingleSelectConstructor.vue
ui/src/workflow/nodes/form-node/index.vue

fix: 修复单选框多选框 选择器未使用label作为选项

---

apps/dataset/serializers/dataset_serializers.py
apps/dataset/serializers/document_serializers.py

fix: 修复分页查询时间相同的情况下数据错乱

---

apps/application/flow/step_node/application_node/impl/base_application_node.py
apps/application/flow/workflow_manage.py
apps/common/handle/impl/response/system_to_response.py

fix: 修复对话使用api调用无法响应数据

---

apps/dataset/serializers/document_serializers.py

fix: 修复文档状态在多次取消的情况下状态错误

---

apps/application/flow/step_node/image_understand_step_node/impl/base_image_understand_node.py

fix: 修复图片识别历史记录无法显示多个图片问题

---

ui/src/views/authentication/component/EditModal.vue

fix: 企业微信扫码信息配置错误  --bug=1050048 --user=王孝刚 【企业微信-扫码登录】配置信息错误 https://www.tapd.cn/57709429/s/1626175

fix: 企业微信扫码信息配置错误

---

ui/src/components/ai-chat/component/chat-input-operate/index.vue
ui/src/workflow/nodes/base-node/component/FileUploadSettingDialog.vue
ui/src/workflow/nodes/start-node/index.vue

feat: 支持上传mp3文件

---

apps/application/flow/step_node/ai_chat_step_node/i_chat_node.py
apps/application/flow/step_node/ai_chat_step_node/impl/base_chat_node.py
apps/application/models/application.py
ui/src/workflow/common/NodeContainer.vue
ui/src/workflow/nodes/ai-chat-node/index.vue

feat: 工作流ai对话节点添加节点上下文

---

apps/dataset/serializers/document_serializers.py
ui/src/views/document/index.vue

fix: 修复文档状态无法过滤

---

apps/application/template/embed.js

fix: 修复嵌入图片过大指引位置错误

---

apps/dataset/views/document.py

fix: 文档导出权限错误

---

apps/dataset/serializers/document_serializers.py

fix: 修复批量导入网页地址swagger上没有填写请求体的地方的缺陷  --bug=1050206 --user=王孝刚 【github#1809】【知识库】web知识库，批量导入网页地址时，抓到的接口有请求体，但是swagger上没有填写请求体的地方。 https://www.tapd.cn/57709429/s/1628286

fix: 修复批量导入网页地址swagger上没有填写请求体的地方的缺陷

---

apps/application/flow/step_node/application_node/impl/base_application_node.py
apps/application/flow/step_node/function_lib_node/impl/base_function_lib_node.py
apps/application/flow/step_node/function_node/impl/base_function_node.py
apps/application/flow/workflow_manage.py

fix: 修复函数库响应数据在日志中不显示问题

---

apps/application/flow/common.py
apps/application/flow/i_step_node.py
apps/application/flow/step_node/application_node/impl/base_application_node.py
apps/application/flow/step_node/form_node/impl/base_form_node.py
apps/application/flow/workflow_manage.py
ui/src/api/type/application.ts

fix: In the dialogue, the form nodes of the sub-application are not displayed as separate cards.

fix: In the dialogue, the form nodes of the sub-application are not displayed as separate cards.

---

apps/dataset/serializers/document_serializers.py
ui/src/views/document/index.vue

fix: The document list status filtering is incorrect.

fix: The document list status filtering is incorrect.

---

apps/setting/models_provider/impl/aliyun_bai_lian_model_provider/aliyun_bai_lian_model_provider.py
apps/setting/models_provider/impl/aliyun_bai_lian_model_provider/credential/image.py
apps/setting/models_provider/impl/aliyun_bai_lian_model_provider/credential/tti.py
apps/setting/models_provider/impl/aliyun_bai_lian_model_provider/model/image.py
apps/setting/models_provider/impl/aliyun_bai_lian_model_provider/model/tti.py

feat: BaiLian Image Model

---

apps/setting/models_provider/impl/azure_model_provider/azure_model_provider.py
apps/setting/models_provider/impl/azure_model_provider/credential/embedding.py
apps/setting/models_provider/impl/azure_model_provider/model/embedding.py

feat: Support Azure embedding model

feat: Support Azure embedding model

---

ui/src/api/type/application.ts

fix: Low version browsers do not have the at function

fix: Low version browsers do not have the at function

---

apps/setting/models_provider/impl/azure_model_provider/azure_model_provider.py
apps/setting/models_provider/impl/azure_model_provider/credential/image.py
apps/setting/models_provider/impl/azure_model_provider/credential/stt.py
apps/setting/models_provider/impl/azure_model_provider/credential/tti.py
apps/setting/models_provider/impl/azure_model_provider/credential/tts.py
apps/setting/models_provider/impl/azure_model_provider/model/image.py
apps/setting/models_provider/impl/azure_model_provider/model/stt.py
apps/setting/models_provider/impl/azure_model_provider/model/tti.py
apps/setting/models_provider/impl/azure_model_provider/model/tts.py

feat: Support Azure image tts stt model

feat: Support Azure image tts stt model

---

apps/application/flow/step_node/document_extract_node/impl/base_document_extract_node.py
apps/application/flow/step_node/speech_to_text_step_node/impl/base_speech_to_text_node.py
ui/src/components/ai-chat/ExecutionDetailDialog.vue

refactor: optimize the display of SST nodes

refactor: optimize the display of SST nodes

---

apps/setting/models_provider/impl/gemini_model_provider/credential/stt.py
apps/setting/models_provider/impl/gemini_model_provider/gemini_model_provider.py
apps/setting/models_provider/impl/gemini_model_provider/model/stt.py

feat: Support gemini stt model

feat: Support gemini stt model

---

apps/setting/models_provider/impl/gemini_model_provider/credential/embedding.py
apps/setting/models_provider/impl/gemini_model_provider/gemini_model_provider.py
apps/setting/models_provider/impl/gemini_model_provider/model/embedding.py

feat: Support gemini embedding model

feat: Support gemini embedding model

---

apps/dataset/views/dataset.py

fix: fix the defect of interface parameter transmission failure  --bug=1050500 --user=王孝刚 【接口文档】接口文档里的获取知识库列表（不分页）接口，带参数查询无数据 https://www.tapd.cn/57709429/s/1634918

fix: fix the defect of interface parameter transmission failure

---

ui/src/views/template/component/CreateModelDialog.vue

fix: Open add model dialog show base-info always  --bug=1050670 --user=刘瑞斌 【系统管理】模型设置-添加模型-默认显示了“高级设置”标签页 https://www.tapd.cn/57709429/s/1635004

fix: Open add model dialog show base-info always

---

apps/application/flow/workflow_manage.py
ui/src/workflow/common/NodeContainer.vue

feat: Node execution conditions

feat: Node execution conditions

---

ui/src/components/dynamics-form/constructor/index.vue
ui/src/components/dynamics-form/constructor/items/DatePickerConstructor.vue
ui/src/components/dynamics-form/constructor/items/JsonInputConstructor.vue
ui/src/components/dynamics-form/constructor/items/MultiSelectConstructor.vue
ui/src/components/dynamics-form/constructor/items/RadioCardConstructor.vue
ui/src/components/dynamics-form/constructor/items/SingleSelectConstructor.vue
ui/src/components/dynamics-form/constructor/items/TextInputConstructor.vue
ui/src/components/dynamics-form/index.vue
ui/src/components/dynamics-form/type.ts

refactor: 支持配置必填项是否展示  --story=1017498 --user=刘瑞斌 【高级编排应用】用户输入参数默认值增加显示设置优化 https://www.tapd.cn/57709429/s/1635457

refactor: 支持配置必填项是否展示

---

installer/Dockerfile
installer/compile.py

build: compile-pyc

---

apps/application/serializers/chat_serializers.py

fix: fix the defect where the exported log field is empty  --bug=1049645 --user=王孝刚 【应用】应用编排嵌入高级编排应用，导出对话日志文件的优化后问题字段没有值 https://www.tapd.cn/57709429/s/1635887

fix: fix the defect where the exported log field is empty

---

apps/common/util/common.py
apps/setting/models_provider/impl/aliyun_bai_lian_model_provider/model/tts.py
apps/setting/models_provider/impl/azure_model_provider/model/tts.py
apps/setting/models_provider/impl/openai_model_provider/model/tts.py
apps/setting/models_provider/impl/volcanic_engine_model_provider/model/tts.py
apps/setting/models_provider/impl/xf_model_provider/model/tts.py
apps/setting/models_provider/impl/xinference_model_provider/model/tts.py
ui/src/api/application.ts
ui/src/views/application/component/AccessSettingDrawer.vue

fix: fix the defect of empty line to speech error  --bug=1050760 --user=王孝刚 【应用】文本转语音使用豆包模型时，用户问题文本中间有空行，会报错 https://www.tapd.cn/57709429/s/1636230

fix: fix the defect of empty line to speech error

---

apps/application/flow/workflow_manage.py

fix: Workflow cannot respond to errors

fix: Workflow cannot respond to errors

---

apps/dataset/serializers/document_serializers.py
apps/dataset/swagger_api/document_api.py
apps/dataset/urls.py
apps/dataset/views/document.py
ui/src/api/document.ts
ui/src/styles/element-plus.scss
ui/src/views/document/index.vue

feat: Batch cancel tasks

---

apps/application/serializers/application_serializers.py

fix: Workflow import did not insert AccessToken information

fix: Workflow import did not insert AccessToken information

---

apps/setting/models_provider/impl/aws_bedrock_model_provider/credential/llm.py
apps/setting/models_provider/impl/aws_bedrock_model_provider/model/llm.py

feat: support aws proxy_url

---

apps/dataset/serializers/document_serializers.py

fix: Empty knowledge base upload error

fix: Empty knowledge base upload error

---

apps/dataset/serializers/document_serializers.py

fix: Batch generation of problems

fix: Batch generation of problems

---

ui/src/components/dynamics-form/constructor/index.vue
ui/src/components/dynamics-form/constructor/items/DatePickerConstructor.vue
ui/src/components/dynamics-form/constructor/items/JsonInputConstructor.vue
ui/src/components/dynamics-form/constructor/items/MultiSelectConstructor.vue
ui/src/components/dynamics-form/constructor/items/RadioCardConstructor.vue
ui/src/components/dynamics-form/constructor/items/RadioRowConstructor.vue
ui/src/components/dynamics-form/constructor/items/SingleSelectConstructor.vue
ui/src/components/dynamics-form/constructor/items/TextInputConstructor.vue
ui/src/components/dynamics-form/index.vue
ui/src/views/application/component/AIModeParamSettingDialog.vue

fix: Invalid parameter saving display

fix: Invalid parameter saving display

---

apps/application/flow/step_node/speech_to_text_step_node/i_speech_to_text_node.py
apps/application/flow/step_node/text_to_speech_step_node/impl/base_text_to_speech_node.py
apps/setting/models_provider/impl/volcanic_engine_model_provider/model/tts.py

fix: fix tts node and stt node error  --bug=1050817 --user=王孝刚 【应用编排】文本转语音，字数不是很多但是模型提示超长了 https://www.tapd.cn/57709429/s/1636787 --bug=1050821 --user=王孝刚 【应用编排】语音转文本错误信息是图片缺少file_id https://www.tapd.cn/57709429/s/1636786

fix: fix tts node and stt node error

---

apps/common/util/common.py

fix: Text ignores special characters such as HTML tags  --bug=1050847 --user=王孝刚 【应用】-文本转语音节点在接收到带有html标签或url的文本，生成的语音中没有忽略代码和url等信息 https://www.tapd.cn/57709429/s/1637065

fix: Text ignores special characters such as HTML tags

---

apps/application/flow/workflow_manage.py

fix: Workflow execution conditions did not execute as expected

fix: Workflow execution conditions did not execute as expected

---

apps/common/util/common.py

fix: tts node add a prompt with empty text  --bug=1050887 --user=王孝刚 【应用编排】知识库检索节点为空，走到文本转语音节点会报错 https://www.tapd.cn/57709429/s/1637596

fix: tts node add a prompt with empty text

---

apps/application/flow/workflow_manage.py

feat: The workflow node cannot obtain values from other nodes, which is set as the default value

feat: The workflow node cannot obtain values from other nodes, which is set as the default value

---

apps/application/flow/step_node/form_node/impl/base_form_node.py

feat: The form node supports obtaining data from other nodes

feat: The form node supports obtaining data from other nodes

---

apps/application/flow/step_node/ai_chat_step_node/impl/base_chat_node.py
apps/application/flow/step_node/question_node/impl/base_question_node.py

feat: AI dialogue roles support obtaining data from other nodes

feat: AI dialogue roles support obtaining data from other nodes

---

apps/application/flow/step_node/ai_chat_step_node/i_chat_node.py

fix: Dialogue node context type is not required

fix: Dialogue node context type is not required

---

apps/smartdoc/conf.py

feat: Add default value for DB_MAX_OVERFLOW

feat: Add default value for DB_MAX_OVERFLOW

---

ui/src/components/codemirror-editor/index.vue

fix: The functions in the library cannot be modified after being defined

fix: The functions in the library cannot be modified after being defined

---

apps/dataset/serializers/common_serializers.py

fix: Exporting zip cannot open the file

fix: Exporting zip cannot open the file

---

ui/src/components/dynamics-form/FormItem.vue
ui/src/components/dynamics-form/items/radio/RadioCard.vue
ui/src/components/dynamics-form/items/radio/RadioRow.vue

fix: The form must be filled out to trigger verification, and the verification prompt is not eliminated after assignment

fix: The form must be filled out to trigger verification, and the verification prompt is not eliminated after assignment

---

ui/src/views/template/component/EditModel.vue

fix: Model editing prohibits modifying model types

fix: Model editing prohibits modifying model types

---

ui/src/views/application/index.vue

fix: Export application error prompt repeated

fix: Export application error prompt repeated

---

ui/src/workflow/nodes/base-node/index.vue

fix: The dropdown menu of workflow basic components cannot be scrolled

fix: The dropdown menu of workflow basic components cannot be scrolled

---

apps/application/flow/step_node/ai_chat_step_node/impl/base_chat_node.py
apps/application/flow/step_node/question_node/impl/base_question_node.py

fix: Error in obtaining variables for character settings

fix: Error in obtaining variables for character settings

---

apps/setting/models_provider/impl/tencent_model_provider/tencent_model_provider.py

fix: fix hunyuan-functioncall edit faild  --bug=1051010 --user=刘瑞斌 【模型设置】修改腾讯混元的大语言模型为 hunyuan-functioncall 模型失败，提示模型不存在 https://www.tapd.cn/57709429/s/1639072

fix: fix hunyuan-functioncall edit faild

---

apps/dataset/task/sync.py

fix: Replace synchronization error

fix: Replace synchronization error

---

ui/src/workflow/nodes/speech-to-text-node/index.vue
ui/src/workflow/nodes/text-to-speech-node/index.vue

fix: tts node and stt node add warning  --bug=1050722 --user=王孝刚 【应用编排】前置节点删掉后，调试和发布的时候引用前置节点的变量要有提示 https://www.tapd.cn/57709429/s/1639310

fix: tts node and stt node add warning

---

apps/application/flow/step_node/application_node/impl/base_application_node.py

fix: Embedded application displays incomplete data

fix: Embedded application displays incomplete data

---

ui/src/components/ai-chat/component/operation-button/ChatOperationButton.vue
ui/src/components/ai-chat/component/operation-button/LogOperationButton.vue

fix: show error message for tts model params not correct  --bug=1051057 --user=刘瑞斌 【模型管理】语音合成模型有错误的参数，播放回答内容时没有反应 https://www.tapd.cn/57709429/s/1639429

fix: show error message for tts model params not correct

---

ui/src/workflow/nodes/base-node/component/UserInputFieldTable.vue
ui/src/workflow/nodes/form-node/index.vue

fix: The switch node does not display default values

fix: The switch node does not display default values

---

apps/dataset/serializers/paragraph_serializers.py

fix: Generate a problem with continuous clicking without response

fix: Generate a problem with continuous clicking without response

---

ui/src/components/ai-chat/KnowledgeSource.vue

perf: KnowledgeSource filename too long

perf: KnowledgeSource filename too long

---

ui/src/views/application-overview/component/DisplaySettingDialog.vue
ui/src/views/application-overview/component/XPackDisplaySettingDialog.vue
ui/src/views/application-overview/index.vue

perf: application overview  update Text

perf: application overview  update Text

---

ui/src/components/ai-chat/component/chat-input-operate/index.vue

fix: tip image 404

---

apps/setting/models_provider/impl/zhipu_model_provider/zhipu_model_provider.py

fix: support zhipu cogview-3-flash model  --bug=1051161 --user=刘瑞斌 【模型】添加智普免费的图片生成模型（Cogview-3-Flash）报错 https://www.tapd.cn/57709429/s/1641187

fix: support zhipu cogview-3-flash model

---

apps/setting/models_provider/impl/ollama_model_provider/ollama_model_provider.py

fix: Unable to enter custom model name  --bug=1051178 --user=刘瑞斌 【模型】添加Ollama的图片理解模型，自定义输入基础模型报错 https://www.tapd.cn/57709429/s/1641511

fix: Unable to enter custom model name

---

apps/application/flow/workflow_manage.py
ui/src/api/type/application.ts

fix: Workflow The condition setting 'any' did not take effect when the discriminator was executed

fix: Workflow The condition setting 'any' did not take effect when the discriminator was executed

---

apps/common/handle/impl/doc_split_handle.py

fix: Part of the docx document is parsed incorrectly

fix: Part of the docx document is parsed incorrectly

---

ui/src/components/ai-chat/component/operation-button/ChatOperationButton.vue
ui/src/components/ai-chat/component/operation-button/LogOperationButton.vue

feat: Support autoplay audio tag  --story=1017623 --user=刘瑞斌 【应用】-语音播放时遇到音频文件直接播放文件内容 https://www.tapd.cn/57709429/s/1642154

feat: Support autoplay audio tag

---

apps/common/event/listener_manage.py
apps/common/util/page_utils.py
apps/dataset/serializers/document_serializers.py
apps/dataset/swagger_api/document_api.py
apps/dataset/views/document.py
apps/embedding/task/embedding.py
ui/src/api/document.ts
ui/src/views/document/component/EmbeddingContentDialog.vue
ui/src/views/document/index.vue

feat: Document vectorization supports processing based on status

feat: Document vectorization supports processing based on status

---

apps/setting/models_provider/impl/tencent_model_provider/tencent_model_provider.py
apps/setting/models_provider/impl/xf_model_provider/xf_model_provider.py

fix: tencent and xf embedding model set default model

fix: tencent and xf embedding model set default model

---

apps/common/event/__init__.py

fix: Guide package

---

apps/dataset/serializers/document_serializers.py

fix: Document upload prompt: missing status list field

fix: Document upload prompt: missing status list field

---

apps/application/serializers/application_serializers.py
ui/src/workflow/nodes/application-node/index.vue

fix: fix github#1988  --bug=1051321 --user=王孝刚 【github#1988】【应用】应用编排接入带用户输入参数的应用，选择后，再次进入应用，选择的参数消失了 https://www.tapd.cn/57709429/s/1643562 --bug=1051323 --user=王孝刚 【应用】创建应用报错 https://www.tapd.cn/57709429/s/1643571

fix: fix github#1988

---

apps/application/flow/workflow_manage.py

perf: Optimize workflow logic

---

apps/common/job/clean_chat_job.py

fix: When deleting conversation logs, they should be deleted by conversation record, not by session.  --bug=1051378 --user=王孝刚 【应用】对话日志删除时应该按对话记录删除，不能按会话删除 https://www.tapd.cn/57709429/s/1645443

fix: When deleting conversation logs, they should be deleted by conversation record, not by session.

---

ui/src/views/application/component/AccessSettingDrawer.vue

fix: Typos

---

ui/src/workflow/common/shortcut.ts
ui/src/workflow/nodes/application-node/index.vue

fix: 1051456  --bug=1051456 --user=王孝刚 【应用编排】当前应用关闭文件上传开关后，引用的应用编排节点，选择文档变量没有清空 https://www.tapd.cn/57709429/s/1646694

fix: 1051456

---

apps/application/swagger_api/application_api.py
apps/application/views/application_views.py

fix: text to speech doc show request body  【【github#2032 】【swagger 文档】/api/application/application_id/text to_speech 接口缺少文件上传的入口参数】 https://www.tapd.cn/57709429/bugtrace/bugs/view/1157709429001051530

fix: text to speech doc show request body

---

apps/setting/models_provider/impl/vllm_model_provider/credential/embedding.py
apps/setting/models_provider/impl/vllm_model_provider/credential/image.py
apps/setting/models_provider/impl/vllm_model_provider/model/embedding.py
apps/setting/models_provider/impl/vllm_model_provider/model/image.py
apps/setting/models_provider/impl/vllm_model_provider/vllm_model_provider.py

feat: Support vllm image model

feat: Support vllm image model

---

ui/src/components/ai-chat/index.vue

fix: Fix new chat cannot load document_image  --bug=1051402 --user=刘瑞斌 【github#2008】【应用编排】应用演示页面新建对话后再次上传文档，无法读取文档内容 https://www.tapd.cn/57709429/s/1648617

fix: Fix new chat cannot load document_image

---

ui/src/views/application/ApplicationSetting.vue
ui/src/workflow/nodes/base-node/index.vue

fix: show/hide autoplay and autosend checkbox  --bug=1051707 --user=刘瑞斌 【应用】-未开启语音输入和语音播放时，不显示自动发送和自动播放 https://www.tapd.cn/57709429/s/1648662

fix: show/hide autoplay and autosend checkbox

---

apps/setting/models_provider/impl/openai_model_provider/credential/llm.py

fix: Volcano engine large speech model cannot be added

fix: Volcano engine large speech model cannot be added

---

ui/src/components/ai-chat/component/chat-input-operate/index.vue
ui/src/components/ai-chat/component/question-content/index.vue

perf: upload file count(#2029)

---

apps/application/chat_pipeline/step/chat_step/impl/base_chat_step.py
apps/application/chat_pipeline/step/reset_problem_step/impl/base_reset_problem_step.py
ui/src/components/ai-chat/component/control/index.vue

fix: After selecting the answer content in the AI conversation and clicking copy, it cannot be copied

fix: After selecting the answer content in the AI conversation and clicking copy, it cannot be copied

---

apps/application/serializers/application_serializers.py

fix: Fix autosend and autoplay not working  --bug=1051779 --user=刘瑞斌 【应用】应用演示页面，不能自动播放回答内容 https://www.tapd.cn/57709429/s/1649281

fix: Fix autosend and autoplay not working

---

ui/src/components/dynamics-form/items/label/TooltipLabel.vue

style: TooltipLabel max-width 200px  --bug=1051041 --user=刘瑞斌 【应用】高级编排-图片生成-参数设置：文字提示样式不对 https://www.tapd.cn/57709429/s/1649373

style: TooltipLabel max-width 200px

---

.gitignore
apps/application/flow/default_workflow_en.json
apps/application/flow/default_workflow_zh.json
apps/application/flow/default_workflow_zh_Hant.json
apps/application/flow/workflow_manage.py
apps/application/serializers/application_serializers.py

fix: New workflow application, node name not internationalized

fix: New workflow application, node name not internationalized

---

ui/src/components/ai-chat/component/control/index.vue

fix: Embedded AI conversation cannot open the tool box

fix: Embedded AI conversation cannot open the tool box

---

ui/src/locales/lang/en-US/views/user.ts

fix: i18n bug

---

apps/setting/models_provider/impl/aliyun_bai_lian_model_provider/aliyun_bai_lian_model_provider.py

fix: bai_lian rerank default model

fix: bai_lian rerank default model

---

apps/application/chat_pipeline/step/chat_step/impl/base_chat_step.py

fix: The simple application of stream=false Q&A will also directly return segmented content when the similarity is not enough

fix: The simple application of stream=false Q&A will also directly return segmented content when the similarity is not enough

---

apps/dataset/serializers/document_serializers.py
apps/locales/en_US/LC_MESSAGES/django.po
apps/locales/zh_CN/LC_MESSAGES/django.po
apps/locales/zh_Hant/LC_MESSAGES/django.po

fix: Knowledge base export error

fix: Knowledge base export error

---

ui/src/locales/lang/en-US/views/system.ts
ui/src/locales/lang/zh-CN/views/system.ts
ui/src/locales/lang/zh-Hant/views/system.ts
ui/src/views/application-overview/component/XPackDisplaySettingDialog.vue
ui/src/views/login/components/dingtalkQrCode.vue
ui/src/views/login/components/larkQrCode.vue
ui/src/views/login/components/wecomQrCode.vue
ui/src/views/login/index.vue
ui/src/views/theme/index.vue

fix: login i18n bug  --bug=1051922 --user=王孝刚 【国际化】扫码登录没有国际化 https://www.tapd.cn/57709429/s/1649970

fix: login i18n bug

---

apps/dataset/serializers/dataset_serializers.py
apps/dataset/serializers/document_serializers.py

fix: The knowledge base vector model can still be vectorized even after unauthorized use

fix: The knowledge base vector model can still be vectorized even after unauthorized use

---

apps/application/serializers/chat_serializers.py
apps/common/util/common.py
apps/locales/en_US/LC_MESSAGES/django.po
apps/locales/zh_CN/LC_MESSAGES/django.po
apps/locales/zh_Hant/LC_MESSAGES/django.po

fix: application i18n

---

ui/src/workflow/common/NodeCascader.vue

fix: application workflow node params

fix: application workflow node params

---

ui/src/components/ai-chat/component/operation-button/ChatOperationButton.vue

fix: Fix autoplay when tts disabled  --bug=1051950 --user=刘瑞斌 【应用】不关闭自动朗读，直接关闭语言合成模型，还是会自动朗读 https://www.tapd.cn/57709429/s/1650240

fix: Fix autoplay when tts disabled

---

ui/src/views/dataset/component/SetRules.vue

fix: 1051957  --bug=1051957 --user=王孝刚 【知识库】在预览时修改添加标题，勾选导入时添加分段标题为关联问题，问题未和分段关联 https://www.tapd.cn/57709429/s/1650244

fix: 1051957

---

apps/application/flow/step_node/function_lib_node/impl/base_function_lib_node.py
apps/application/flow/step_node/function_node/impl/base_function_node.py
apps/application/flow/workflow_manage.py

fix: Workflow execution logic error

fix: Workflow execution logic error

---

apps/setting/models_provider/impl/wenxin_model_provider/credential/llm.py

fix: Failed to save the Qianfan large model

fix: Failed to save the Qianfan large model

---

apps/application/flow/step_node/document_extract_node/impl/base_document_extract_node.py

refactor: override document extract node save_content

refactor: override document extract node save_content

---

apps/setting/models_provider/impl/aws_bedrock_model_provider/credential/llm.py
apps/setting/models_provider/impl/azure_model_provider/credential/llm.py

fix: i18n azure llm mode

---

apps/setting/models_provider/base_model_provider.py
apps/setting/models_provider/constants/model_provider_constants.py
apps/setting/models_provider/impl/aliyun_bai_lian_model_provider/aliyun_bai_lian_model_provider.py
apps/setting/models_provider/impl/siliconCloud_model_provider/__init__.py
apps/setting/models_provider/impl/siliconCloud_model_provider/credential/embedding.py
apps/setting/models_provider/impl/siliconCloud_model_provider/credential/image.py
apps/setting/models_provider/impl/siliconCloud_model_provider/credential/llm.py
apps/setting/models_provider/impl/siliconCloud_model_provider/credential/reranker.py
apps/setting/models_provider/impl/siliconCloud_model_provider/credential/stt.py
apps/setting/models_provider/impl/siliconCloud_model_provider/credential/tti.py
apps/setting/models_provider/impl/siliconCloud_model_provider/credential/tts.py
apps/setting/models_provider/impl/siliconCloud_model_provider/model/embedding.py
apps/setting/models_provider/impl/siliconCloud_model_provider/model/image.py
apps/setting/models_provider/impl/siliconCloud_model_provider/model/llm.py
apps/setting/models_provider/impl/siliconCloud_model_provider/model/reranker.py
apps/setting/models_provider/impl/siliconCloud_model_provider/model/stt.py
apps/setting/models_provider/impl/siliconCloud_model_provider/model/tti.py
apps/setting/models_provider/impl/siliconCloud_model_provider/model/tts.py
apps/setting/models_provider/impl/siliconCloud_model_provider/siliconCloud_model_provider.py

feat: support siliconCloud  --story=1017720 --user=王孝刚 【模型管理】-支持SiliconCloud供应商的大语言模型、向量模型 https://www.tapd.cn/57709429/s/1650888

feat: support siliconCloud

---

ui/src/components/login-layout/index.vue
ui/src/components/markdown/MdEditor.vue
ui/src/locales/index.ts
ui/src/main.ts
ui/src/stores/modules/user.ts
ui/src/views/login/components/wecomQrCode.vue
ui/src/views/login/index.vue

feat: login view add language setting

feat: login view add language setting

---

apps/setting/models_provider/impl/aliyun_bai_lian_model_provider/aliyun_bai_lian_model_provider.py
apps/setting/models_provider/impl/aws_bedrock_model_provider/aws_bedrock_model_provider.py
apps/setting/models_provider/impl/deepseek_model_provider/deepseek_model_provider.py
apps/setting/models_provider/impl/gemini_model_provider/gemini_model_provider.py
apps/setting/models_provider/impl/local_model_provider/local_model_provider.py
apps/setting/models_provider/impl/ollama_model_provider/ollama_model_provider.py
apps/setting/models_provider/impl/qwen_model_provider/qwen_model_provider.py
apps/setting/models_provider/impl/siliconCloud_model_provider/credential/reranker.py
apps/setting/models_provider/impl/siliconCloud_model_provider/model/reranker.py
apps/setting/models_provider/impl/siliconCloud_model_provider/siliconCloud_model_provider.py
apps/setting/models_provider/impl/tencent_model_provider/tencent_model_provider.py
apps/setting/models_provider/impl/vllm_model_provider/vllm_model_provider.py
apps/setting/models_provider/impl/volcanic_engine_model_provider/volcanic_engine_model_provider.py
apps/setting/models_provider/impl/wenxin_model_provider/wenxin_model_provider.py
apps/setting/models_provider/impl/xf_model_provider/xf_model_provider.py
apps/setting/models_provider/impl/xinference_model_provider/xinference_model_provider.py
apps/setting/models_provider/impl/zhipu_model_provider/zhipu_model_provider.py

feat: support siliconCloud rerank

feat: support siliconCloud rerank

---

apps/common/template/email_template_en.html
apps/common/template/email_template_zh.html
apps/common/template/email_template_zh_Hant.html
apps/dataset/serializers/document_serializers.py
apps/locales/en_US/LC_MESSAGES/django.po
apps/locales/zh_CN/LC_MESSAGES/django.po
apps/users/serializers/user_serializers.py

fix: 1052009  --bug=1052009 --user=王孝刚 [国际化]修改密码的验证码通知邮件未国际化 https://www.tapd.cn/57709429/s/1651094

fix: 1052009

---

apps/setting/models_provider/impl/siliconCloud_model_provider/model/reranker.py

fix: rerank error  --bug=1052035 --user=王孝刚 【模型管理】SiliconFlow的重排模型，重排后的内容不正确 https://www.tapd.cn/57709429/s/1651239

fix: rerank error

---

apps/application/flow/workflow_manage.py

fix: Fix sub application form unable to recall

fix: Fix sub application form unable to recall

---

ui/src/workflow/nodes/text-to-speech-node/index.vue

fix: Workflow text to speech node cannot be added

fix: Workflow text to speech node cannot be added

---

apps/application/flow/step_node/function_lib_node/i_function_lib_node.py
apps/locales/en_US/LC_MESSAGES/django.po
apps/locales/zh_CN/LC_MESSAGES/django.po
apps/locales/zh_Hant/LC_MESSAGES/django.po

fix: Resolve the error message  --bug=1052045 --user=王孝刚 【应用】-应用中使用的函数被删除后，演示中提示函数库被删除，提示错误 https://www.tapd.cn/57709429/s/1651371

fix: Resolve the error message

---

apps/application/flow/workflow_manage.py

fix: Internationalization global variables cannot be retrieved

fix: Internationalization global variables cannot be retrieved

---

apps/common/handle/impl/csv_split_handle.py
apps/common/handle/impl/xls_split_handle.py
apps/common/handle/impl/xlsx_split_handle.py

fix: XLS, XLSX, CSV file upload lost data

fix: XLS, XLSX, CSV file upload lost data

---

ui/src/locales/lang/en-US/common.ts
ui/src/locales/lang/en-US/views/application.ts
ui/src/locales/lang/en-US/views/dataset.ts
ui/src/locales/lang/en-US/views/problem.ts

This PR refines inconsistent and unnatural English translations in the UI. 
The focus was on improving clarity and fluency in areas where the original Chinese translations sounded unnatural in English. 
Only the Chinese-to-English translations were reviewed and adjusted, ensuring better readability and consistency across the interface.

chore: refine UI text consistency and translation accuracy for Knowledge

---

apps/common/handle/impl/csv_split_handle.py
apps/common/handle/impl/doc_split_handle.py

fix: defect of incorrect document names after importing CSV and docx files into the knowledge base  --bug=1052039 --user=王孝刚 【知识库】-压缩文件中包含csv、docx文件时，导入到知识库后，文档名称包含文件夹名称 https://www.tapd.cn/57709429/s/1651752

fix: defect of incorrect document names after importing CSV and docx files into the knowledge base

---

ui/src/locales/lang/en-US/views/document.ts
ui/src/locales/lang/en-US/views/problem.ts

When questions or segments are semantically or logically related, using 'Relate' is more appropriate than 'Link' or 'Associate,' as it better conveys the intended relationship
- Replaced "Link to Segment" → "Relate to Segment" for better clarity.
- Updated "Linked Segments" → "Related Segments" to ensure consistent terminology.
/release-note-none

chore(i18n): unify "Relate" as the standard term for knowledge

---

ui/src/locales/lang/zh-CN/views/system.ts
ui/src/locales/lang/zh-Hant/views/system.ts

simplify tab group titles by removing redundant "设置”

chore(i18n): simplify tab group titles by removing redundant Settings

---

ui/src/components/ai-chat/component/chat-input-operate/index.vue

fix: Fix speech recognition failed, the input box did not restore the default style.  --bug=1051969 --user=刘瑞斌 【应用】语音识别失败后输入框没有恢复默认的样式 https://www.tapd.cn/57709429/s/1651864

fix: Fix speech recognition failed, the input box did not restore the default style.

---

ui/src/locales/lang/en-US/ai-chat.ts

fix: Rrefine english words

---

apps/application/flow/tools.py

fix: When the thinking process label is empty, do not process the thinking process

fix: When the thinking process label is empty, do not process the thinking process

---

ui/src/components/markdown/FormRander.vue

fix: The form node submission button has not been internationalized

fix: The form node submission button has not been internationalized

---

apps/application/flow/tools.py

fix: Excerpt from the thinking process

fix: Excerpt from the thinking process

---

ui/src/components/ai-chat/component/answer-content/index.vue

fix: The workflow encountered an error in displaying data for the next node of the form node

fix: The workflow encountered an error in displaying data for the next node of the form node

---

ui/src/components/ai-chat/component/prologue-content/index.vue

fix: Opening remarks with built-in quick Q&A and tag conflicts result in HTML rendering failure

fix: Opening remarks with built-in quick Q&A and tag conflicts result in HTML rendering failure

---

apps/application/chat_pipeline/step/chat_step/impl/base_chat_step.py

fix: Simple application dialogue, non streaming, unable to respond to data

fix: Simple application dialogue, non streaming, unable to respond to data

---

apps/common/handle/impl/csv_split_handle.py
apps/common/handle/impl/xls_split_handle.py
apps/common/handle/impl/xlsx_split_handle.py

fix: The knowledge base table file upload is missing a header

fix: The knowledge base table file upload is missing a header

---

ui/src/components/ai-chat/component/prologue-content/index.vue

fix: Opening statement shortcuts can only handle one issue

fix: Opening statement shortcuts can only handle one issue

---

apps/application/flow/workflow_manage.py

fix: Workflow non streaming dialogue cannot respond

fix: Workflow non streaming dialogue cannot respond

---

apps/setting/models_provider/impl/base_chat_open_ai.py

fix: Fix xinference cannot add deepseek-vl-chat model  --bug=1052077 --user=刘瑞斌 【github#2051】【模型管理】xinference添加issue中提供的视觉模型失败 https://www.tapd.cn/57709429/s/1652171

fix: Fix xinference cannot add deepseek-vl-chat model

---

apps/application/flow/step_node/form_node/impl/base_form_node.py

fix: The Chinese characters in the form data have been transcoded

fix: The Chinese characters in the form data have been transcoded

---

apps/application/flow/workflow_manage.py

fix: After the workflow form collection node is recalled, the subsequent nodes will not execute

fix: After the workflow form collection node is recalled, the subsequent nodes will not execute

---

ui/src/api/type/application.ts

fix: The dialogue prompt is incorrect

fix: The dialogue prompt is incorrect

---

ui/src/locales/lang/en-US/layout.ts
ui/src/locales/lang/en-US/views/application-overview.ts
ui/src/locales/lang/zh-CN/layout.ts
ui/src/locales/lang/zh-Hant/layout.ts
ui/src/utils/theme.ts
ui/src/views/application-overview/index.vue

feat: user manual and help doc support i18n

feat: user manual and help doc support i18n

---

ui/src/locales/useLocale.ts
ui/src/main.ts
ui/src/stores/modules/application.ts
ui/src/stores/modules/user.ts
ui/src/views/application-overview/component/DisplaySettingDialog.vue
ui/src/views/application-overview/component/XPackDisplaySettingDialog.vue
ui/src/views/login/components/wecomQrCode.vue
ui/src/views/login/index.vue

fix: Fix default language

---

ui/src/locales/useLocale.ts
ui/src/main.ts
ui/src/stores/modules/application.ts
ui/src/stores/modules/user.ts
ui/src/views/application-overview/component/DisplaySettingDialog.vue
ui/src/views/application-overview/component/XPackDisplaySettingDialog.vue
ui/src/views/chat/index.vue
ui/src/views/login/components/wecomQrCode.vue
ui/src/views/login/index.vue

fix: Fix default language<br>fix: Fix default language when chat language is null

fix: Fix default language when chat language is null

---

ui/src/layout/components/top-bar/avatar/AboutDialog.vue
ui/src/locales/lang/en-US/layout.ts
ui/src/locales/lang/zh-CN/layout.ts
ui/src/locales/lang/zh-Hant/layout.ts

Add missing translation for "edition" in about dialog

chore(i18n): add missing translation for "edition" in about dialog

---

ui/src/components/markdown/MdPreview.vue
ui/src/locales/lang/en-US/views/template.ts
ui/src/locales/lang/zh-CN/views/template.ts
ui/src/locales/lang/zh-Hant/views/template.ts
ui/src/views/application-overview/component/DisplaySettingDialog.vue
ui/src/views/application-overview/component/XPackDisplaySettingDialog.vue
ui/src/views/authentication/component/EditModal.vue
ui/src/views/authentication/component/SCAN.vue
ui/src/views/authentication/index.vue

fix: Style optimization<br>perf: SCAN login setting views Style optimization<br>fix: markdown preview i18n

fix: markdown preview i18n

---

apps/common/handle/impl/table/xls_parse_table_handle.py

fix: Filter blank sheet  --bug=1052097 --user=刘瑞斌 【github#2196】【应用编排】应用对话的时候上传带空白sheet的表格会报错 https://www.tapd.cn/57709429/s/1653414

fix: Filter blank sheet

---

ui/src/views/login/components/dingtalkQrCode.vue

fix: Non organizational DingTalk users scan the code to log in - can successfully log in and create a user  --bug=1052022 --user=王孝刚 【扫码登录】非组织下钉钉用户扫码登录-可登录成功并创建用户 https://www.tapd.cn/57709429/s/1653465

fix: Non organizational DingTalk users scan the code to log in - can successfully log in and create a user

---

apps/locales/en_US/LC_MESSAGES/django.po
apps/locales/zh_CN/LC_MESSAGES/django.po
apps/locales/zh_Hant/LC_MESSAGES/django.po
apps/setting/models_provider/constants/model_provider_constants.py
apps/setting/models_provider/impl/tencent_cloud_model_provider/__init__.py
apps/setting/models_provider/impl/tencent_cloud_model_provider/credential/llm.py
apps/setting/models_provider/impl/tencent_cloud_model_provider/model/llm.py
apps/setting/models_provider/impl/tencent_cloud_model_provider/tencent_cloud_model_provider.py
apps/setting/models_provider/impl/volcanic_engine_model_provider/volcanic_engine_model_provider.py

feat: support Tencent Cloud  --story=1017838 --user=王孝刚 【模型设置】支持腾讯云的大语言模型  issue#2230 https://www.tapd.cn/57709429/s/1653533

feat: support Tencent Cloud

---

ui/src/locales/lang/zh-CN/ai-chat.ts
ui/src/locales/lang/zh-Hant/ai-chat.ts
ui/src/views/application-workflow/index.vue

perf:  Cancel automatic closure of debugging dialog

---

ui/src/workflow/common/NodeCascader.vue
ui/src/workflow/common/app-node.ts
ui/src/workflow/common/edge.ts
ui/src/workflow/index.vue

perf: Workflow Canvas Rendering

perf: Workflow Canvas Rendering

---

ui/src/workflow/nodes/form-node/index.vue

fix: The node cannot respond after adding fields to the form node

fix: The node cannot respond after adding fields to the form node

---

apps/application/chat_pipeline/step/chat_step/impl/base_chat_step.py
apps/application/flow/step_node/ai_chat_step_node/impl/base_chat_node.py
apps/application/flow/tools.py
ui/src/api/type/application.ts

fix: Lost content during the answering process

fix: Lost content during the answering process

---

apps/application/flow/step_node/ai_chat_step_node/impl/base_chat_node.py
apps/application/flow/step_node/question_node/impl/base_question_node.py

fix: AI dialogue context removes form data

fix: AI dialogue context removes form data

---

ui/src/views/dataset/component/UploadComponent.vue

fix: Mac upload folder error

---

ui/src/views/login/components/dingtalkQrCode.vue

fix: No error message prompted after QR code failure  --bug=1052150 --user=王孝刚 【系统设置】钉钉二维码失效后，点击刷新，使用非当前组织的用户扫码登录，没有弹错误提示 https://www.tapd.cn/57709429/s/1653901

fix: No error message prompted after QR code failure

---

apps/setting/models_provider/impl/base_chat_open_ai.py

perf: Add custom token_ids method

perf: Add custom token_ids method

---

apps/common/handle/impl/table/xlsx_parse_table_handle.py

fix: Fix excel merge cells header

fix: Fix excel merge cells header

---

ui/src/components/ai-chat/component/chat-input-operate/index.vue

feat: audio support m4a  --story=1017864 --user=王孝刚 【应用】上传音频文件类型中支持m4a类型 #2276 https://www.tapd.cn/57709429/s/1654257

feat: audio support m4a

---

apps/application/flow/step_node/application_node/i_application_node.py
apps/application/flow/step_node/application_node/impl/base_application_node.py

fix: Defect of embedding application parameters as empty and reporting errors  --bug=1052184 --user=王孝刚 【github#2273】【应用】-有非必填接口传参的编排应用，作为节点加入新的编排应用后，接口传参为空时对话报错 https://www.tapd.cn/57709429/s/1654259

fix: Defect of embedding application parameters as empty and reporting errors

---

apps/function_lib/serializers/function_lib_serializer.py
apps/setting/serializers/provider_serializers.py
ui/src/views/team/component/PermissionSetting.vue

refactor: Search ignores capitalization  --story=1017866 --user=王孝刚 【Bug转需求】【搜索】-函数库、模型、团队成员界面搜索不支持忽略大小写 #2126 https://www.tapd.cn/57709429/s/1654282

refactor: Search ignores capitalization

---

apps/dataset/serializers/document_serializers.py
ui/src/views/document/index.vue

feat: Support sorting feat for knowledge base documents  --story=1017634 --user=刘瑞斌 知识库文档列表排序功能，可以根据各列属性排序 https://www.tapd.cn/57709429/s/1654419

feat: Support sorting feat for knowledge base documents

---

apps/function_lib/serializers/function_lib_serializer.py
apps/function_lib/swagger_api/function_lib_api.py
apps/function_lib/urls.py
apps/function_lib/views/function_lib_views.py
ui/src/api/function-lib.ts
ui/src/locales/lang/en-US/views/function-lib.ts
ui/src/locales/lang/zh-CN/views/function-lib.ts
ui/src/locales/lang/zh-Hant/views/function-lib.ts
ui/src/views/function-lib/index.vue

feat: Import and Export function lib

feat: Import and Export function lib

---

apps/dataset/serializers/document_serializers.py
apps/dataset/task/generate.py
apps/setting/models_provider/impl/xinference_model_provider/model/image.py
apps/setting/models_provider/impl/xinference_model_provider/model/llm.py
ui/src/components/generate-related-dialog/index.vue

feat: Generate problem support for generating unfinished paragraphs

feat: Generate problem support for generating unfinished paragraphs

---

apps/application/serializers/chat_message_serializers.py
apps/dataset/serializers/file_serializers.py

refactor: Support image_list, document_list while using swagger api  --story=1017867 --user=刘瑞斌 对话API支持上传文件、语音、图像和视频，用于实现maxkb的文件解析及多模态对话#2228 https://www.tapd.cn/57709429/s/1654842

refactor: Support image_list, document_list while using swagger api

---

ui/src/views/chat/embed/index.vue
ui/src/views/chat/pc/index.vue

feat: Chat page retains the display of the last conversation

---

apps/setting/models_provider/impl/aliyun_bai_lian_model_provider/model/llm.py
apps/setting/models_provider/impl/aliyun_bai_lian_model_provider/model/stt.py

fix: Alibaba Cloud full modal docking error  --bug=1052232 --user=王孝刚 【模型设置】-大语言模型/语音识别模型 对接不上阿里云的全模态模型 https://www.tapd.cn/57709429/s/1655034

fix: Alibaba Cloud full modal docking error

---

ui/src/locales/lang/en-US/views/system.ts
ui/src/locales/lang/zh-CN/views/system.ts
ui/src/locales/lang/zh-Hant/views/system.ts
ui/src/views/authentication/component/OIDC.vue
ui/src/views/login/index.vue

refactor: oidc add scope

---

apps/application/flow/step_node/condition_node/impl/base_condition_node.py

feat: The discriminator supports variables

feat: The discriminator supports variables

---

ui/src/components/markdown/MdEditorMagnify.vue

perf: Close editor save content

---

apps/application/flow/step_node/reranker_node/impl/base_reranker_node.py
ui/src/components/ai-chat/ExecutionDetailDialog.vue
ui/src/components/ai-chat/ParagraphSourceDialog.vue
ui/src/components/ai-chat/component/ParagraphCard.vue
ui/src/components/card-box/index.vue
ui/src/styles/app.scss

refactor: Multi channel recall, adding display of knowledge base titles and other information

refactor: Multi channel recall, adding display of knowledge base titles and other information

---

apps/setting/models_provider/impl/base_chat_open_ai.py

fix: Tokens cannot be obtained from the model dialogue

fix: Tokens cannot be obtained from the model dialogue

---

ui/src/components/ai-chat/component/answer-content/index.vue

fix: Dialogue image cannot be enlarged

fix: Dialogue image cannot be enlarged

---

ui/src/views/chat/embed/index.vue

When embedding with `http://localhost:3000/ui/chat/{token}?mode=embed` into a third party, there should be no space left in the top right corner. The position of the history button is incorrect. I expect the display to be optimized for standalone embedding.
I've added a route parameter `?mode=embed&popup=no` to determine whether the content is displayed in a popup. There is no impact on the Floating Mode.
```plain
http://localhost:3000/ui/chat/{token}?mode=embed
http://localhost:3000/ui/chat/{token}?mode=embed&popup=no
```

perf: optimize embed mode

---

apps/common/util/function_code.py

fix: Function library execution role group

fix: Function library execution role group

---

apps/application/models/application.py

fix: Workflow execution decimal cannot be serialized

fix: Workflow execution decimal cannot be serialized

---

apps/setting/models_provider/impl/vllm_model_provider/model/image.py

fix: Remove vllm image cache  --bug=1052365 --user=刘瑞斌 【github#2353】vllm视觉模型修改最大tokens不生效 https://www.tapd.cn/57709429/s/1657667

fix: Remove vllm image cache

---

apps/application/swagger_api/application_api.py

docs: Create an application and add workflow parameters

docs: Create an application and add workflow parameters

---

ui/src/locales/lang/en-US/views/application.ts
ui/src/locales/lang/zh-CN/views/application.ts
ui/src/locales/lang/zh-Hant/views/application.ts
ui/src/views/application/component/CreateApplicationDialog.vue
ui/src/workflow/common/data.ts

feat: Create workflow applications that support template selection

---

ui/src/components/ai-chat/component/operation-button/ChatOperationButton.vue
ui/src/components/ai-chat/component/operation-button/LogOperationButton.vue
ui/src/views/chat/pc/index.vue

fix: Fix browser text to speech cannot resume and cancel  --bug=1052345 --user=刘瑞斌 【github#2352】【应用】使用浏览器内置TTS，切换历史记录内容播放会没有声音 https://www.tapd.cn/57709429/s/1657771

fix: Fix browser text to speech cannot resume and cancel

---

pyproject.toml

fix: The locally loaded vector model is missing the libGL.so library

fix: The locally loaded vector model is missing the libGL.so library

---

apps/application/flow/step_node/variable_assign_node/impl/base_variable_assign_node.py
ui/src/workflow/nodes/variable-assign-node/index.vue

refactor: Support string,json,num types

refactor: Support string,json,num types

---

apps/common/handle/impl/response/openai_to_response.py

feat: The OpenAI interface supports the thought process

feat: The OpenAI interface supports the thought process

---

ui/src/views/function-lib/index.vue

fix: Fix add function lib error  --bug=1052403 --user=刘瑞斌 【函数库】-创建函数失败 https://www.tapd.cn/57709429/s/1658691  --bug=1052404 --user=刘瑞斌 【函数库】新建函数，无法添加参数 https://www.tapd.cn/57709429/s/1658693

fix: Fix add function lib error

---

apps/setting/serializers/team_serializers.py

fix: When adding members in bulk, existing members will be automatically passed in, do not affect the joining of other members #2351

fix: When adding members in bulk, existing members will be automatically passed in, do not affect the joining of other members #2351

---

apps/dataset/serializers/file_serializers.py

fix: File upload failed

---

ui/src/workflow/nodes/base-node/component/FileUploadSettingDialog.vue

fix: The audio file does not display M4A  --bug=1052445 --user=王孝刚 【编排应用】基本信息的上传文件界面，音频文件中没有显示M4A格式 https://www.tapd.cn/57709429/s/1658969

fix: The audio file does not display M4A

---

apps/dataset/serializers/document_serializers.py
apps/dataset/sql/list_document.sql

fix: the error in obtaining the document list

fix: the error in obtaining the document list

---

apps/dataset/serializers/document_serializers.py

fix: When generating a problem, the generated data is incorrect

fix: When generating a problem, the generated data is incorrect

---

ui/src/components/ai-chat/component/user-form/index.vue

fix: URL encoding parameters not decompiled

fix: URL encoding parameters not decompiled

---

apps/dataset/serializers/document_serializers.py
apps/dataset/serializers/paragraph_serializers.py

fix: Paragraph list unsorted

---

apps/setting/models_provider/impl/vllm_model_provider/credential/llm.py

fix: VLLM Supplier Dialogue Verification

fix: VLLM Supplier Dialogue Verification

---

ui/src/views/function-lib/component/FunctionDebugDrawer.vue

fix: Resolve the issue of a function returning 0 as a result (#2389)

---

ui/src/components/ai-chat/component/control/index.vue

fix: Left click to copy incomplete content

fix: Left click to copy incomplete content

---

apps/dataset/serializers/document_serializers.py

fix: Import zip report error

---

ui/src/workflow/nodes/variable-assign-node/index.vue

fix: Fix variable-assign-node cannot publish  --bug=1052464 --user=刘瑞斌 【应用】-编排应用中存在变量赋值节点，发布应用失败 https://www.tapd.cn/57709429/s/1659401

fix: Fix variable-assign-node cannot publish

---

apps/common/middleware/gzip.py
apps/smartdoc/settings/base.py

 perf: enable gzip.

---

apps/application/flow/step_node/image_generate_step_node/impl/base_image_generate_node.py

refactor: Support the generated images horizontal tiling display  --story=1017907 --user=刘瑞斌 【越秀农牧】图片生成节点，生成的图片，希望可以支持横向平铺展示 https://www.tapd.cn/57709429/s/1659636

refactor: Support the generated images horizontal tiling display

---

apps/application/flow/step_node/variable_assign_node/impl/base_variable_assign_node.py

fix: Fix variable assign num not working  --bug=1052497 --user=刘瑞斌 【变量赋值】-将全局变量赋值为num类型，输出时报错 https://www.tapd.cn/57709429/s/1659733

fix: Fix variable assign num not working

---

apps/application/flow/workflow_manage.py
apps/common/middleware/gzip.py

fix: The workflow cannot function properly after the conversation flow is disconnected

fix: The workflow cannot function properly after the conversation flow is disconnected

---

ui/src/components/dynamics-form/constructor/data.ts
ui/src/components/dynamics-form/constructor/items/PasswordInputConstructor.vue
ui/src/locales/lang/en-US/dynamics-form.ts
ui/src/locales/lang/zh-CN/dynamics-form.ts
ui/src/locales/lang/zh-Hant/dynamics-form.ts
ui/src/workflow/nodes/base-node/component/UserFieldFormDialog.vue
ui/src/workflow/nodes/base-node/component/UserInputFieldTable.vue

refactor: Password input constractor

refactor: Password input constractor

---

ui/src/components/ai-chat/component/operation-button/ChatOperationButton.vue

refactor: Cancel last autoplay audio  --story=1017953 --user=刘瑞斌 【优化】多轮对话，语音识别自动播放，会重叠播放 https://www.tapd.cn/57709429/s/1660001

refactor: Cancel last autoplay audio

---

ui/src/locales/lang/en-US/common.ts
ui/src/locales/lang/en-US/views/application-workflow.ts
ui/src/locales/lang/zh-CN/common.ts
ui/src/locales/lang/zh-CN/views/application-workflow.ts
ui/src/locales/lang/zh-Hant/common.ts
ui/src/locales/lang/zh-Hant/views/application-workflow.ts
ui/src/workflow/common/NodeContainer.vue
ui/src/workflow/nodes/variable-assign-node/index.vue

perf: Optimization of modifying node names in workflow

---

apps/application/flow/step_node/document_extract_node/impl/base_document_extract_node.py

fix: Sending error when extracting multiple forms and documents in the workflow

fix: Sending error when extracting multiple forms and documents in the workflow

---

apps/application/flow/step_node/search_dataset_node/i_search_dataset_node.py
ui/src/components/ai-chat/component/answer-content/index.vue

fix: Changing the answer does not take effect

fix: Changing the answer does not take effect

---

apps/application/views/chat_views.py
apps/dataset/serializers/file_serializers.py

fix: swagger show more args

---

ui/src/components/logo/LogoFull.vue
ui/src/router/index.ts
ui/src/styles/app.scss
ui/src/views/application/component/ParamSettingDialog.vue
ui/src/views/hit-test/index.vue
ui/src/views/login/index.vue
ui/src/workflow/nodes/reranker-node/ParamSettingDialog.vue

Pr@main/xpack login

---

ui/src/views/document/index.vue

fix: Document name sorting

---

ui/src/components/codemirror-editor/index.vue
ui/src/views/function-lib/component/FunctionFormDrawer.vue
ui/src/workflow/icons/variable-assign-node-icon.vue
ui/src/workflow/nodes/function-node/index.vue
ui/src/workflow/nodes/variable-assign-node/index.vue

perf: optimization codemirror component

---

apps/function_lib/serializers/function_lib_serializer.py
ui/src/api/function-lib.ts

refactor: rename function lib export subfix  --bug=1052638 --user=刘瑞斌 函数库导出后缀名优化 https://www.tapd.cn/57709429/s/1660837

refactor: rename function lib export subfix

---

ui/src/views/document/index.vue

fix: After generating the problem, jump to the first page

fix: After generating the problem, jump to the first page

---

ui/src/workflow/nodes/base-node/component/UserInputFieldTable.vue

fix: Fix user input table title not changed  --bug=1052676 --user=刘瑞斌 【应用】高级编排-设置-基本信息-修改用户输入标题后保存-未更新-再次进入后仍展示用户输入 https://www.tapd.cn/57709429/s/1661083

fix: Fix user input table title not changed

---

apps/application/chat_pipeline/step/chat_step/impl/base_chat_step.py
apps/application/flow/workflow_manage.py
apps/common/util/test.py

feat: Non streaming response answers_list

feat: Non streaming response answers_list

---

ui/src/views/team/index.vue

fix: member list does not support ignoring case  --bug=1052688 --user=王孝刚 【团队成员】成员列表搜索不支持忽略大小写 https://www.tapd.cn/57709429/s/1661230

fix: member list does not support ignoring case

---

ui/src/components/dynamics-form/index.vue

fix: Fix default_value not show when image model changed  --bug=1052695 --user=刘瑞斌 【应用】高级编排-设置-图片生成组件-切换模型后图片尺寸为空-未同步切换到当前模型的首个尺寸 https://www.tapd.cn/57709429/s/1661346

fix: Fix default_value not show when image model changed

---

ui/src/components/ai-chat/index.vue
ui/src/components/dynamics-form/index.vue
ui/src/views/application/component/AIModeParamSettingDialog.vue

fix: Fixed the default value of not selecting 'select' after switching models

fix: Fixed the default value of not selecting 'select' after switching models

---

apps/application/serializers/chat_serializers.py
apps/application/swagger_api/chat_api.py
apps/locales/en_US/LC_MESSAGES/django.po
apps/locales/zh_CN/LC_MESSAGES/django.po
apps/locales/zh_Hant/LC_MESSAGES/django.po

fix: Retrieve the dialogue record list document and confirm the parameters

fix: Retrieve the dialogue record list document and confirm the parameters

---

ui/src/views/chat/embed/index.vue
ui/src/views/chat/pc/EditTitleDialog.vue
ui/src/views/chat/pc/index.vue

fix: The page cannot continue streaming response when changing the conversation name in the conversation reply

fix: The page cannot continue streaming response when changing the conversation name in the conversation reply

---

apps/dataset/serializers/document_serializers.py
apps/dataset/template/csv_template_en.csv

fix: csvTemplate error  --bug=1052711 --user=王孝刚 【知识库】英文模式-文档-QA问答对-下载的csv模版内容错误 https://www.tapd.cn/57709429/s/1661565

fix: csvTemplate error

---

apps/application/serializers/application_serializers.py

fix: The newly created simple application dialogue process label is not effective

fix: The newly created simple application dialogue process label is not effective

---

apps/setting/models_provider/impl/qwen_model_provider/model/image.py
apps/setting/models_provider/impl/qwen_model_provider/model/llm.py

refactor: update QwenChatModel to use BaseChatOpenAI and remove unused methods  --bug=1052269 --user=刘瑞斌 【模型】对接千问模型，设置联网参数，maxkb对答不生效。通过python代码调用是可以的。 https://www.tapd.cn/57709429/s/1662132

refactor: update QwenChatModel to use BaseChatOpenAI and remove unused methods

---

apps/application/serializers/application_serializers.py
apps/dataset/serializers/dataset_serializers.py

fix: Reference segmentation limit

fix: Reference segmentation limit

---

apps/application/flow/step_node/application_node/impl/base_application_node.py
apps/common/handle/impl/response/openai_to_response.py

fix: Enterprise WeChat docking sub application cannot output thinking process

fix: Enterprise WeChat docking sub application cannot output thinking process

---

ui/src/components/ai-chat/component/chat-input-operate/index.vue

When reading the source code of chat-input-operate component, I found the strange variable name isDisabledChart. I think the correct name should be isDisabledChat.

fix: rename isDisabledChart to isDisabledChat in chat-input-operate

---

ui/src/layout/components/top-bar/avatar/APIKeyDialog.vue
ui/src/locales/lang/en-US/views/team.ts
ui/src/locales/lang/zh-CN/views/team.ts
ui/src/locales/lang/zh-Hant/views/team.ts
ui/src/views/application-overview/component/APIKeyDialog.vue
ui/src/views/application-overview/component/LimitDialog.vue
ui/src/views/application-overview/component/SettingAPIKeyDialog.vue
ui/src/views/dataset/component/ParagraphList.vue
ui/src/views/dataset/index.vue
ui/src/views/document/index.vue
ui/src/views/function-lib/index.vue
ui/src/views/paragraph/index.vue
ui/src/views/problem/index.vue
ui/src/views/team/index.vue
ui/src/views/template/component/ModelCard.vue
ui/src/views/user-manage/index.vue
ui/src/workflow/common/NodeContainer.vue
ui/src/workflow/common/shortcut.ts

perf: Unified deletion confirmation button

---

ui/src/workflow/nodes/base-node/component/UserInputFieldTable.vue

fix: simplify inputFieldConfig handling in UserInputFieldTable  --bug=1052676 --user=刘瑞斌 【应用】高级编排-设置-基本信息-修改用户输入标题后保存-未更新-再次进入后仍展示用户输入 https://www.tapd.cn/57709429/s/1662577

fix: simplify inputFieldConfig handling in UserInputFieldTable

---

apps/application/chat_pipeline/step/chat_step/impl/base_chat_step.py

fix: Workflow embedding sub application thinking process switch cannot control thinking process output

fix: Workflow embedding sub application thinking process switch cannot control thinking process output

---

ui/src/locales/lang/en-US/views/team.ts
ui/src/locales/lang/zh-CN/views/team.ts
ui/src/locales/lang/zh-Hant/views/team.ts

fix: Team management remove button nationalization

fix: Team management remove button nationalization

---

apps/dataset/task/sync.py

fix: When importing documents from a web knowledge base, if a failed document is encountered, the import will be interrupted

fix: When importing documents from a web knowledge base, if a failed document is encountered, the import will be interrupted

---

apps/application/flow/workflow_manage.py

fix: Having the same suffix for function node names can result in incorrect value retrieval

fix: Having the same suffix for function node names can result in incorrect value retrieval

---

apps/application/chat_pipeline/step/chat_step/impl/base_chat_step.py

fix: Simple application model dialogue model error not returned

fix: Simple application model dialogue model error not returned

---

ui/src/workflow/nodes/base-node/component/ApiInputFieldTable.vue
ui/src/workflow/nodes/form-node/index.vue

perf: Form node support adjusting the order

---

ui/src/components/ai-chat/KnowledgeSource.vue
ui/src/components/ai-chat/component/answer-content/index.vue
ui/src/styles/element-plus.scss
ui/src/views/application-overview/component/EditAvatarDialog.vue
ui/src/views/hit-test/index.vue
ui/src/workflow/nodes/variable-assign-node/index.vue

Pr@main/perf style

---

ui/src/locales/lang/zh-CN/views/function-lib.ts
ui/src/locales/lang/zh-Hant/views/function-lib.ts
ui/src/utils/application.ts
ui/src/views/application/component/ParamSettingDialog.vue
ui/src/views/function-lib/component/EditAvatarDialog.vue
ui/src/views/function-lib/component/FunctionFormDrawer.vue
ui/src/views/function-lib/component/PermissionDialog.vue
ui/src/views/function-lib/index.vue

feat: Update function setting style

---

ui/src/workflow/common/app-node.ts

fix: Adjustment of workflow node name auto increment rule(#2562)

---

apps/application/flow/step_node/function_lib_node/impl/base_function_lib_node.py
apps/function_lib/serializers/function_lib_serializer.py

refactor: Improve parameter handling in function execution

refactor: Improve parameter handling in function execution

---

apps/application/flow/step_node/function_lib_node/impl/base_function_lib_node.py
apps/application/flow/step_node/function_node/impl/base_function_node.py

fix: The float values collected by the form will be treated as ints when the decimal part is 0, resulting in a type error

fix: The float values collected by the form will be treated as ints when the decimal part is 0, resulting in a type error

---

ui/src/api/operate-log.ts
ui/src/locales/lang/en-US/views/index.ts
ui/src/locales/lang/en-US/views/operate-log.ts
ui/src/locales/lang/zh-CN/views/index.ts
ui/src/locales/lang/zh-CN/views/operate-log.ts
ui/src/locales/lang/zh-Hant/views/index.ts
ui/src/locales/lang/zh-Hant/views/operate-log.ts
ui/src/router/modules/setting.ts
ui/src/views/operate-log/component/DetailDialog.vue
ui/src/views/operate-log/index.vue

feat: Add Operate Log

---

apps/common/handle/impl/doc_split_handle.py
apps/common/util/split_model.py

perf: Enhance Word parsing

---

apps/function_lib/migrations/0003_functionlib_function_type_functionlib_icon_and_more.py
apps/function_lib/serializers/function_lib_serializer.py
apps/function_lib/views/function_lib_views.py
ui/src/api/function-lib.ts
ui/src/views/function-lib/component/AddInternalFunctionDialog.vue
ui/src/views/function-lib/index.vue

feat: Add functionality to create and manage internal functions with MySQL and PostgreSQL queries

feat: Add functionality to create and manage internal functions with MySQL and PostgreSQL queries

---

apps/common/log/log.py

fix: Logging error for logged in user

fix: Logging error for logged in user

---

ui/src/components/ai-chat/KnowledgeSource.vue
ui/src/components/ai-chat/component/answer-content/index.vue
ui/src/components/ai-chat/component/operation-button/ChatOperationButton.vue
ui/src/components/ai-chat/component/operation-button/index.vue

fix: Optimize small screen dialogue style

---

apps/application/chat_pipeline/step/chat_step/impl/base_chat_step.py

fix: Simple application user did not successfully set up

fix: Simple application user did not successfully set up

---

ui/src/api/operate-log.ts
ui/src/views/operate-log/index.vue

feat: add operate log ui

---

ui/src/api/type/application.ts
ui/src/components/ai-chat/component/operation-button/ChatOperationButton.vue
ui/src/components/ai-chat/component/operation-button/index.vue
ui/src/components/ai-chat/index.vue

Stream tts

---

ui/src/views/function-lib/index.vue

fix: conditionally render user selection for public function type  --bug=1053743 --user=刘瑞斌 【需求转缺陷】【内置函数】- 去掉按创建用户的搜索选项 https://www.tapd.cn/57709429/s/1675143

fix: conditionally render user selection for public function type

---

ui/src/components/ai-chat/component/user-form/index.vue
ui/src/views/application/component/ReasoningParamSettingDialog.vue

fix: When asker is empty, do not pass the current parameter

fix: When asker is empty, do not pass the current parameter

---

apps/application/flow/step_node/__init__.py
apps/application/flow/step_node/ai_chat_step_node/i_chat_node.py
apps/application/flow/step_node/ai_chat_step_node/impl/base_chat_node.py
apps/application/flow/step_node/mcp_node/__init__.py
apps/application/flow/step_node/mcp_node/i_mcp_node.py
apps/application/flow/step_node/mcp_node/impl/__init__.py
apps/application/flow/step_node/mcp_node/impl/base_mcp_node.py
apps/application/serializers/application_serializers.py
apps/application/urls.py
apps/application/views/application_views.py
ui/src/api/application.ts
ui/src/components/ai-chat/ExecutionDetailDialog.vue
ui/src/enums/workflow.ts
ui/src/locales/lang/en-US/views/application-workflow.ts
ui/src/locales/lang/zh-CN/views/application-workflow.ts
ui/src/locales/lang/zh-Hant/views/application-workflow.ts
ui/src/views/application/component/McpServersDialog.vue
ui/src/workflow/common/data.ts
ui/src/workflow/icons/mcp-node-icon.vue
ui/src/workflow/nodes/ai-chat-node/index.vue
ui/src/workflow/nodes/mcp-node/index.ts
ui/src/workflow/nodes/mcp-node/index.vue

Support MCP

---

ui/src/components/ai-chat/component/operation-button/ChatOperationButton.vue

fix: Limit the number of retries for text to speech conversion

fix: Limit the number of retries for text to speech conversion

---

ui/src/locales/lang/en-US/views/application.ts
ui/src/locales/lang/en-US/views/dataset.ts
ui/src/views/dataset/component/CreateDatasetDialog.vue

fix: lark document i18n error  --bug=1053850 --user=王孝刚 [知识库]英文语言模式-添加飞书文档页面未国际化&提示的翻译错误 https://www.tapd.cn/57709429/s/1675482

fix: lark document i18n error

---

ui/src/views/dataset/index.vue

fix: lark document icon error  --bug=1053854 --user=王孝刚 【飞书】-创建完飞书知识库后，面板中飞书的icon未变 https://www.tapd.cn/57709429/s/1675539

fix: lark document icon error

---

ui/src/views/function-lib/component/FunctionFormDrawer.vue

fix: function add required  --bug=1053859 --user=王孝刚 【函数库】函数内容给出必填提示 https://www.tapd.cn/57709429/s/1675529

fix: function add required

---

ui/src/assets/fx/bochaai/detail.md
ui/src/assets/fx/google_search/detail.md
ui/src/assets/fx/langsearch/detail.md
ui/src/components/ai-chat/component/chat-input-operate/index.vue
ui/src/components/ai-chat/component/user-form/index.vue
ui/src/components/ai-chat/index.vue
ui/src/layout/components/sidebar/SidebarItem.vue
ui/src/views/function-lib/index.vue
ui/src/workflow/common/NodeControl.vue
ui/src/workflow/icons/function-lib-node-icon.vue
ui/src/workflow/nodes/ai-chat-node/index.vue
ui/src/workflow/nodes/mcp-node/index.vue

perf: refine user input style

---

apps/common/handle/impl/zip_split_handle.py

fix: Zip with title cannot be parsed

fix: Zip with title cannot be parsed

---

apps/application/flow/step_node/mcp_node/impl/base_mcp_node.py
ui/src/workflow/nodes/mcp-node/index.vue

feat: enhance form handling with dynamic input fields and reference content retrieval

feat: enhance form handling with dynamic input fields and reference content retrieval

---

ui/src/components/ai-chat/component/operation-button/ChatOperationButton.vue

fix: Voice playback may cause playback issues

fix: Voice playback may cause playback issues

---

ui/src/components/ai-chat/index.vue
ui/src/locales/lang/en-US/views/application.ts

perf: Prompt word alignment issue(#2537)

---

apps/common/log/log.py
apps/users/views/user.py

fix: Audit log login did not record user

fix: Audit log login did not record user

---

ui/src/components/ai-chat/component/chat-input-operate/index.vue

perf: Optimize pressing enter to line breaks on mobile

---

apps/common/util/split_model.py

fix: Segmented filtering of paragraphs with empty parent title content

fix: Segmented filtering of paragraphs with empty parent title content

---

apps/application/flow/step_node/mcp_node/impl/base_mcp_node.py

fix: ensure tool parameters are properly handled by reloading JSON  --bug=1053980 --user=刘瑞斌 【应用】MCP节点的工具参数引用参数时，对话过程中参数值发生变化，MCP节点没有获取最新的参数值 https://www.tapd.cn/57709429/s/1676830

fix: ensure tool parameters are properly handled by reloading JSON

---

ui/src/components/ai-chat/ExecutionDetailDialog.vue
ui/src/components/ai-chat/component/chat-input-operate/index.vue
ui/src/components/card-checkbox/index.vue
ui/src/layout/components/breadcrumb/index.vue
ui/src/styles/element-plus.scss
ui/src/views/application-overview/component/EditAvatarDialog.vue
ui/src/views/application-overview/component/XPackDisplaySettingDialog.vue
ui/src/views/application/ApplicationSetting.vue
ui/src/views/application/component/AIModeParamSettingDialog.vue
ui/src/views/application/component/AddDatasetDialog.vue
ui/src/views/application/component/McpServersDialog.vue
ui/src/views/application/component/ParamSettingDialog.vue
ui/src/views/application/component/TTSModeParamSettingDialog.vue
ui/src/views/document/component/EmbeddingContentDialog.vue
ui/src/views/document/component/SelectDatasetDialog.vue
ui/src/views/function-lib/component/EditAvatarDialog.vue
ui/src/views/function-lib/component/PermissionDialog.vue
ui/src/views/log/component/EditContentDialog.vue
ui/src/views/log/index.vue
ui/src/views/paragraph/component/SelectDocumentDialog.vue
ui/src/workflow/nodes/search-dataset-node/index.vue

fix: Update lark icon and dialog style

---

ui/src/components/dynamics-form/index.vue

fix: update option list search logic to handle string and array form_data values  --bug=1053919 --user=刘瑞斌 【函数库】非必填启动参数开启启动参数后再次编辑多选置空 https://www.tapd.cn/57709429/s/1677136

fix: update option list search logic to handle string and array form_data values

---

ui/src/components/ai-chat/component/chat-input-operate/index.vue
ui/src/components/ai-chat/component/transition-content/index.vue
ui/src/components/ai-chat/index.vue
ui/src/locales/lang/en-US/ai-chat.ts
ui/src/locales/lang/zh-CN/ai-chat.ts
ui/src/locales/lang/zh-Hant/ai-chat.ts

feat: Support converting text prompts

feat: Support converting text prompts

---

apps/application/views/chat_views.py
apps/dataset/views/document.py
apps/dataset/views/image.py
apps/dataset/views/paragraph.py
apps/dataset/views/problem.py
apps/locales/en_US/LC_MESSAGES/django.po
apps/locales/zh_CN/LC_MESSAGES/django.po
apps/locales/zh_Hant/LC_MESSAGES/django.po
apps/setting/views/Team.py
apps/users/views/user.py

refactor: log menu

---

ui/src/views/dataset/ImportDocumentDataset.vue

fix: Defects that can be saved multiple times  --bug=1054039 --user=王孝刚 【飞书知识库】-导入文档时，快速点击开始导入按钮，会触发多次import请求，并且会跳离文档列表页 https://www.tapd.cn/57709429/s/1677588

fix: Defects that can be saved multiple times

---

ui/public/fx/langsearch/detail.md
ui/src/components/ai-chat/component/chat-input-operate/index.vue
ui/src/components/ai-chat/component/user-form/index.vue
ui/src/components/ai-chat/index.vue
ui/src/views/function-lib/index.vue

Pr@main/user input

---

ui/src/components/ai-chat/component/chat-input-operate/TouchChat.vue
ui/src/components/ai-chat/component/chat-input-operate/index.vue
ui/src/components/ai-chat/index.vue

perf: Optimize voice recording

perf: Optimize voice recording

---

ui/public/fx/google_search/detail.md

fix: Fix markdown text

---

apps/application/views/application_views.py
apps/application/views/chat_views.py
apps/locales/en_US/LC_MESSAGES/django.po
apps/locales/zh_CN/LC_MESSAGES/django.po
apps/locales/zh_Hant/LC_MESSAGES/django.po
ui/src/views/operate-log/index.vue

refactor: Optimization of operation menu  --bug=1054069 --user=王孝刚 【操作日志】-操作菜单优化建议 https://www.tapd.cn/57709429/s/1677900

refactor: Optimization of operation menu

---

ui/src/components/ai-chat/component/chat-input-operate/index.vue

perf: Optimization of recording function on mobile devices

perf: Optimization of recording function on mobile devices

---

apps/common/event/listener_manage.py

fix: Every time a vectorized document is generated, the entire vectorized data of the document is deleted

fix: Every time a vectorized document is generated, the entire vectorized data of the document is deleted

---

ui/src/views/operate-log/index.vue

refactor: log add hover  --bug=1054088 --user=王孝刚 【操作日志】优化-操作详情建议一行展示，提供hover功能，hover后展示全部详情 https://www.tapd.cn/57709429/s/1678006

refactor: log add hover

---

ui/src/locales/lang/en-US/views/function-lib.ts
ui/src/locales/lang/zh-CN/views/function-lib.ts
ui/src/locales/lang/zh-Hant/views/function-lib.ts
ui/src/views/function-lib/component/AddInternalFunctionDialog.vue
ui/src/views/function-lib/index.vue

feat: Internal function can modify names

---

ui/src/locales/lang/en-US/views/document.ts
ui/src/locales/lang/zh-CN/views/document.ts
ui/src/locales/lang/zh-Hant/views/document.ts
ui/src/views/dataset/ImportDocumentDataset.vue

fix: import add warning  --bug=1054090 --user=王孝刚 【知识库】飞书知识库-导入文档-未选择导入文件时，导入有提示信息 https://www.tapd.cn/57709429/s/1678039

fix: import add warning

---

ui/src/components/ai-chat/component/operation-button/ChatOperationButton.vue
ui/src/components/ai-chat/index.vue

fix: Fix some phones unable to play audio

fix: Fix some phones unable to play audio

---

ui/src/locales/lang/en-US/views/document.ts
ui/src/locales/lang/zh-CN/views/document.ts
ui/src/locales/lang/zh-Hant/views/document.ts
ui/src/views/dataset/ImportDocumentDataset.vue

fix: import add warning  --bug=1054090 --user=王孝刚 【知识库】飞书知识库-导入文档-未选择导入文件时，导入有提示信息 https://www.tapd.cn/57709429/s/1678039<br>refactor: lark

refactor: lark

---

apps/dataset/serializers/common_serializers.py

fix: Fix some knowledge base import errors

fix: Fix some knowledge base import errors

---

apps/dataset/serializers/document_serializers.py

fix: Processing for document export sheet with more than 32 characters

fix: Processing for document export sheet with more than 32 characters

---

apps/application/serializers/application_serializers.py
ui/src/workflow/nodes/application-node/index.vue

fix: Application deleted, workflow page error reported

fix: Application deleted, workflow page error reported

---

ui/src/views/application/ApplicationSetting.vue
ui/src/views/log/component/EditContentDialog.vue
ui/src/views/log/index.vue
ui/src/views/paragraph/component/SelectDocumentDialog.vue
ui/src/workflow/nodes/search-dataset-node/index.vue

fix: knowledge icon error

---

ui/src/components/ai-chat/component/chat-input-operate/index.vue

fix: When uploading files during application dialogue, there are special whitespace characters and file name parsing errors

fix: When uploading files during application dialogue, there are special whitespace characters and file name parsing errors

---

apps/common/handle/impl/zip_split_handle.py

fix: garbled zip import file names

fix: garbled zip import file names

---

ui/src/views/application-workflow/index.vue
ui/src/views/application/ApplicationSetting.vue

fix: chat avatar display problem

---

apps/common/middleware/doc_headers_middleware.py
apps/smartdoc/settings/base.py
ui/vite.config.ts

feat: doc auth

---

ui/src/views/function-lib/component/FunctionFormDrawer.vue

feat: function field form support sort

---

apps/dataset/serializers/common_serializers.py
apps/dataset/serializers/dataset_serializers.py
apps/dataset/task/generate.py
apps/dataset/urls.py
apps/dataset/views/dataset.py
apps/locales/en_US/LC_MESSAGES/django.po
apps/locales/zh_CN/LC_MESSAGES/django.po
apps/locales/zh_Hant/LC_MESSAGES/django.po
ui/src/api/dataset.ts
ui/src/components/generate-related-dialog/index.vue
ui/src/views/dataset/index.vue

feat: Knowledge base generation problem

feat: Knowledge base generation problem

---

ui/src/views/function-lib/index.vue

refactor: conditionally render dropdown item based on init_field_list length  --bug=1054160 --user=刘瑞斌 【函数库】没有启用参数的函数，不展示启动参数按钮 https://www.tapd.cn/57709429/s/1678874<br>refactor: convert getList and getUserList functions to async for improved handling of asynchronous operations  --bug=1054152 --user=刘瑞斌 【函数库】筛选“我的”函数后刷新页面，还是显示的全部函数 https://www.tapd.cn/57709429/s/1678876

refactor: convert getList and getUserList functions to async for improved handling of asynchronous operations

---

ui/src/components/ai-chat/component/chat-input-operate/index.vue
ui/src/components/dynamics-form/items/select/MultiSelect.vue
ui/src/views/application-overview/component/XPackDisplaySettingDialog.vue
ui/src/views/hit-test/index.vue
ui/src/workflow/nodes/base-node/component/UserInputFieldTable.vue

perf: Optimize some style issues

---

apps/common/util/ts_vecto_util.py
apps/embedding/vector/pg_vector.py

perf: Optimize word segmentation retrieval

perf: Optimize word segmentation retrieval

---

ui/src/components/ai-chat/component/chat-input-operate/TouchChat.vue
ui/src/components/ai-chat/component/chat-input-operate/index.vue
ui/src/components/ai-chat/index.vue

fix: optimization chart operation style

---

ui/src/components/ai-chat/component/operation-button/ChatOperationButton.vue

fix: After trying voice playback three times and sending an error message, an error message pops up

fix: After trying voice playback three times and sending an error message, an error message pops up

---

apps/application/serializers/application_serializers.py

fix: Embedding dialogue asker parameter does not take effect

fix: Embedding dialogue asker parameter does not take effect

---

apps/setting/models_provider/impl/siliconCloud_model_provider/model/reranker.py

fix: siliconCloud rerank error  --bug=1054256 --user=王孝刚 【模型】添加硅基流动的重排序模型失败 https://www.tapd.cn/57709429/s/1679612

fix: siliconCloud rerank error

---

ui/src/components/ai-chat/component/chat-input-operate/index.vue
ui/src/components/ai-chat/component/user-form/index.vue
ui/src/components/ai-chat/index.vue

refactor: Dialogue logic optimization

refactor: Dialogue logic optimization

---

ui/src/components/ai-chat/component/operation-button/ChatOperationButton.vue

fix: Unfiltered special characters in voice playback

fix: Unfiltered special characters in voice playback

---

ui/src/components/ai-chat/component/operation-button/ChatOperationButton.vue

fix: Copy and delete form information

fix: Copy and delete form information

---

ui/src/views/chat/embed/index.vue
ui/src/views/chat/mobile/index.vue

fix: Dialogue embedding to modify name

fix: Dialogue embedding to modify name

---

apps/setting/models_provider/impl/openai_model_provider/model/embedding.py

fix: OpenAI Vector Model Using Openai Supplier

fix: OpenAI Vector Model Using Openai Supplier

---

ui/src/components/ai-chat/component/operation-button/ChatOperationButton.vue

fix: remove_form_rander

---

apps/setting/serializers/provider_serializers.py

fix: When other users download the public model, they cannot obtain the download data

fix: When other users download the public model, they cannot obtain the download data

---

apps/application/swagger_api/chat_api.py
apps/application/views/chat_views.py
apps/setting/serializers/provider_serializers.py

feat: Swagger document response for adding OpenAI interface

feat: Swagger document response for adding OpenAI interface

---

apps/setting/serializers/provider_serializers.py

fix: The interface for obtaining model metadata cannot access public models

fix: The interface for obtaining model metadata cannot access public models

---

ui/src/components/ai-chat/component/operation-button/ChatOperationButton.vue

fix: After the page is redirected, the voice playback does not stop

fix: After the page is redirected, the voice playback does not stop

---

ui/src/components/ai-chat/index.vue

perf: Optimization user input auto close when send message

---

apps/application/flow/step_node/search_dataset_node/impl/base_search_dataset_node.py

fix: Knowledge base retrieval segmentation sorted by relevance

fix: Knowledge base retrieval segmentation sorted by relevance

---

ui/src/components/ai-chat/component/operation-button/ChatOperationButton.vue

fix: During the debugging process, the browser voice will automatically play after returning to other pages

fix: During the debugging process, the browser voice will automatically play after returning to other pages

---

apps/common/handle/impl/pdf_split_handle.py

fix: limit chapter title length to 256 characters in pdf_split_handle.py  --bug=1054363 --user=刘瑞斌 【知识库】导入PDF文档，分段标题长度超长时，没有自动截断 https://www.tapd.cn/57709429/s/1681044

fix: limit chapter title length to 256 characters in pdf_split_handle.py

---

ui/src/views/template/component/CreateModelDialog.vue

fix: When adding a large language model in Application-Settings-Add AI node, the Base Model is not listed  --bug=1054358 --user=王孝刚 【应用】应用-设置-添加AI 节点时添加大语言模型，没有列出Base Model https://www.tapd.cn/57709429/s/1681102

fix: When adding a large language model in Application-Settings-Add AI node, the Base Model is not listed

---

ui/src/components/ai-chat/component/user-form/index.vue

fix: Quick issue, API parameters cannot be carried

fix: Quick issue, API parameters cannot be carried

---

ui/package.json
ui/src/components/index.ts
ui/src/workflow/nodes/condition-node/index.vue

feat: The workflow condition node supports drag and drop sorting

---

ui/src/workflow/nodes/application-node/index.vue

fix: The same observable object cannot appear twice in the same tree  --bug=1054451 --user=王孝刚 【应用嵌套】高级编排中应用关联设置用户输入参数的应用，会报该应用不可用 https://www.tapd.cn/57709429/s/1681701

fix: The same observable object cannot appear twice in the same tree

---

apps/common/util/ts_vecto_util.py

fix: jieba 分词使用全模式

---

apps/application/serializers/chat_serializers.py
apps/application/sql/export_application_chat.sql

fix: Missing fields in exported logs  --bug=1054500 --user=王孝刚 【应用】对话日志导出，没有携带用户信息 https://www.tapd.cn/57709429/s/1681984

fix: Missing fields in exported logs

---

apps/application/views/chat_views.py
ui/src/components/ai-chat/index.vue

fix: Workflow debugging for authorized applications will result in an error message indicating unauthorized access to the model

fix: Workflow debugging for authorized applications will result in an error message indicating unauthorized access to the model

---

ui/src/api/type/application.ts
ui/src/components/ai-chat/component/answer-content/index.vue

fix: The form recall node cannot respond

fix: The form recall node cannot respond

---

ui/src/components/model-select/index.vue

fix: When switching application models, the model parameters should be set to the default values of the current model

fix: When switching application models, the model parameters should be set to the default values of the current model

---

apps/dataset/serializers/dataset_serializers.py

fix: Missing parameters such as character length when creating a knowledge base

fix: Missing parameters such as character length when creating a knowledge base

---

apps/common/util/function_code.py
installer/Dockerfile

security: fix reverse shell vulnerability in function library.

security: fix reverse shell vulnerability in function library.

---

ui/src/components/ai-chat/component/answer-content/index.vue
ui/src/components/ai-chat/component/prologue-content/index.vue
ui/src/components/ai-chat/component/question-content/index.vue
ui/src/workflow/nodes/condition-node/index.vue

fix: chat avatar display issue fixed

---

ui/src/workflow/nodes/condition-node/index.vue

fix: condition node supports drag and drop

---

ui/src/workflow/nodes/condition-node/index.vue

fix: Judgment tool drag and drop sorting

fix: Judgment tool drag and drop sorting

---

ui/src/components/ai-chat/index.vue
ui/src/stores/modules/user.ts

fix: Historical user conversation data has been cleared

fix: Historical user conversation data has been cleared

---

ui/src/components/ai-chat/component/answer-content/index.vue
ui/src/components/ai-chat/component/question-content/index.vue
ui/src/views/chat/base/index.vue

fix: History record error in dialogue basic mode

---

ui/src/styles/md-editor.scss

fix: MD editor table cannot have too many columns and cannot scroll horizontally

fix: MD editor table cannot have too many columns and cannot scroll horizontally

---

ui/src/components/ai-chat/component/operation-button/ChatOperationButton.vue
ui/src/components/ai-chat/index.scss
ui/src/components/ai-chat/index.vue

fix: Optimize dialogue style

---

apps/common/handle/impl/table/xls_parse_table_handle.py

fix: handle line breaks in cell content for markdown table formatting  --bug=1054683 --user=刘瑞斌 【github#2831】知识库上传excel、应用编排文档内容提取节点中上传excel，单元格中有换行，导入后没有在一个单元格里显示 https://www.tapd.cn/57709429/s/1685274

fix: handle line breaks in cell content for markdown table formatting

---

ui/src/workflow/nodes/mcp-node/index.vue

refactor: enhance input handling for custom sources in form fields  --bug=1054775 --user=刘瑞斌 【应用编排】MCP调用节点，自定义工具参数建议支持选择数据类型 https://www.tapd.cn/57709429/s/1685483

refactor: enhance input handling for custom sources in form fields

---

apps/application/serializers/application_serializers.py

fix: application title error  --bug=1054724 --user=王孝刚 【github#2855】【应用】修改应用名称后，演示界面及访问链接的web标签页名称还是旧名称 https://www.tapd.cn/57709429/s/1685555

fix: application title error

---

README_CN.md

chore: Update README_CN.md

---

apps/common/auth/authenticate.py
apps/maxkb/urls.py
apps/users/views/user.py

fix: swagger

---

apps/common/constants/permission_constants.py
apps/modules/api/module.py
apps/modules/serializers/module.py
apps/modules/views/module.py

fix: improve module tree query to use Q object for filtering by workspace_id

fix: improve module tree query to use Q object for filtering by workspace_id

---

apps/tools/api/tool.py
apps/tools/serializers/tool.py
apps/tools/urls.py
apps/tools/views/tool.py

feat: add ToolTreeView and ToolTreeReadAPI for retrieving tools by workspace and module

feat: add ToolTreeView and ToolTreeReadAPI for retrieving tools by workspace and module

---

apps/locales/zh_CN/LC_MESSAGES/django.po
apps/locales/zh_Hant/LC_MESSAGES/django.po

fix: i18n error  --bug=1054853 --user=王孝刚 【API文档】-获取知识库文档分页列表接口的名称错误 https://www.tapd.cn/57709429/s/1688248

fix: i18n error

---

apps/modules/urls.py
apps/modules/views/module.py
apps/tools/api/tool.py
apps/tools/urls.py
apps/tools/views/tool.py

feat: consolidate module and tool views by removing redundant classes and updating API endpoints

feat: consolidate module and tool views by removing redundant classes and updating API endpoints

---

apps/setting/models_provider/base_model_provider.py
apps/setting/models_provider/impl/aliyun_bai_lian_model_provider/model/image.py
apps/setting/models_provider/impl/aliyun_bai_lian_model_provider/model/llm.py
apps/setting/models_provider/impl/base_chat_open_ai.py
apps/setting/models_provider/impl/deepseek_model_provider/model/llm.py
apps/setting/models_provider/impl/kimi_model_provider/model/llm.py
apps/setting/models_provider/impl/ollama_model_provider/model/image.py
apps/setting/models_provider/impl/openai_model_provider/model/image.py
apps/setting/models_provider/impl/openai_model_provider/model/llm.py
apps/setting/models_provider/impl/qwen_model_provider/model/image.py
apps/setting/models_provider/impl/qwen_model_provider/model/llm.py
apps/setting/models_provider/impl/siliconCloud_model_provider/model/image.py
apps/setting/models_provider/impl/siliconCloud_model_provider/model/llm.py
apps/setting/models_provider/impl/tencent_cloud_model_provider/model/llm.py
apps/setting/models_provider/impl/tencent_model_provider/model/image.py
apps/setting/models_provider/impl/vllm_model_provider/model/image.py
apps/setting/models_provider/impl/vllm_model_provider/model/llm.py
apps/setting/models_provider/impl/volcanic_engine_model_provider/model/image.py
apps/setting/models_provider/impl/volcanic_engine_model_provider/model/llm.py
apps/setting/models_provider/impl/xinference_model_provider/model/image.py
apps/setting/models_provider/impl/xinference_model_provider/model/llm.py
apps/setting/models_provider/impl/zhipu_model_provider/model/image.py

fix: Model parameters are not effective

fix: Model parameters are not effective

---

apps/application/flow/step_node/start_node/impl/base_start_node.py
apps/application/flow/workflow_manage.py
apps/application/serializers/chat_message_serializers.py
apps/application/views/chat_views.py
ui/src/components/ai-chat/component/chat-input-operate/index.vue
ui/src/locales/lang/en-US/common.ts
ui/src/locales/lang/zh-CN/common.ts
ui/src/locales/lang/zh-Hant/common.ts
ui/src/workflow/nodes/base-node/component/FileUploadSettingDialog.vue
ui/src/workflow/nodes/base-node/index.vue
ui/src/workflow/nodes/start-node/index.vue

feat: add support for uploading other file types and extend file upload settings  --story=1018411 --user=刘瑞斌 【工作流应用】文件上传可以支持其它文件类型 https://www.tapd.cn/57709429/s/1688679

feat: add support for uploading other file types and extend file upload settings

---

apps/application/serializers/chat_message_serializers.py

fix: OpenAI interface call for session, passing asker does not take effect

fix: OpenAI interface call for session, passing asker does not take effect

---

ui/src/components/markdown/MdRenderer.vue
ui/src/locales/lang/en-US/common.ts
ui/src/locales/lang/en-US/views/application-workflow.ts
ui/src/locales/lang/zh-CN/common.ts
ui/src/locales/lang/zh-CN/views/application-workflow.ts
ui/src/locales/lang/zh-Hant/common.ts
ui/src/locales/lang/zh-Hant/views/application-workflow.ts
ui/src/workflow/nodes/base-node/component/FileUploadSettingDialog.vue

feat: Adjust file upload and add other file function styles

---

ui/src/workflow/nodes/application-node/index.vue

fix: Edit advanced orchestration applications, add application nodes, and display that some applications are unavailable after being added

fix: Edit advanced orchestration applications, add application nodes, and display that some applications are unavailable after being added

---

ui/src/components/ai-chat/component/chat-input-operate/index.vue

fix: When automatic sending is not selected, the text conversion should be displayed in the position of the question input box

fix: When automatic sending is not selected, the text conversion should be displayed in the position of the question input box

---

apps/application/models/application.py

fix: When there is an empty string in the context, the conversation reports an error

fix: When there is an empty string in the context, the conversation reports an error

---

ui/src/views/login/forgot-password/index.vue

fix: The forgot password page displays an error  --bug=1055073 --user=王孝刚 【长城开发科技】自定平台登录设置在点击忘记密码时还是默认提示 https://www.tapd.cn/57709429/s/1689108

fix: The forgot password page displays an error

---

apps/common/handle/impl/doc_split_handle.py

fix: Docx segmented font title recognition

fix: Docx segmented font title recognition

---

ui/src/components/ai-chat/component/answer-content/index.vue
ui/src/components/ai-chat/index.vue

fix: collection form function cannot be used normally and will be stuck in the answer

fix: collection form function cannot be used normally and will be stuck in the answer

---

ui/src/components/ai-chat/component/chat-input-operate/index.vue
ui/src/workflow/nodes/base-node/component/FileUploadSettingDialog.vue

fix: upload file style

---

ui/src/stores/modules/user.ts

fix: Lost historical conversation records

fix: Lost historical conversation records

---

apps/setting/models_provider/impl/wenxin_model_provider/credential/llm.py

fix: Change the max_token of the Qianfan large model to max_output_token

fix: Change the max_token of the Qianfan large model to max_output_token

---

apps/setting/models_provider/impl/base_chat_open_ai.py

fix: The tag based thinking process does not output

fix: The tag based thinking process does not output

---

apps/application/serializers/application_serializers.py

fix: Thinking about process labels during simple application debugging does not take effect

fix: Thinking about process labels during simple application debugging does not take effect

---

apps/common/handle/impl/xls_split_handle.py

fix: update post_cell function to handle different newline characters in cell values  --bug=1054683 --user=刘瑞斌 【github#2831】知识库上传excel、应用编排文档内容提取节点中上传excel，单元格中有换行，导入后没有在一个单元格里显示 https://www.tapd.cn/57709429/s/1690232

fix: update post_cell function to handle different newline characters in cell values

---

apps/setting/models_provider/impl/ollama_model_provider/credential/llm.py

fix: Ollama maximum output token field

fix: Ollama maximum output token field

---

apps/common/management/commands/services/services/local_model.py
apps/setting/models_provider/impl/ollama_model_provider/credential/llm.py
apps/smartdoc/conf.py

fix: Ollama maximum output token field<br>feat: Add local model worker parameters

feat: Add local model worker parameters

---

apps/common/management/commands/services/services/local_model.py
ui/src/components/ai-chat/index.vue

build: ui build error

---

ui/src/components/ai-chat/index.vue

fix: User input parameter occupancy issue

fix: User input parameter occupancy issue

---

.github/dependabot.yml

ci: add pip package ecosystem support to dependabot configuration

ci: add pip package ecosystem support to dependabot configuration

---

apps/common/constants/permission_constants.py
apps/users/serializers/user.py
apps/users/views/user.py

feat: User profile returns permission role information

feat: User profile returns permission role information

---

ui/src/directives/hasPermission.ts
ui/src/directives/index.ts
ui/src/main.ts
ui/src/stores/modules/user.ts
ui/src/utils/permission/data.ts
ui/src/utils/permission/index.ts
ui/src/utils/permission/type.ts
ui/src/views/HomeView.vue

feat: UI permission instruction

feat: UI permission instruction

---

apps/common/auth/authentication.py

fix: authentication errors

---

apps/application/serializers/chat_serializers.py
apps/application/sql/list_application_chat.sql

perf: Slow dialogue log query

---

apps/dataset/serializers/file_serializers.py

when docx, xlsx files download, response header will be recognized as text/plain.

add support for docx, xlsx

---

apps/application/serializers/application_serializers.py

fix: During the conversation, there is sensitive data in the application profile obtained by the application

fix: During the conversation, there is sensitive data in the application profile obtained by the application

---

ui/src/workflow/nodes/application-node/index.vue

fix: Workflow application node parameter saving cannot be reflected back

fix: Workflow application node parameter saving cannot be reflected back

---

apps/setting/models_provider/impl/aliyun_bai_lian_model_provider/credential/llm.py

feat: Support Alibaba Bailian supplier qwen3 model

feat: Support Alibaba Bailian supplier qwen3 model

---

ui/src/views/application/component/ParamSettingDialog.vue

fix: The similarity of knowledge base mixed retrieval should be 0-2

fix: The similarity of knowledge base mixed retrieval should be 0-2

---

apps/application/serializers/application_serializers.py

fix: Cannot copy applications with opening statement characters exceeding 4096

fix: Cannot copy applications with opening statement characters exceeding 4096

---

apps/common/auth/handle/impl/user_token.py
apps/common/constants/permission_constants.py
apps/maxkb/urls.py
apps/system_manage/api/__init__.py
apps/system_manage/api/user_resource_permission.py
apps/system_manage/serializers/__init__.py
apps/system_manage/serializers/user_resource_permission.py
apps/system_manage/sql/check_member_permission_target_exists.sql
apps/system_manage/sql/get_user_resource_permission.sql
apps/system_manage/urls.py
apps/system_manage/views/__init__.py
apps/system_manage/views/user_resource_permission.py

feat: UserResourcePermission<br>feat: UserResourcePermission<br>feat: UserResourcePermission

feat: UserResourcePermission

---

apps/application/admin.py
apps/application/apps.py
apps/application/models/__init__.py
apps/application/models/application.py
apps/application/tests.py
apps/application/views/__init__.py
apps/common/utils/common.py
apps/workflow/admin.py
apps/workflow/apps.py
apps/workflow/models/__init__.py
apps/workflow/models/workflow.py
apps/workflow/tests.py
apps/workflow/views/__init__.py
apps/workflow/workflow/__init__.py
apps/workflow/workflow/common.py
apps/workflow/workflow/i_node.py
apps/workflow/workflow/nodes/__init__.py
apps/workflow/workflow/tools.py
apps/workflow/workflow/workflow_manage.py

feat: workflow init

---

apps/smartdoc/conf.py

feat: add pool options recycle

feat: add pool options recycle

---

ui/src/locales/lang/en-US/views/application-workflow.ts
ui/src/locales/lang/zh-CN/views/application-workflow.ts
ui/src/locales/lang/zh-Hant/views/application-workflow.ts
ui/src/workflow/nodes/mcp-node/index.vue

fix: update MCP server configuration text to include STREAMABLE_HTTP support  --bug=1056115 --user=刘瑞斌 【应用编排】编辑mcp节点的config后，提问会报错 https://www.tapd.cn/57709429/s/1699333 --bug=1056092 --user=刘瑞斌 【应用编排】MCP的支持文案要加上支持 Streamable HTTP https://www.tapd.cn/57709429/s/1699357

fix: update MCP server configuration text to include STREAMABLE_HTTP support

---

apps/common/config/embedding_config.py

perf: Refine the Model Manager code

perf: Refine the Model Manager code

---

apps/dataset/serializers/document_serializers.py

fix: Excel export prohibits inputting external links or formulas

fix: Excel export prohibits inputting external links or formulas

---

apps/application/flow/step_node/function_lib_node/impl/base_function_lib_node.py
apps/application/flow/step_node/function_node/impl/base_function_node.py

fix: When the function parameter is of non string type, if the parameter is empty, the function will run with an error #3053

fix: When the function parameter is of non string type, if the parameter is empty, the function will run with an error #3053

---

ui/src/styles/md-editor.scss

fix: Line break truncated characters in English(#3103)

---

ui/src/layout/components/breadcrumb/index.vue
ui/src/views/application/component/CreateApplicationDialog.vue

fix: breadcrumb issue

---

ui/src/views/application/component/ParamSettingDialog.vue

fix: Parameter setting page optimization

---

apps/common/handle/impl/table/xlsx_parse_table_handle.py

perf: Optimize document extraction for complex table files

perf: Optimize document extraction for complex table files

---

apps/common/util/common.py
apps/locales/en_US/LC_MESSAGES/django.po
apps/locales/zh_CN/LC_MESSAGES/django.po
apps/locales/zh_Hant/LC_MESSAGES/django.po
apps/smartdoc/settings/base.py
apps/users/serializers/user_serializers.py
apps/users/urls.py
apps/users/views/user.py
pyproject.toml
ui/src/api/type/user.ts
ui/src/api/user.ts
ui/src/locales/lang/en-US/views/user.ts
ui/src/locales/lang/zh-CN/views/user.ts
ui/src/locales/lang/zh-Hant/views/user.ts
ui/src/stores/modules/user.ts
ui/src/views/login/index.vue

feat: Login and add graphic captcha

feat: Login and add graphic captcha

---

ui/src/components/ai-chat/index.vue

fix: AI conversation jumps to 404

fix: AI conversation jumps to 404

---

apps/users/serializers/user_serializers.py

fix: Verification code is not case sensitive

fix: Verification code is not case sensitive

---

ui/src/workflow/nodes/base-node/index.vue

fix: The default suffix for workflow file upload nodes is set to uppercase DOC and PPT

fix: The default suffix for workflow file upload nodes is set to uppercase DOC and PPT

---

installer/Dockerfile

build: Sensitive directory permissions

build: Sensitive directory permissions

---

ui/src/workflow/nodes/form-node/index.ts

fix: The dropdown data of subsequent nodes in the form cannot be displayed back

fix: The dropdown data of subsequent nodes in the form cannot be displayed back

---

apps/common/field/common.py

feat: application save

---

apps/common/utils/common.py

feat: common

---

apps/common/constants/permission_constants.py
apps/locales/en_US/LC_MESSAGES/django.po
apps/locales/zh_CN/LC_MESSAGES/django.po
apps/locales/zh_Hant/LC_MESSAGES/django.po

feat: System api permission setting

feat: System api permission setting

---

apps/common/util/function_code.py

perf: Function library execution

perf: Function library execution

---

apps/common/field/common.py

fix: Fix Swagger document image upload

fix: Fix Swagger document image upload

---

apps/maxkb/conf.py

feat: use redis cache

---

ui/src/api/type/application.ts
ui/src/views/application/component/CreateApplicationDialog.vue
ui/src/views/application/index.vue

feat: create application ui

---

apps/common/auth/handle/impl/chat_anonymous_user_token.py

fix: anonymous authentication

---

apps/application/api/application_stats.py
apps/application/serializers/application_stats.py
apps/application/sql/chat_record_count_trend.sql
apps/application/sql/customer_count_trend.sql
apps/application/urls.py
apps/application/views/__init__.py
apps/application/views/application_stats.py

feat: application stats

---

apps/application/views/application_chat_record.py

fix: Modify openAPI description

fix: Modify openAPI description

---

apps/application/views/application.py
apps/system_manage/views/email_setting.py
apps/users/views/user.py

feat: Permission update

---

apps/application/chat_pipeline/step/chat_step/i_chat_step.py
apps/application/chat_pipeline/step/chat_step/impl/base_chat_step.py
apps/application/chat_pipeline/step/reset_problem_step/i_reset_problem_step.py
apps/application/chat_pipeline/step/reset_problem_step/impl/base_reset_problem_step.py
apps/application/chat_pipeline/step/search_dataset_step/i_search_dataset_step.py
apps/application/chat_pipeline/step/search_dataset_step/impl/base_search_dataset_step.py
apps/application/flow/step_node/ai_chat_step_node/impl/base_chat_node.py
apps/application/flow/step_node/image_generate_step_node/impl/base_image_generate_node.py
apps/application/flow/step_node/image_understand_step_node/impl/base_image_understand_node.py
apps/application/flow/step_node/question_node/impl/base_question_node.py
apps/application/flow/step_node/reranker_node/impl/base_reranker_node.py
apps/application/flow/step_node/search_dataset_node/impl/base_search_dataset_node.py
apps/application/flow/step_node/speech_to_text_step_node/impl/base_speech_to_text_node.py
apps/application/flow/step_node/text_to_speech_step_node/impl/base_text_to_speech_node.py
apps/application/serializers/application.py
apps/application/serializers/common.py
apps/application/views/application.py
apps/chat/serializers/chat.py
apps/models_provider/tools.py

fix: chat bugs

---

apps/application/serializers/application_access_token.py
apps/locales/en_US/LC_MESSAGES/django.po
apps/locales/zh_CN/LC_MESSAGES/django.po
apps/locales/zh_Hant/LC_MESSAGES/django.po
ui/src/api/application/application.ts
ui/src/views/application-overview/index.vue
ui/src/views/application-overview/xpack-component/XPackLimitDrawer.vue

feat: application assess

---

apps/common/auth/handle/impl/user_token.py
apps/common/constants/permission_constants.py
apps/users/serializers/user.py

feat: workspace manage role

---

apps/application/serializers/application.py
apps/application/sql/list_application_user_ee.sql
apps/knowledge/serializers/knowledge.py
apps/knowledge/sql/list_knowledge_user_ee.sql

fix: application knowledge list

fix: application knowledge list

---

ui/src/layout/layout-header/top-menu/index.vue
ui/src/router/index.ts
ui/src/router/modules/application.ts
ui/src/router/modules/document.ts
ui/src/router/modules/knowledge.ts
ui/src/router/modules/model.ts
ui/src/router/modules/tool.ts
ui/src/router/routes.ts
ui/src/views/no-permission/index.vue

feat: no permission route

---

apps/application/serializers/application.py

fix: application related knowledge

fix: application related knowledge

---

ui/admin.html
ui/chat.html
ui/src/components/markdown/MdRenderer.vue
ui/src/layout/login-layout/LoginLayout.vue
ui/src/layout/login-layout/UserLoginLayout.vue
ui/src/stores/modules/application.ts
ui/src/utils/common.ts
ui/src/views/chat/user-login/components/LoginLayout.vue
ui/src/views/system/resource-authorization/index.vue
ui/src/views/tool/component/EditAvatarDialog.vue

fix: ui bugs

---

apps/application/views/application.py
apps/application/views/application_access_token.py
apps/application/views/application_api_key.py
apps/application/views/application_chat.py
apps/application/views/application_chat_record.py
apps/application/views/application_stats.py
apps/application/views/application_version.py
apps/knowledge/views/document.py
apps/knowledge/views/knowledge.py
apps/knowledge/views/paragraph.py
apps/knowledge/views/problem.py
apps/models_provider/views/model.py
apps/tools/views/tool.py

feat: System common user permission to knowledge application tool model by resource authorization

feat: System common user permission to knowledge application tool model by resource authorization

---

apps/chat/serializers/chat_embed_serializers.py
apps/maxkb/urls.py
ui/admin.html
ui/env.d.ts
ui/src/stores/modules/application.ts
ui/src/stores/modules/chat-user.ts
ui/src/views/application-overview/component/EmbedDialog.vue

fix: Application embed

---

apps/chat/api/chat_api.py
apps/chat/serializers/chat_record.py
apps/chat/urls.py
apps/chat/views/chat_record.py
apps/tools/views/tool.py
ui/src/api/chat/chat.ts
ui/src/views/chat/pc/EditTitleDialog.vue
ui/src/views/chat/pc/index.vue

feat: Application conversation

feat: Application conversation

---

apps/knowledge/views/document.py

fix: Split permission in document import dialogue

fix: Split permission in document import dialogue

---

apps/application/sql/list_knowledge_paragraph_by_paragraph_id.sql
apps/knowledge/serializers/document.py
ui/src/components/ai-chat/component/answer-content/index.vue
ui/src/components/ai-chat/component/knowledge-source-component/ParagraphDocumentContent.vue
ui/src/components/ai-chat/component/knowledge-source-component/index.vue
ui/src/views/chat/pc/index.vue

feat: PDF Preview

---

apps/locales/en_US/LC_MESSAGES/django.po
apps/locales/zh_CN/LC_MESSAGES/django.po
apps/locales/zh_Hant/LC_MESSAGES/django.po

feat: Locales
